### ISSUE TITLE
Keyboard shortcuts for steam menu and QAM do not work in game

### ISSUE THREAD

**Issue by tfranken90** [ValveSoftware/steam-for-linux#10247]
#### Your system information

* Steam client version: 1685488080
* SteamOS version: chimeraos
* Opted into Steam client beta?: [Yes/No] no
* Opted into SteamOS beta?: [Yes/No]  no
* Have you checked for updates in Settings > System?: [Yes/No] no

#### Please describe your issue in as much detail as possible:
While inside the steam interface crtl+1 and ctrl+2 work for bringing up the system menu and QAM respectively. However, in game, these shortcuts do not work. This means that navigating steamos with only a keyboard is broken. This problem has been mentioned multiple times in community forums.

https://www.reddit.com/r/SteamDeck/comments/v3leah/steam_button_keyboard_shortcut/
https://www.reddit.com/r/SteamDeck/comments/wof9kk/keyboard_shortcuts_for_steam_special_buttons/

**Comment by tiggerbiggo** [comment]
Same issue here, this needs fixing. Having to go to the steam deck itself across the room to open the menu is terrible. Fix please.

**Comment by tfranken90** [comment]
@bertogg I have steam-for-linux installed on fedora and this shortcut works fine, so I don't think it belongs there.  It's unclear whether the issue is with Steam, SteamOS, gamescope-session, ChimeraOS, or etc. Hopefully this ambiguity will ultimately be resolved by the eventual official release of SteamOS.

**Comment by senolfeldmann** [comment]
This issue still persists.
These shortcuts have never worked inside a gamescope session while being ingame. It does not matter if it's on the steam deck, HoloIso, Bazzite, ChimeraOS etc.
CTRL+1 and CTRL+2 (and CTRL+0) are very bad hotkeys by the way and could block shortcuts of games. Because of this I would propose using Super (Windows key) instead of CTRL.

**Comment by Managor** [comment]
On top of making the shortcuts work in-game, the shortcuts should be changed to something like Shift+Tab for Steam menu and Super for QAM for a more consistent functionality with desktop mode.

**Comment by baconicsynergy** [comment]
This should be relatively quite simple to fix. I hope it gets some attention.

I use a keyboard and mouse with my Steam Deck a surprising amount of the time, especially when docked to a TV when my controller dies.

**Comment by Bondarenko199** [comment]
Same here. I thought it was a quite basic thing to have. It feels like this is the only thing that keeps me from switching to SteamDeck from my PC. If you have any updates, please, share with us. And thanks for such a good product. Much love

**Comment by totaltommygun** [comment]
While I don't think this issue applies to all Linux distributions, it _does_ happen on my Steam Deck, and it's very frustrating when trying to play docked in game mode. Would love to see a fix!

**Comment by oSoMoN** [comment]
There is no specific handling for `Ctrl+1` and `Ctrl+2` in the compositor. When the Steam client has focus, it gets the key events and displays the respective menus, but when a game has focus, it gets them first and they never reach the Steam client.

It wouldn't be difficult to intercept them in the compositor and forward them to the Steam client, but there is still the issue of potential conflicts with in-game shortcuts, highlighted in several comments. I think this requires careful consideration, and input from gamers and designers.

**Comment by totaltommygun** [comment]
> There is no specific handling for `Ctrl+1` and `Ctrl+2` in the compositor. When the Steam client has focus, it gets the key events and displays the respective menus, but when a game has focus, it gets them first and they never reach the Steam client.
> 
> It wouldn't be difficult to intercept them in the compositor and forward them to the Steam client, but there is still the issue of potential conflicts with in-game shortcuts, highlighted in several comments. I think this requires careful consideration, and input from gamers and designers.

We can just change the keybinding in-game. Not being able to access these steam menus while using keyboard and mouse in game mode is beyond frustrating, and I've seen a hand full of gamers agree just searching through the steam forums for a few minutes. I'm definitely not the only one hoping it gets fixed soon

**Comment by tiggerbiggo** [comment]
> There is no specific handling for `Ctrl+1` and `Ctrl+2` in the compositor. When the Steam client has focus, it gets the key events and displays the respective menus, but when a game has focus, it gets them first and they never reach the Steam client.
> 
> It wouldn't be difficult to intercept them in the compositor and forward them to the Steam client, but there is still the issue of potential conflicts with in-game shortcuts, highlighted in several comments. I think this requires careful consideration, and input from gamers and designers.

Right... But right now, there is no way whatsoever to "alt-tab" as it were. If you've just docked your steam deck, and use a mouse and keyboard, once you get into the game you either quit it or go over to the steam deck (which in my case would usually be across the room from me) to press one of the system buttons.

So why are we getting caught up in what keybinds conflict with what? Heck, if the keybindings aren't what you want them, you can't even visit the steam input options without quitting the entire game or going over to the steam deck anyway, which is a far worse issue which if this thread is still going I can only assume has not been fixed. It's really weird that this is still hanging around.

**Comment by tiggerbiggo** [comment]
Also want to second the suggestion above to use shift tab, as it's a known shortcut that does exactly what the user wants, to visit the steam menu to do steam stuff.

**Comment by AkazaRenn** [comment]
TBH we should just bind all Steam shortcuts to `super` key while in game mode, it not used at all right now, that's a huge waste.

**Comment by SilentException** [comment]
Latest Steam Deck Client beta update has this feature implemented. Haven't seen changelog for non Steam Deck client yet but I guess they will push it out soon as well.

https://store.steampowered.com/news/app/1675200/view/529847413482980683?l=english
> * Added in-game keyboard shortcuts to open the Main Menu and Quick Access Menu.
>   * Default Main Menu hotkey: Shift+Tab
>   * Default Quick Access Menu hotkey: Ctrl+Shift+Tab
>   * Customizable in Settings->In Game

**Comment by Managor** [comment]
Can confirm that this works on my Deck. Shift+Tab Ctrl+Shift+Tab open the menus as expected and Ctrl+1 and Ctrl+2 no longer exist as bindings

**Comment by cecton** [comment]
How about the F12 key for screenshots? Has it been fixed by that update too? It is weird when you plug the steam deck and you can't do the normal actions without reaching for a controller. 

I also noticed an inconsistency with the screenshot button on a gamepad vs steam deck itself: the xbox gamepad uses the xbox button + RT while the steam deck uses the xbox button + RB

**Comment by Managor** [comment]
I've noticed that too. This issue could probably use a note about that https://github.com/ValveSoftware/steam-for-linux/issues/11272

**Comment by njdom24** [comment]
It'd be useful to have this with `-gamepadui` on Desktop. Any chance this makes it to the standard Linux client?

**Comment by oSoMoN** [comment]
> Latest Steam Deck Client beta update has this feature implemented.

I can confirm. Shift+Tab and Ctrl+Shift+Tab work while in game, and can be configured in the "Settings->In Game" menu.

> Ctrl+1 and Ctrl+2 no longer exist as bindings

That's not what I'm seeing. Ctrl+1 and Ctrl+2 still work in the Steam client (not in game, but they never did there).

> How about the F12 key for screenshots? Has it been fixed by that update too?

Apparently not.

**Comment by matte-schwartz** [comment]
I periodically lose Shift + Tab and Ctrl + Shift + Tab at random with gamescope + gamepadui, both in-game but also within the Steam UI itself. They start working again after restarting gamescope-session though. Haven't found a trigger for what breaks it yet, but will grab Steam/gamescope logs next time it happens.

**Comment by njdom24** [comment]
> It'd be useful to have this with `-gamepadui` on Desktop. Any chance this makes it to the standard Linux client?

I tried again last night on the stable desktop Linux client through gamescope + `-gamepadui`, and it worked. Didn't see it in the announcement.

**Comment by kisak-valve** [comment]
Closing as fixed. Follow up issues should be tracked separately.
