### ISSUE TITLE
Steam no longer opens after system updates

### ISSUE THREAD

**Issue by grian32** [ValveSoftware/steam-for-linux#10417]
#### Your system information

* Steam client version (build number or date): Latest as I just reinstalled but can't check because Steam won't open. 
* Distribution (e.g. Ubuntu): PopOS 22.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14000825/steam-logs.tar.gz)
* GPU: Nvidia RTX 3050 Laptop

#### Please describe your issue in as much detail as possible:
After recently updating system packages and such steam no longer opens.
This is the output i get by running Steam in the command line:
```
steam.sh[15765]: Running Steam on pop 22.04 64-bit
steam.sh[15765]: STEAM_RUNTIME is enabled automatically
setup.sh[15890]: Steam runtime environment up-to-date!
steam.sh[15765]: Steam client's requirements are satisfied
tid(15973) burning pthread_key_t == 0 so we never use it
```

Seems to be an issue with Nvidia as when i run it off of the Cpu's IGPU it runs without issues.

#### Steps for reproducing this issue:

1. run `steam` in terminal

**Comment by lucifertdark** [comment]
I had to go into the .steam/steam/package folder & delete the files with beta in their names to get steam running again, it defaults back to the non beta version but at least it's working again.

**Comment by nopenopenope** [comment]
I had your issue before, what worked for me was to close the terminal windows where I ran steam previously, but it sounds like you have restarterd the machine, so I'd rather go for a "Same same but different" notice:

```
steam.sh[453121]: Running Steam on ubuntu 23.10 64-bit
steam.sh[453121]: STEAM_RUNTIME is enabled automatically
setup.sh[453190]: Steam runtime environment up-to-date!
steam.sh[453121]: Steam client's requirements are satisfied
tid(453255) burning pthread_key_t == 0 so we never use it
[2024-01-23 09:52:42] Startup - updater built Jan 20 2024 02:58:32
[2024-01-23 09:52:42] Startup - Steam Client launched with: '/home/nopenopenope/.steam/debian-installation/ubuntu12_32/steam' '-nominidumps' '-nobreakpad' '--reset'
[2024-01-23 09:52:42] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
01/23 09:52:42 Init: Installing breakpad exception handler for appid(steam)/version(1705720677)/tid(453255)
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
```

**Comment by lucifertdark** [comment]
I'm using version 545 & the problem is present with them on Ubuntu 22.04 for me. I get the exact same message grian32 is getting.

**Comment by nopenopenope** [comment]
Problem for me was resolved by simply restarting my machine.

**Comment by grian32** [comment]
As far as I can tell this seems to be an issue with the newer Nvidia Drivers, I fixed it by doing a refresh install (feature of popos which deletes all apps but keeps data, couldn't revert drivers manually due to other issues on my system at the time) to revert the drivers to an earlier version.

**Comment by ahjolinna** [comment]
I had this same issue with beta client, it would not load/open the app but I did see it on system-tray but it wont open the UI. Restarting with disabling the sandboxing or gpu accelartion webview didnt help either.

I also used nvidia  545 driver (just updated to newest [550.40.07 BETA](https://www.nvidia.com/download/driverResults.aspx/218153/) ) ....

I dont think its driver issue as it did work before on same driver version and **it works fine on stable client**


----

my system spec

```
Operating System: openSUSE MicroOS 20240122
KDE Plasma Version: 6.0.80
KDE Frameworks Version: 5.249.0
Qt Version: 6.6.1
Kernel Version: 6.6.11-1-default (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5700G with Radeon Graphics
Memory: 46.8 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
```

**Comment by lucifertdark** [comment]
I managed to sort my problem, it was GPU accelerated rendering being switched on, not sure why or when I switched it on, but it's back off & everything is back to normal for me.

**Comment by domdfcoding** [comment]
All I was seeing was the `tid(2749) burning pthread_key_t == 0 so we never use it` line. After restarting it still shows up but steam then opens as usual.

**Comment by Septimius-Severus** [comment]
Also running into this same issue, just updated arch today.

**Comment by kisak-valve** [comment]
Hello @Septimius-Severus, you're most likely looking for #10841 instead of this issue report.
