### ISSUE TITLE
Store fullscreen video broken

### ISSUE THREAD

**Issue by Zorrototo** [ValveSoftware/steam-for-linux#10692]
#### Your system information

* Steam client version (build number or date): 1711147596
* Distribution (e.g. Ubuntu): Manjaro KDE
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14782359/steam-logs.tar.gz)
* GPU: GTX 1060 and RX 6800 (on their own, not together, I recently replaced the video card)

#### Please describe your issue in as much detail as possible:
When you click the fullscreen button on a video there is no fullscreen video, only the audio, and the Steam client itself goes fullscreen with a black page content. You can't get out of this broken state with escape or ALT TAB, you can't interact with the client, you can recover by ALT TAB and right clicking the Steam icon, and clicking LIBRARY, then the client goes out of fullscreen and it behaves normally.

#### Steps for reproducing this issue:

1. click play on a video in the store
2. click the fullscreen button
3. observe the broken state with sound playing, no video displayed and the Steam client messed up, where you can't interact with anything

**Comment by Grntrenchman** [comment]
Getting the same Black Screen if I try to fullscreen a store video.

Running Nobara 39 KDE Plasma on AMD. Same issue using either Wayland or X11. Steam Beta or not.

Having different combinations of the acceleration options on/off does not affect issue.

As noted in [this issue](https://github.com/ValveSoftware/steam-for-linux/issues/10597#issuecomment-2043992756), the issue does not occur if the steam window is _NOT_ maximized when fullscreening the video, it only occurs when the steam window is already maximized.

Also, while testing the maximization, I noticed the same black screen issue occurs if switching from/to maximized while in the store, video or not. manually resizing the window does not cause the black screen. Switching to Library and back to Store brings the page back, changing or refreshing the store page by itself (via store tab button, back button, refresh button) stays black.

[Here are my steam logs.](https://github.com/ValveSoftware/steam-for-linux/files/15007254/steam-logs.tar.gz)

[Here is the requested system information.](https://gist.github.com/Grntrenchman/845483c7844d114d728cf2aa734036a1)

For now, the workaround is to never maximize the main steam window.

**Comment by Grntrenchman** [comment]
It seems this has been fixed in the latest client update, at least for me.

**Comment by Zorrototo** [comment]
It seems, indeed. Can't get out of the fullscreen video with Esacape key though, you need to click the fullscreen button.

**Comment by NaturalHate** [comment]
Can confirm to be (**Finally!!!**) fixed as well as the ESC issue (minor comparatively). Hopefully we'll see some more fixes for the other broken shit since the re-design, because ctrl+F search still doesn't work, the right click context menu still hangs or crashes the client sometimes and I still cannot copy a selected text via right click context menu.

**Comment by kisak-valve** [comment]
Closing because this issue appears to be resolved.

Hello @rommager, if you're still able to reproduce this issue on an up to date system, please open a new issue report so that your lookalike issue can be tracked properly.
