### ISSUE TITLE
[Remote Play] HEVC and AV1 video decoding greyed out/disabled in Steam beta client.

### ISSUE THREAD

**Issue by XaeroVincent** [ValveSoftware/steam-for-linux#11625]
#### Your system information

* Steam client version (build number or date): 1735842154
* Distribution (e.g. Ubuntu): EndeavourOS
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* GPU: AMD Radeon RX 6700XT

#### Please describe your issue in as much detail as possible:

After upgrading to the latest Steam Beta client, HEVC and AV1 video decoding options in the Remote Play settings can be enabled.
![remoteplay](https://github.com/user-attachments/assets/ee392fd7-b05b-4971-bf03-329a092ce8bd)

#### Steps for reproducing this issue:

1. Update to Steam Beta Client

**Comment by Sid127** [comment]
Seeing the same on my system with an RTX 3070. Beta client has HEVC and AV1 decode options greyed out while they're toggle-able on the main client

**Comment by Lifeismana** [comment]
Fixed in today's beta

**Comment by Sid127** [comment]
can confirm, fixed in the latest beta

**Comment by e270889o** [comment]
Same here

**Comment by remotebert** [comment]
Still having this issue with AV1 video greyed out in the Steam Deck Remote Play settings.

**Comment by joegibes** [comment]
Same, in Stable and Beta (as of 3/14/2025). AV1 is grayed out. I have a 4070 and could previously stream Remote Play with AV1.

**Comment by phillipegf** [comment]
AV1 is still disabled on beta 4/7/2025 with Radeon RX 7800 XT

**Comment by luisfagundes94** [comment]
Still happening with latest stable version. (RTX 4080)

**Comment by GribanovIvan** [comment]
3050 mobile, Radeon 660M, stable, beta tested, same here

**Comment by yataktyni** [comment]
rtx5080, av1 is still disabled

**Comment by epjaeger** [comment]
AV1 is still disabled on latest Steam Deck Stable and Beta builds as of 5 minutes ago.  Host machine is rtx3080 i7 win11.

**Comment by GribanovIvan** [comment]
Also, just dropping it here: Steam on windows works fine on same pc, AV1 can be enabled and just works just perfectly. AV1 content can be played perfectly on both system. Feels like someone just decided that no AV1 for Linux. Maybe, Steam Deck is not powerful enough to utilize AV1 as good as HEVC or something, so someone decided just gray it for all Linux machines...

Valve, Linux community are here, we are willing to help you if issue is something more than lazy #define noav1. Valve, please, enable it in steam beta, so we can test it and point if something is wrong or describe what stopping you from enabling it, someone surely will help you make Steam a better place for everyone.

**Comment by AkazaRenn** [comment]
6950XT, I don't even have the options for HEVC and AV1? I'm on Bazzite OS desktop mode, host options are available but no encoding toggles.

**Comment by jcline8** [comment]
Intel Arc A380, Bazzite 43 (bazzite-deck image): AV1 is disabled on my Intel Arc card. I have the option for HVEC. My settings look like @Sid127's.

**Comment by Lawstorant** [comment]
9070 XT, 7840U (RDNA 3.5) and steam deck here. All lack the option to turn on AV1 on the client side + my PC and laptop (both support AV1 encode) lack the option to encode with AV1

**Comment by shanold** [comment]
Can enable HEVC but not AV1 Kubuntu 25.10 steam stable 1769025840  Ryzen 7 5800x and RX 7900 XTX

**Comment by Lawstorant** [comment]
@kisak-valve is there even a clue as to why this happens? Detecting AV1 VAAPI capabilities should be pretty easy and should just work. Are there just some internal issues with Steam Remote Play and AV1 that keep this unavailable? At least knowing that it's not a random issue but intended behavior would be some kind of info to keep this out of our heads.

**Comment by aqtie** [comment]
av1 greyed out for me, openSUSE Tumbleweed 20260126 w/ 9800x3d & 9070xt. I am using mesa from packman repo so im assuming its a steam issue and not related to opensuse repo mesa.

**Comment by joegibes** [comment]
> Same, in Stable and Beta (as of 3/14/2025). AV1 is grayed out. I have a 4070 and could previously stream Remote Play with AV1.

SteamOS team, any updates on AV1 streaming being broken, 1 year later? I don't mean to spam, I just really miss being able to use AV1 (which worked ok before) for smooth, latency-free streaming to Steam Deck.

**Comment by dmytro-liashko-dev** [comment]
Same here, I have AMD 8845HS with Radeon 780M integrated graphics, perfectly capable of encoding and decoding the AV1. However, on Fedora Linux 44 with Linux kernel 7.0.8 and Mesa 26.0.6 AV1 option is still greyed out. I have to rely on HEVC for decoding.  I use Steam beta channel installed from RPM package.

**Comment by GribanovIvan** [comment]
I guess we should stop samehering. This thread already highlights that AV1 is grayed out on AMD, Intel, Nvidia, SteamOS, Arch, Bazzite, Valve produced hardware, rpm, flatpak, native package and every combination of above.

**Comment by Lawstorant** [comment]
Just FYI, AV1 is back on the menu at least with beta RT3 client on the Steam Deck Oled. Didn't try it yet on other devices

Update:
Yes, it's available on all my devices now (SD, RDNA3.5 laptop and 9070 XT). Only available with RT3 beta client but at least everywhere.
