### ISSUE TITLE
Mishandling of a broken depot configuration (Steam Deck vs. generic Linux)

### ISSUE THREAD

**Issue by dsalt** [ValveSoftware/steam-for-linux#12019]
Game: Gripper's 3D/VR Adventure
Game id: 3549440
Steam client build stamp: 1747431473

This game has two depots, [3549441](https://steamdb.info/depot/3549441/) (Windows) and [3549442](https://steamdb.info/depot/3549442/) (Linux, Steam Deck).

We're concerned only with the latter depot here: it is misconfigured, and in a way which isn't handled well: the configuration is `Linux` and `Steam Deck`; no `32-bit` or `64-bit`.

On a typical desktop or laptop PC (testing on my desktop box, running Devuan stable), installing this game installs nothing (no depots are listed in the app manifest); consequently, attempting to launch the game results in a “missing game executable” error.

Installing and launching it on a Steam Deck both work fine. Copying the Deck-installed files across to my desktop box allows launching of the game; it then ‘works’, as in it can be launched and (to some extent) played.

Given the lack of a depot configured for generic Linux (either i386 or amd64), either the Deck-specific depot should be installed anyway (possibly with warnings) or the Windows version should be installed instead.

**Comment by bokahrij** [comment]
Hello as the developer for Gripper's 3D/VR Adventure. I have changed the Linux + SteamOS CPU Architecture from "Any" to "64bit". I'm not sure if that will fix the issue as I cannot currently test on a Linux machine. I would love to fix this issue though. Also I do not see a way to set only Linux or only SteamOS, only an option of Linux + SteamOS (regarding launch options).

**Comment by kisak-valve** [comment]
Hello @bokahrij, I'm not particularly familiar with this topic, but I think the key detail here is that depot 3549442 is marked `Steam Deck`, and ideally that depot config is only used for a small subset of a game to get it working on handhelds, like if you'd need to override some in-game videos with a repacked version using a compatible codec or optimize for smaller disk availability. If the depot was only marked `Linux`, without `Steam Deck`, that depot will still be used with the Steam Deck when Steam is configured to use the Linux native variant of the game.

**Comment by bokahrij** [comment]
Under the linux depot I had it set to steam deck only, I have updated it to All so I'm hoping that will fix the issue.

**Comment by NotMrFlibble** [comment]
Seems fine now.

I'm thinking that maybe there's some Steamworks documentation and/or UI which could be improved regarding depot configuration.

**Comment by kisak-valve** [comment]
Noted in #12344, Baldur's Gate 3 now has a similar misconfiguration.

**Comment by cybik** [comment]
@kisak-valve at this point it feels deliberate in the case of Baldur's Gate III. [(thread link)](https://www.reddit.com/r/BaldursGate3/comments/1nok0jf/comment/nfsq7on/)
<img width="748" height="496" alt="Image" src="https://github.com/user-attachments/assets/56e2b134-4bb6-4bb2-abaa-c75c0ee0e5d0" />

If devs are going to be this specific about platform support, may I respectfully request a very loud option for Linux desktop users to "force enable Steam Deck depot configuration" on a per-game basis? With a rather in-your-face and loud warning about game support (or lack thereof) if this option is enabled? Nevermind that running a Windows build on Linux through Proton isn't exactly supported by all, but having the OPTION to be counted as a "Steam Deck", "SteamOS" or "SteamOS-Related" platform instead of a "Faked Windows" player would be appreciated, especially since I _**know**_ this kind of data would help the case of Linux and SteamOS/Deck when presenting to producers and miscelaneous C-Suites and investors when defending Linux-related development expenses.

EDITED: [this might be getting solved](https://github.com/ValveSoftware/steam-for-linux/issues/12019#issuecomment-3325432697).

**Comment by FaeAlicia** [comment]
Why is there a Steam Deck repo in the first place? If it's because of handheld device screen size, why call it Steam Deck and not just Linux Handheld?

Also, forcing devs that use the handheld repo to also populate the desktop equivalents should solve these issues.

Well, with one exception. Some devs explicitly disable Linux support *except for* Steam Deck. Broken by design stuff like that honestly shouldn't be allowed. I get that different Linux distros can behave differently, but every time this happens, the game works fine anyway. It's just some anticheat or something that forcibly crashes out when it can't install its rootkit or whatever.

In other words, there's several design flaws with how things are set up atm that allows devs to screw over their players just for using an OS they don't like. These need to be addressed.

**Comment by Milli189** [comment]
> Noted in [#12344](https://github.com/ValveSoftware/steam-for-linux/issues/12344), Baldur's Gate 3 now has a similar misconfiguration.

I hope this can be fixed as soon as possible.

**Comment by cybik** [comment]
Looks like [someone got through](https://steamdb.info/app/1086940/history/?changeid=31271015) to their Release team, or gave the dev team enough spell slots to override decisions.

There's still an issue with the launcher config, Non-Deck Linux still defaults to the Larian Launcher EXE. Need to use fancy forbidden futzing to yeet the Windows (and mac) launch options to force the Linux binary, but after that, the build works.

Yet another edit: Config shenanigans [appear to be unneeded now](https://steamdb.info/app/1086940/history/?changeid=31273477).

**Comment by ChristophHaag** [comment]
Is [Cowbots and Aliens](https://steamdb.info/app/517670/) affected too? It too downloads an empty directory on desktop Linux.

**Comment by dsalt** [comment]
> Is [Cowbots and Aliens](https://steamdb.info/app/517670/) affected too? It too downloads an empty directory on desktop Linux.

And on Deck you get the Windows version?

Given that the Linux depot is marked as ‘unused’, I find it reasonable to expect the Windows version to be installed by default; and, given actual content to install, I'd expect to be able to override that default.
