### ISSUE TITLE
Steam and SIGTERM

### ISSUE THREAD

**Issue by fbt** [ValveSoftware/steam-for-linux#3005]
[fbt@cetaganda ~]$ cat .steam/steam.pid 
5875
[fbt@cetaganda ~]$ ps aux | grep 5875
fbt       5875  3.6  1.5 619964 259296 pts/2   Sl   21:09   0:07 /home/trash/steam/ubuntu12_32/steam
[fbt@cetaganda ~]$ kill 5875

SIGTERM doesn't have any effect on the main steam process.
Considering that SIGTERM is the default kill signal that is supposed to be a way to politely ask a process to clean up and exit, it should work on steam.

**Comment by fbt** [comment]
Any news on this at all?

**Comment by SEAPUNK** [comment]
**Huge** +1. When steam ignores SIGTERM, the whole system, during shutdown, waits for Steam to exit, before killing it.

**Comment by prozacgod** [comment]
It's been 3 years, and no response on such a simple request, that's based on standards for the operating system. 

I recently wanted to handle properly shutting down steam on my computer through a custom daemon tool.  You can't do it.  Steam won't allow it.

Why is this issue not even been responded too?  SIGTERM is a standard basic mechanism.

**Comment by prozacgod** [comment]
If there are technical hurdles to be surpassed, posting such answers here would be of benefit to the community and Linux game developers, as they can design for a spec Valve could release.

Please post a technical synopsis of the challenges implementing this would face.

**Comment by SEAPUNK** [comment]
I bet it'll be another 5-10 years before Valve even bothers to look at this.

**Comment by calexil** [comment]
I can't believe they still haven't fixed this, confirming that on all my machines, if steam is running and I shutdown the entire system hangs for 30 seconds while it waits for steam to shutdown first.

this is related to #3301

**Comment by fbt** [comment]
They probably just don't care. This is a very minor issue that doesn't actually affect many people. It's a question of convention compliance, not something that actively makes users' lives worse.

In other words, welcome to enterprise proprietary software development. Fuck platform-specific conventions, no one cares.

**Comment by SEAPUNK** [comment]
@fbt I'm doubtful that this "doesn't actually affect many people", unless other distros don't bother to wait for processes to exit, or have created workarounds for this problem.

More likely, the people that are affected by this issue wouldn't know why this is happening, and wouldn't know to look for this issue.

**Comment by SEAPUNK** [comment]
Quite disappointing how Valve announced its support for Linux, but never really bothered to go through with it fully and just stopped bothering somewhere in the middle of "nonexistent support" and "adequate support".

**Comment by fbt** [comment]
@SEAPUNK well I do have other processes that won't die porperly on a SIGTERM, which slows down my shutdown time (although it's 30 sec. vs the default of 90 for systemd :) ), and I doubt a lot if users actually realise that it's Steam that is the problem for their shutdown times.

**Comment by SEAPUNK** [comment]
@fbt I've never had any other process that did this to me.

Assuming normal everyday usage: internet browser, music player, mail browser, office suite and the DE of choice and all their "extras" (file manager, image viewer, blah blah blah), only Steam out of that large set of software doesn't stop on SIGTERM. Unless the software that you use that doesn't stop on SIGTERM is an everyday tool, I would consider your argument a much more narrow edge case to warrant a counterargument to the importance of this issue.

But I digress.

**Comment by prozacgod** [comment]
@fbt - Actually I bet most people don't notice this bug because steam crashes every so often, so its already closed, and many of us Linux desktop users are always running, with up times into the 150+ days (me).  Often I just close out of it for resources

I was looking into it because I'm working on a "Steam launching supervisor over DBUS" so I can hack my personal edge case. I want to use xrandr to adjust my displays to 1080p single head, when launching steam.  So that steam link streaming is less painful.

It felt like the right path to create a daemon for launching and controlling steam.

I suspect the issue might be related to child processes, most of the games they have aren't really designed to be fully integrated into a "console" or "supervised" experience.  I wonder if the games steam launches respond to a SIGTERM

How would a game launched through steam need to react to a SIGTERM, like if steam gets the SIGTERM and then the game gets it ... do we save state?  drop dead? wait for user input?  

Steam on Linux likely needs to be a full desktop environment in order to fully overtake the game applications. With compositing window manager (something like gnome)

**Comment by xpander69** [comment]
ohh that explains why my logouts take so long.

i usualy shut down via systemctl poweroff, thatone goes instantly.. maybe i shouldnt use that.
but shutting down from DE waits super long.

**Comment by victoredwardocallaghan** [comment]
@triage-valve any reason why has still not been fixed? This seems trivial to me.

**Comment by kisak-valve** [comment]
As noted in #4771, the client should also respond to SIGINT

**Comment by kisak-valve** [comment]
Closing as fixed in the [2017-01-05 steam beta client update](http://steamcommunity.com/groups/SteamClientBeta#announcements/detail/586991182161672256). SIGINT also closed steam in my test.

**Comment by SEAPUNK** [comment]
Awesome, thank you!

**Comment by fbt** [comment]
Wow. Didn't actually expect this. Thanks, maybe my desktop system will not wait 30 seconds on reboot every time I forgot to kill Steam manually now! :)

**Comment by calexil** [comment]
this issue was NOT resolved, mint 18.1 mate, still hangs for 30 seconds on shutdown if steam is open
