### ISSUE TITLE
Download link on steam.com returns HTTP 403 Forbidden

### ISSUE THREAD

**Issue by buro9** [ValveSoftware/steam-for-linux#3465]
The link http://store.steampowered.com/about/ to download and install Steam from http://repo.steampowered.com/steam/archive/precise/steam_latest.deb currently returns a 403 Forbidden.

#3362 also covered this a couple of months ago, but is marked as closed and I cannot re-open.

I've found this: http://repo.steampowered.com/steam/pool/steam/s/steam/ but not sure which one installs Steam on an Intel Xeon system.

**Comment by johnv-valve** [comment]
this was fixed a while ago

**Comment by reyhansofian** [comment]
It's still happen to me

**Comment by tragiclifestories** [comment]
And I'm getting it now.

**Comment by ta2000** [comment]
I am also getting a 403 on http://repo.steampowered.com/steam/archive/precise/steam_latest.deb

**Comment by Eitz** [comment]
Why was this closed? After years, still a problem.

![image](https://cloud.githubusercontent.com/assets/6805910/20688144/bea3a4dc-b5a6-11e6-86ce-81b22ac51d6c.png)

![image](https://cloud.githubusercontent.com/assets/6805910/20688157/cfa7c682-b5a6-11e6-8936-1bdd97146d28.png)
