### ISSUE TITLE
several games have no sound on fedora 21

### ISSUE THREAD

**Issue by MaxPayneFH** [ValveSoftware/steam-for-linux#3864]
While trying to play non valve games on fedora 21, I found out to my dismay that they don't have sound, despite appearing to work very well on the visual side of things.

Games with sound:
All valve games I've tried
Civilization Beyond Earth 
Civilization V
Serius Sam 3

Games without sound:
Bioshock: Infinite
BorderLands 2
Chivalry: Medieval Warfare
Killing Floor
Metro 2033 Redux
Metro: Last Light
Metro: Last Light Redux
The Witcher 2: Assasins of Kings Enhanced Edition
Worms Reloaded

Back when I was still using fedora 20 I had sound on Metro: Last Light and Killing Floor, but nowadays they are mute.

Hopefully someone will have figured out a way to bring back sound to these games, but searching the issues here only showed up unrelated stuff.

Basic System Specs:
OS: Fedora 21
Window Manager: Gnome 3.14.2
kernel: 4.0.4
Video Driver: 352.09(Nvidia beta proprietary driver directlly from their website)
Sound card:  Realtek ALC889 (motherboard integrated sound card)
CPU: AMD FX8350
RAM: 16GB
Video Cards: Nvidia GTX760 SLI(AA mode)

Thanks in adavance for any help given.

**Comment by Celexi** [comment]
Hi,

  I did not have any issues in fedora 21 ( now in 22 ) with sound, except for dota 2 which required a selinux exception (selinux troubleshooter will tell you) is your pulseaudio properly set and not corrupted?

**Comment by MaxPayneFH** [comment]
Hello,

How can you tell if pulseaudio is corrupted or not? 
Apart from the games I mentioned before, sound works pretty well, even in vlc, clementine, firefox, teamspeak, mumble and probablly any other program I haven't tried.
csgo had an selinux exception that made the game crash, but that was solved on selinux troubleshooter, and not sure it was ever sound related in the first place, apart from that there's that bug(https://github.com/ValveSoftware/Counter-Strike-Global-Offensive/issues/12#issuecomment-107076835) that prevents you from changing speaker configuration the headphones, however that seems to be something csgo specific.

**Comment by MaxPayneFH** [comment]
After trying some of the games on other distros and goggling a little, I found out that Metro: Last light and Killing Floor have sound on ubuntu 14.04LTS out of the box, on OpenSuse Tumbleweed Killing Floor and THE Witcher 2 also as sound out of the box but  Metro: Last light does not, fortunately adding SDL_AUDIODRIVER=alsa %command% to the launch options is a workaround.

On Fedora 21 the same workaround by itself did not work, it was necessary to run "pulseaudio --kill" and "alsactl kill rescan" on the terminal for sound to work, this workaround on fedora worked for all the Metro franchise games, Killing Floor, Chivalry: Medieval Warfare and Borderlands 2, unfortunately it didn't work for Bioshock: Infinite, The Witcher 2 and Worms Reloaded, so amongst the games on my library those remain without sound on Fedora 21.

**Comment by MaxPayneFH** [comment]
Not sure if this was partially fixed on your end or on fedora's but the games that didn't have sound at all even with workaround now have sound on fedora 21, that games that required the annoying workaround to have sound still need so.
 The most weird situation is on Chivalry Medieval Warfare,  where you have sound on the intro (the unreal engine logo thin and stuff), but then no sound in-game if your not using the workaround, and if you use the workaround there is no sound during the unreal engine logo thing but at least there is sound in-game.

Tried fedora 22 on a different partition and there Metro 2033 had sound without the workaround.

If this partial fix was your doing you have my thanks

**Comment by MaxPayneFH** [comment]
Not sure if this was partially fixed on your end or on fedora's but the games that didn't have sound at all even with workaround now have sound on fedora 21, the games that required the annoying workaround to have sound still need so.
 The most weird situation is on Chivalry Medieval Warfare,  where you have sound on the intro (the unreal engine logo thin and stuff), but then no sound in-game if your not using the workaround, and if you use the workaround there is no sound during the unreal engine logo thing but at least there is sound in-game.

Tried fedora 22 on a different partition and there Metro 2033 had sound without the workaround.

If this partial fix was your doing you have my thanks

**Comment by Germano0** [comment]
Confirming on Fedora 25 with steam-1.0.0.53-1.fc24.i686. `SDL_AUDIODRIVER=alsa steam` does not solve the problem, but I could see some particular messages like

```
>>> Adding process 3375 for game ID *removed_for_privacy*
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused
```


I attach some useful infos

```
# lsmod
Module                  Size  Used by
uas                    24576  0
usb_storage            65536  1 uas
xt_CHECKSUM            16384  1
ipt_MASQUERADE         16384  3
nf_nat_masquerade_ipv4    16384  1 ipt_MASQUERADE
tun                    28672  1
ip6t_rpfilter          16384  1
ip6t_REJECT            16384  2
nf_reject_ipv6         16384  1 ip6t_REJECT
xt_conntrack           16384  32
ip_set                 36864  0
nfnetlink              16384  1 ip_set
ebtable_broute         16384  1
bridge                131072  1 ebtable_broute
stp                    16384  1 bridge
llc                    16384  2 bridge,stp
ebtable_nat            16384  1
ip6table_nat           16384  1
nf_conntrack_ipv6      20480  17
nf_defrag_ipv6         36864  1 nf_conntrack_ipv6
nf_nat_ipv6            16384  1 ip6table_nat
ip6table_mangle        16384  1
ip6table_raw           16384  1
ip6table_security      16384  1
iptable_nat            16384  1
nf_conntrack_ipv4      16384  17
nf_defrag_ipv4         16384  1 nf_conntrack_ipv4
nf_nat_ipv4            16384  1 iptable_nat
nf_nat                 28672  3 nf_nat_ipv6,nf_nat_masquerade_ipv4,nf_nat_ipv4
iptable_mangle         16384  1
iptable_raw            16384  1
iptable_security       16384  1
ebtable_filter         16384  1
ebtables               36864  3 ebtable_filter,ebtable_nat,ebtable_broute
ip6table_filter        16384  1
ip6_tables             28672  5 ip6table_mangle,ip6table_filter,ip6table_security,ip6table_raw,ip6table_nat
joydev                 20480  0
snd_hda_codec_hdmi     45056  1
snd_hda_intel          36864  3
snd_virtuoso           49152  3
kvm_amd                73728  0
snd_hda_codec         126976  2 snd_hda_intel,snd_hda_codec_hdmi
snd_oxygen_lib         40960  1 snd_virtuoso
snd_hda_core           81920  3 snd_hda_intel,snd_hda_codec,snd_hda_codec_hdmi
kvm                   581632  1 kvm_amd
snd_hwdep              16384  1 snd_hda_codec
snd_mpu401_uart        16384  1 snd_oxygen_lib
snd_rawmidi            32768  1 snd_mpu401_uart
snd_seq                69632  0
snd_seq_device         16384  2 snd_seq,snd_rawmidi
ppdev                  20480  0
snd_pcm               118784  5 snd_oxygen_lib,snd_hda_intel,snd_hda_codec,snd_hda_core,snd_hda_codec_hdmi
irqbypass              16384  1 kvm
k10temp                16384  0
snd_timer              32768  2 snd_seq,snd_pcm
snd                    86016  24 snd_oxygen_lib,snd_hda_intel,snd_hwdep,snd_seq,snd_hda_codec,snd_timer,snd_mpu401_uart,snd_rawmidi,snd_hda_codec_hdmi,snd_seq_device,snd_virtuoso,snd_pcm
soundcore              16384  1 snd
wmi                    16384  0
parport_pc             28672  0
parport                49152  2 parport_pc,ppdev
shpchp                 36864  0
sp5100_tco             16384  0
i2c_piix4              24576  0
acpi_cpufreq           20480  0
tpm_tis                16384  0
tpm_tis_core           20480  1 tpm_tis
tpm                    45056  2 tpm_tis,tpm_tis_core
binfmt_misc            20480  1
amdkfd                139264  1
amd_iommu_v2           20480  1 amdkfd
amdgpu               1200128  52
i2c_algo_bit           16384  1 amdgpu
firewire_ohci          40960  0
drm_kms_helper        151552  1 amdgpu
serio_raw              16384  0
ttm                    94208  1 amdgpu
firewire_core          65536  1 firewire_ohci
ata_generic            16384  0
pata_acpi              16384  0
crc_itu_t              16384  1 firewire_core
drm                   344064  24 amdgpu,ttm,drm_kms_helper
r8169                  81920  0
pata_jmicron           16384  0
mii                    16384  1 r8169
fjes                   28672  0
nf_conntrack_pptp      16384  0
nf_conntrack_proto_gre    16384  1 nf_conntrack_pptp
nf_conntrack          106496  9 nf_conntrack_ipv6,nf_conntrack_ipv4,nf_conntrack_pptp,nf_conntrack_proto_gre,nf_nat_ipv6,nf_nat_masquerade_ipv4,xt_conntrack,nf_nat_ipv4,nf_nat
```
```
# lspci -vv
08:06.0 Multimedia audio controller: C-Media Electronics Inc CMI8788 [Oxygen HD Audio]
        Subsystem: ASUSTeK Computer Inc. Virtuoso 100 (Xonar ST)
        Control: I/O+ Mem- BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=medium >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 32 (500ns min, 6000ns max)
        Interrupt: pin A routed to IRQ 20
        NUMA node: 0
        Region 0: I/O ports at 7e00 [size=256]
        Capabilities: [c0] Power Management version 2
                Flags: PMEClk- DSI- D1+ D2+ AuxCurrent=0mA PME(D0-,D1-,D2-,D3hot-,D3cold-)
                Status: D0 NoSoftRst- PME-Enable- DSel=0 DScale=0 PME-
        Kernel driver in use: snd_virtuoso
        Kernel modules: snd_virtuoso
```

```
!!################################
!!ALSA Information Script v 0.4.64
!!################################


!!Linux Distribution
!!------------------

Fedora release 24 (Twenty Four) NAME=Fedora ID=fedora PRETTY_NAME="Fedora 24 (Twenty Four)" CPE_NAME="cpe:/o:fedoraproject:fedora:24" HOME_URL="https://fedoraproject.org/" BUG_REPORT_URL="https://bugzilla.redhat.com/" REDHAT_BUGZILLA_PRODUCT="Fedora" REDHAT_BUGZILLA_PRODUCT_VERSION=24 REDHAT_SUPPORT_PRODUCT="Fedora" REDHAT_SUPPORT_PRODUCT_VERSION=24 PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy Fedora release 24 (Twenty Four) Fedora release 24 (Twenty Four)


!!DMI Information
!!---------------

Manufacturer:      Gigabyte Technology Co., Ltd.
Product Name:      GA-890FXA-UD5
Product Version:    
Firmware Version:  F6


!!Kernel Information
!!------------------

Kernel release:    4.8.10-200.fc24.x86_64
Operating System:  GNU/Linux
Architecture:      x86_64
Processor:         x86_64
SMP Enabled:       Yes


!!ALSA Version
!!------------

Driver version:     k4.8.10-200.fc24.x86_64
Library version:    1.1.1
Utilities version:  1.1.1


!!Loaded ALSA modules
!!-------------------

snd_virtuoso
snd_hda_intel


!!Sound Servers on this system
!!----------------------------

Pulseaudio:
      Installed - Yes (/usr/bin/pulseaudio)
      Running - Yes

Jack:
      Installed - Yes (/usr/bin/jackd)
      Running - No


!!Soundcards recognised by ALSA
!!-----------------------------

 0 [ST             ]: AV200 - Xonar ST
                      Asus Virtuoso 100 at 0x7e00, irq 20
 1 [HDMI           ]: HDA-Intel - HDA ATI HDMI
                      HDA ATI HDMI at 0xfd9fc000 irq 33


!!PCI Soundcards installed in the system
!!--------------------------------------

01:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Device aaf0
08:06.0 Multimedia audio controller: C-Media Electronics Inc CMI8788 [Oxygen HD Audio]


!!Advanced information - PCI Vendor/Device/Subsystem ID's
!!-------------------------------------------------------

01:00.1 0403: 1002:aaf0
	Subsystem: 1682:aaf0
--
08:06.0 0401: 13f6:8788
	Subsystem: 1043:835d


!!Loaded sound module options
!!---------------------------

!!Module: snd_virtuoso
	enable : Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y
	id : (null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null)
	index : -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

!!Module: snd_hda_intel
	align_buffer_size : -1
	bdl_pos_adj : -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
	beep_mode : N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N
	enable : Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y
	enable_msi : -1
	id : (null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null)
	index : -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
	jackpoll_ms : 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	model : (null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null)
	patch : (null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null)
	position_fix : -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
	power_save : 0
	power_save_controller : Y
	probe_mask : -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
	probe_only : 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	single_cmd : N
	snoop : -1


!!HDA-Intel Codec information
!!---------------------------
--startcollapse--

Codec: ATI R6xx HDMI
Address: 0
AFG Function Id: 0x1 (unsol 0)
Vendor Id: 0x1002aa01
Subsystem Id: 0x00aa0100
Revision Id: 0x100700
No Modem Function Group found
Default PCM:
    rates [0x70]: 32000 44100 48000
    bits [0x2]: 16
    formats [0x1]: PCM
Default Amp-In caps: N/A
Default Amp-Out caps: N/A
State of AFG node 0x01:
  Power states:  D0 D3 CLKSTOP EPSS
  Power: setting=D0, actual=D0, Clock-stop-OK
GPIO: io=0, o=0, i=0, unsolicited=0, wake=0
Node 0x02 [Audio Output] wcaps 0x221: Stereo Digital Stripe
  Converter: stream=1, channel=0
  Digital: Enabled
  Digital category: 0x0
  IEC Coding Type: 0x0
Node 0x03 [Pin Complex] wcaps 0x400381: Stereo Digital
  Control: name="IEC958 Playback Con Mask", index=0, device=0
  Control: name="IEC958 Playback Pro Mask", index=0, device=0
  Control: name="IEC958 Playback Default", index=0, device=0
  Control: name="IEC958 Playback Switch", index=0, device=0
  Pincap 0x00000094: OUT Detect HDMI
  Pin Default 0x185600f0: [Jack] Digital Out at Int HDMI
    Conn = Digital, Color = Unknown
    DefAssociation = 0xf, Sequence = 0x0
  Pin-ctls: 0x40: OUT
  Unsolicited: tag=01, enabled=1
  Connection: 1
     0x02
Node 0x04 [Audio Output] wcaps 0x221: Stereo Digital Stripe
  Converter: stream=0, channel=0
  Digital: Enabled
  Digital category: 0x0
  IEC Coding Type: 0x0
Node 0x05 [Pin Complex] wcaps 0x400381: Stereo Digital
  Control: name="IEC958 Playback Con Mask", index=1, device=0
  Control: name="IEC958 Playback Pro Mask", index=1, device=0
  Control: name="IEC958 Playback Default", index=1, device=0
  Control: name="IEC958 Playback Switch", index=1, device=0
  Pincap 0x00000094: OUT Detect HDMI
  Pin Default 0x185600f0: [Jack] Digital Out at Int HDMI
    Conn = Digital, Color = Unknown
    DefAssociation = 0xf, Sequence = 0x0
  Pin-ctls: 0x40: OUT
  Unsolicited: tag=02, enabled=1
  Connection: 1
     0x04
Node 0x06 [Audio Output] wcaps 0x221: Stereo Digital Stripe
  Converter: stream=0, channel=0
  Digital: Enabled
  Digital category: 0x0
  IEC Coding Type: 0x0
Node 0x07 [Pin Complex] wcaps 0x400381: Stereo Digital
  Control: name="IEC958 Playback Con Mask", index=2, device=0
  Control: name="IEC958 Playback Pro Mask", index=2, device=0
  Control: name="IEC958 Playback Default", index=2, device=0
  Control: name="IEC958 Playback Switch", index=2, device=0
  Pincap 0x00000094: OUT Detect HDMI
  Pin Default 0x185600f0: [Jack] Digital Out at Int HDMI
    Conn = Digital, Color = Unknown
    DefAssociation = 0xf, Sequence = 0x0
  Pin-ctls: 0x40: OUT
  Unsolicited: tag=03, enabled=1
  Connection: 1
     0x06
Node 0x08 [Audio Output] wcaps 0x221: Stereo Digital Stripe
  Converter: stream=0, channel=0
  Digital: Enabled
  Digital category: 0x0
  IEC Coding Type: 0x0
Node 0x09 [Pin Complex] wcaps 0x400381: Stereo Digital
  Control: name="IEC958 Playback Con Mask", index=3, device=0
  Control: name="IEC958 Playback Pro Mask", index=3, device=0
  Control: name="IEC958 Playback Default", index=3, device=0
  Control: name="IEC958 Playback Switch", index=3, device=0
  Pincap 0x00000094: OUT Detect HDMI
  Pin Default 0x185600f0: [Jack] Digital Out at Int HDMI
    Conn = Digital, Color = Unknown
    DefAssociation = 0xf, Sequence = 0x0
  Pin-ctls: 0x40: OUT
  Unsolicited: tag=04, enabled=1
  Connection: 1
     0x08
Node 0x0a [Audio Output] wcaps 0x221: Stereo Digital Stripe
  Converter: stream=0, channel=0
  Digital: Enabled
  Digital category: 0x0
  IEC Coding Type: 0x0
Node 0x0b [Pin Complex] wcaps 0x400381: Stereo Digital
  Control: name="IEC958 Playback Con Mask", index=4, device=0
  Control: name="IEC958 Playback Pro Mask", index=4, device=0
  Control: name="IEC958 Playback Default", index=4, device=0
  Control: name="IEC958 Playback Switch", index=4, device=0
  Pincap 0x00000094: OUT Detect HDMI
  Pin Default 0x185600f0: [Jack] Digital Out at Int HDMI
    Conn = Digital, Color = Unknown
    DefAssociation = 0xf, Sequence = 0x0
  Pin-ctls: 0x40: OUT
  Unsolicited: tag=05, enabled=1
  Connection: 1
     0x0a
Node 0x0c [Audio Output] wcaps 0x221: Stereo Digital Stripe
  Converter: stream=0, channel=0
  Digital: Enabled
  Digital category: 0x0
  IEC Coding Type: 0x0
Node 0x0d [Pin Complex] wcaps 0x400381: Stereo Digital
  Control: name="IEC958 Playback Con Mask", index=5, device=0
  Control: name="IEC958 Playback Pro Mask", index=5, device=0
  Control: name="IEC958 Playback Default", index=5, device=0
  Control: name="IEC958 Playback Switch", index=5, device=0
  Pincap 0x00000094: OUT Detect HDMI
  Pin Default 0x185600f0: [Jack] Digital Out at Int HDMI
    Conn = Digital, Color = Unknown
    DefAssociation = 0xf, Sequence = 0x0
  Pin-ctls: 0x40: OUT
  Unsolicited: tag=06, enabled=1
  Connection: 1
     0x0c
Node 0x0e [Audio Output] wcaps 0x221: Stereo Digital Stripe
  Converter: stream=0, channel=0
  Digital:
  Digital category: 0x0
  IEC Coding Type: 0x0
Node 0x0f [Pin Complex] wcaps 0x400381: Stereo Digital
  Pincap 0x00000094: OUT Detect HDMI
  Pin Default 0x585600f0: [N/A] Digital Out at Int HDMI
    Conn = Digital, Color = Unknown
    DefAssociation = 0xf, Sequence = 0x0
  Pin-ctls: 0x40: OUT
  Unsolicited: tag=00, enabled=0
  Connection: 1
     0x0e
--endcollapse--


!!ALSA Device nodes
!!-----------------

crw-rw----+ 1 root audio 116, 10 Dec  6 17:23 /dev/snd/controlC0
crw-rw----+ 1 root audio 116,  2 Dec  6 17:23 /dev/snd/controlC1
crw-rw----+ 1 root audio 116,  9 Dec  6 17:23 /dev/snd/hwC1D0
crw-rw----+ 1 root audio 116, 12 Dec  6 17:25 /dev/snd/pcmC0D0c
crw-rw----+ 1 root audio 116, 11 Dec  6 17:42 /dev/snd/pcmC0D0p
crw-rw----+ 1 root audio 116, 14 Dec  6 17:25 /dev/snd/pcmC0D1c
crw-rw----+ 1 root audio 116, 13 Dec  6 17:25 /dev/snd/pcmC0D1p
crw-rw----+ 1 root audio 116,  7 Dec  6 17:25 /dev/snd/pcmC1D10p
crw-rw----+ 1 root audio 116,  8 Dec  6 17:25 /dev/snd/pcmC1D11p
crw-rw----+ 1 root audio 116,  3 Dec  6 17:25 /dev/snd/pcmC1D3p
crw-rw----+ 1 root audio 116,  4 Dec  6 17:25 /dev/snd/pcmC1D7p
crw-rw----+ 1 root audio 116,  5 Dec  6 17:25 /dev/snd/pcmC1D8p
crw-rw----+ 1 root audio 116,  6 Dec  6 17:25 /dev/snd/pcmC1D9p
crw-rw----+ 1 root audio 116,  1 Dec  6 17:23 /dev/snd/seq
crw-rw----+ 1 root audio 116, 33 Dec  6 17:23 /dev/snd/timer

/dev/snd/by-path:
total 0
drwxr-xr-x. 2 root root  80 Dec  6 17:23 .
drwxr-xr-x. 3 root root 360 Dec  6 17:23 ..
lrwxrwxrwx. 1 root root  12 Dec  6 17:23 pci-0000:01:00.1 -> ../controlC1
lrwxrwxrwx. 1 root root  12 Dec  6 17:23 pci-0000:08:06.0 -> ../controlC0


!!ALSA configuration files
!!------------------------

!!System wide config file (/etc/asound.conf)


 Place your global alsa-lib configuration here...



!!Aplay/Arecord output
!!--------------------

APLAY

**** List of PLAYBACK Hardware Devices ****
card 0: ST [Xonar ST], device 0: Multichannel [Multichannel]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: ST [Xonar ST], device 1: Digital [Digital]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA ATI HDMI], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA ATI HDMI], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA ATI HDMI], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA ATI HDMI], device 9: HDMI 3 [HDMI 3]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA ATI HDMI], device 10: HDMI 4 [HDMI 4]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA ATI HDMI], device 11: HDMI 5 [HDMI 5]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

ARECORD

**** List of CAPTURE Hardware Devices ****
card 0: ST [Xonar ST], device 0: Multichannel [Multichannel]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: ST [Xonar ST], device 1: Digital [Digital]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

!!Amixer output
!!-------------

!!-------Mixer controls for card 0 [ST]

Card hw:0 'ST'/'Asus Virtuoso 100 at 0x7e00, irq 20'
  Mixer name	: 'AV200'
  Components	: 'PCM1792A CS5381 CS2000 AV200'
  Controls      : 23
  Simple ctrls  : 13
Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 135 - 255
  Mono:
  Front Left: Playback 214 [66%] [-20.50dB] [on]
  Front Right: Playback 214 [66%] [-20.50dB] [on]
Simple mixer control 'Headphones Impedance',0
  Capabilities: penum
  Items: '< 32 ohms' '32-64 ohms' '64-300 ohms' '300-600 ohms'
  Item0: '< 32 ohms'
Simple mixer control 'Line',0
  Capabilities: cswitch cswitch-joined
  Capture channels: Mono
  Mono: Capture [on]
Simple mixer control 'Mic',0
  Capabilities: cvolume cvolume-joined cswitch cswitch-joined
  Capture channels: Mono
  Limits: Capture 0 - 31
  Mono: Capture 0 [0%] [-34.50dB] [off]
Simple mixer control 'Mic Boost (+20dB)',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [off]
Simple mixer control 'Mic Source',0
  Capabilities: cenum
  Items: 'Mic Jack' 'Front Panel'
  Item0: 'Mic Jack'
Simple mixer control 'IEC958',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [off]
Simple mixer control 'IEC958 Loopback',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [off]
Simple mixer control 'IEC958 Validity Check',0
  Capabilities: cswitch cswitch-joined
  Capture channels: Mono
  Mono: Capture [off]
Simple mixer control 'Aux',0
  Capabilities: cvolume cswitch cswitch-joined
  Capture channels: Front Left - Front Right
  Limits: Capture 0 - 31
  Front Left: Capture 0 [0%] [-34.50dB] [off]
  Front Right: Capture 0 [0%] [-34.50dB] [off]
Simple mixer control 'Analog Input Monitor',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback 0 - 1
  Mono: Playback 1 [100%] [0.00dB] [off]
Simple mixer control 'Analog Output',0
  Capabilities: enum
  Items: 'Speakers' 'Headphones' 'FP Headphones'
  Item0: 'Speakers'
Simple mixer control 'Digital Input Monitor',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback 0 - 1
  Mono: Playback 1 [100%] [0.00dB] [off]

!!-------Mixer controls for card 1 [HDMI]

Card hw:1 'HDMI'/'HDA ATI HDMI at 0xfd9fc000 irq 33'
  Mixer name	: 'ATI R6xx HDMI'
  Components	: 'HDA:1002aa01,00aa0100,00100700'
  Controls      : 42
  Simple ctrls  : 6
Simple mixer control 'IEC958',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'IEC958',1
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'IEC958',2
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'IEC958',3
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'IEC958',4
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'IEC958',5
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]


!!Alsactl output
!!--------------

--startcollapse--
state.ST {
	control.1 {
		iface MIXER
		name 'Master Playback Volume'
		value.0 214
		value.1 214
		comment {
			access 'read write'
			type INTEGER
			count 2
			range '135 - 255'
			dbmin -6000
			dbmax 0
			dbvalue.0 -2050
			dbvalue.1 -2050
		}
	}
	control.2 {
		iface MIXER
		name 'Master Playback Switch'
		value true
		comment {
			access 'read write'
			type BOOLEAN
			count 1
		}
	}
	control.3 {
		iface MIXER
		name 'IEC958 Playback Switch'
		value false
		comment {
			access 'read write'
			type BOOLEAN
			count 1
		}
	}
	control.4 {
		iface PCM
		device 1
		name 'IEC958 Playback Default'
		value '0482000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
		comment {
			access 'read write'
			type IEC958
			count 1
		}
	}
	control.5 {
		iface PCM
		device 1
		name 'IEC958 Playback Con Mask'
		value '3eff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
		comment {
			access read
			type IEC958
			count 1
		}
	}
	control.6 {
		iface PCM
		device 1
		name 'IEC958 Playback PCM Stream'
		value '0482000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
		comment {
			access 'read write inactive'
			type IEC958
			count 1
		}
	}
	control.7 {
		iface PCM
		device 1
		name 'IEC958 Capture Mask'
		value ffffffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
		comment {
			access read
			type IEC958
			count 1
		}
	}
	control.8 {
		iface PCM
		device 1
		name 'IEC958 Capture Default'
		value '0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
		comment {
			access read
			type IEC958
			count 1
		}
	}
	control.9 {
		iface MIXER
		name 'IEC958 Loopback Switch'
		value false
		comment {
			access 'read write'
			type BOOLEAN
			count 1
		}
	}
	control.10 {
		iface MIXER
		name 'IEC958 Validity Check Capture Switch'
		value false
		comment {
			access 'read write'
			type BOOLEAN
			count 1
		}
	}
	control.11 {
		iface MIXER
		name 'Analog Input Monitor Playback Switch'
		value false
		comment {
			access 'read write'
			type BOOLEAN
			count 1
		}
	}
	control.12 {
		iface MIXER
		name 'Analog Input Monitor Playback Volume'
		value 1
		comment {
			access 'read write'
			type INTEGER
			count 1
			range '0 - 1'
			dbmin -600
			dbmax 0
			dbvalue.0 0
		}
	}
	control.13 {
		iface MIXER
		name 'Digital Input Monitor Playback Switch'
		value false
		comment {
			access 'read write'
			type BOOLEAN
			count 1
		}
	}
	control.14 {
		iface MIXER
		name 'Digital Input Monitor Playback Volume'
		value 1
		comment {
			access 'read write'
			type INTEGER
			count 1
			range '0 - 1'
			dbmin -600
			dbmax 0
			dbvalue.0 0
		}
	}
	control.15 {
		iface MIXER
		name 'Mic Capture Volume'
		value 0
		comment {
			access 'read write'
			type INTEGER
			count 1
			range '0 - 31'
			dbmin -3450
			dbmax 1200
			dbvalue.0 -3450
		}
	}
	control.16 {
		iface MIXER
		name 'Mic Capture Switch'
		value false
		comment {
			access 'read write'
			type BOOLEAN
			count 1
		}
	}
	control.17 {
		iface MIXER
		name 'Mic Boost (+20dB)'
		value false
		comment {
			access 'read write'
			type BOOLEAN
			count 1
		}
	}
	control.18 {
		iface MIXER
		name 'Mic Source Capture Enum'
		value 'Mic Jack'
		comment {
			access 'read write'
			type ENUMERATED
			count 1
			item.0 'Mic Jack'
			item.1 'Front Panel'
		}
	}
	control.19 {
		iface MIXER
		name 'Line Capture Switch'
		value true
		comment {
			access 'read write'
			type BOOLEAN
			count 1
		}
	}
	control.20 {
		iface MIXER
		name 'Aux Capture Volume'
		value.0 0
		value.1 0
		comment {
			access 'read write'
			type INTEGER
			count 2
			range '0 - 31'
			dbmin -3450
			dbmax 1200
			dbvalue.0 -3450
			dbvalue.1 -3450
		}
	}
	control.21 {
		iface MIXER
		name 'Aux Capture Switch'
		value false
		comment {
			access 'read write'
			type BOOLEAN
			count 1
		}
	}
	control.22 {
		iface MIXER
		name 'Analog Output'
		value Speakers
		comment {
			access 'read write'
			type ENUMERATED
			count 1
			item.0 Speakers
			item.1 Headphones
			item.2 'FP Headphones'
		}
	}
	control.23 {
		iface MIXER
		name 'Headphones Impedance Playback Enum'
		value '< 32 ohms'
		comment {
			access 'read write'
			type ENUMERATED
			count 1
			item.0 '< 32 ohms'
			item.1 '32-64 ohms'
			item.2 '64-300 ohms'
			item.3 '300-600 ohms'
		}
	}
}
state.HDMI {
	control.1 {
		iface CARD
		name 'HDMI/DP,pcm=3 Jack'
		value false
		comment {
			access read
			type BOOLEAN
			count 1
		}
	}
	control.2 {
		iface MIXER
		name 'IEC958 Playback Con Mask'
		value '0fff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
		comment {
			access read
			type IEC958
			count 1
		}
	}
	control.3 {
		iface MIXER
		name 'IEC958 Playback Pro Mask'
		value '0f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
		comment {
			access read
			type IEC958
			count 1
		}
	}
	control.4 {
		iface MIXER
		name 'IEC958 Playback Default'
		value '0400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
		comment {
			access 'read write'
			type IEC958
			count 1
		}
	}
	control.5 {
		iface MIXER
		name 'IEC958 Playback Switch'
		value true
		comment {
			access 'read write'
			type BOOLEAN
			count 1
		}
	}
	control.6 {
		iface PCM
		device 3
		name ELD
		value ''
		comment {
			access 'read volatile'
			type BYTES
			count 0
		}
	}
	control.7 {
		iface CARD
		name 'HDMI/DP,pcm=7 Jack'
		value false
		comment {
			access read
			type BOOLEAN
			count 1
		}
	}
	control.8 {
		iface MIXER
		name 'IEC958 Playback Con Mask'
		index 1
		value '0fff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
		comment {
			access read
			type IEC958
			count 1
		}
	}
	control.9 {
		iface MIXER
		name 'IEC958 Playback Pro Mask'
		index 1
		value '0f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
		comment {
			access read
			type IEC958
			count 1
		}
	}
	control.10 {
		iface MIXER
		name 'IEC958 Playback Default'
		index 1
		value '0400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
		comment {
			access 'read write'
			type IEC958
			count 1
		}
	}
	control.11 {
		iface MIXER
		name 'IEC958 Playback Switch'
		index 1
		value true
		comment {
			access 'read write'
			type BOOLEAN
			count 1
		}
	}
	control.12 {
		iface PCM
		device 7
		name ELD
		value ''
		comment {
			access 'read volatile'
			type BYTES
			count 0
		}
	}
	control.13 {
		iface CARD
		name 'HDMI/DP,pcm=8 Jack'
		value false
		comment {
			access read
			type BOOLEAN
			count 1
		}
	}
	control.14 {
		iface MIXER
		name 'IEC958 Playback Con Mask'
		index 2
		value '0fff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
		comment {
			access read
			type IEC958
			count 1
		}
	}
	control.15 {
		iface MIXER
		name 'IEC958 Playback Pro Mask'
		index 2
		value '0f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
		comment {
			access read
			type IEC958
			count 1
		}
	}
	control.16 {
		iface MIXER
		name 'IEC958 Playback Default'
		index 2
		value '0400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
		comment {
			access 'read write'
			type IEC958
			count 1
		}
	}
	control.17 {
		iface MIXER
		name 'IEC958 Playback Switch'
		index 2
		value true
		comment {
			access 'read write'
			type BOOLEAN
			count 1
		}
	}
	control.18 {
		iface PCM
		device 8
		name ELD
		value ''
		comment {
			access 'read volatile'
			type BYTES
			count 0
		}
	}
	control.19 {
		iface CARD
		name 'HDMI/DP,pcm=9 Jack'
		value false
		comment {
			access read
			type BOOLEAN
			count 1
		}
	}
	control.20 {
		iface MIXER
		name 'IEC958 Playback Con Mask'
		index 3
		value '0fff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
		comment {
			access read
			type IEC958
			count 1
		}
	}
	control.21 {
		iface MIXER
		name 'IEC958 Playback Pro Mask'
		index 3
		value '0f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
		comment {
			access read
			type IEC958
			count 1
		}
	}
	control.22 {
		iface MIXER
		name 'IEC958 Playback Default'
		index 3
		value '0400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
		comment {
			access 'read write'
			type IEC958
			count 1
		}
	}
	control.23 {
		iface MIXER
		name 'IEC958 Playback Switch'
		index 3
		value true
		comment {
			access 'read write'
			type BOOLEAN
			count 1
		}
	}
	control.24 {
		iface PCM
		device 9
		name ELD
		value ''
		comment {
			access 'read volatile'
			type BYTES
			count 0
		}
	}
	control.25 {
		iface CARD
		name 'HDMI/DP,pcm=10 Jack'
		value false
		comment {
			access read
			type BOOLEAN
			count 1
		}
	}
	control.26 {
		iface MIXER
		name 'IEC958 Playback Con Mask'
		index 4
		value '0fff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
		comment {
			access read
			type IEC958
			count 1
		}
	}
	control.27 {
		iface MIXER
		name 'IEC958 Playback Pro Mask'
		index 4
		value '0f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
		comment {
			access read
			type IEC958
			count 1
		}
	}
	control.28 {
		iface MIXER
		name 'IEC958 Playback Default'
		index 4
		value '0400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
		comment {
			access 'read write'
			type IEC958
			count 1
		}
	}
	control.29 {
		iface MIXER
		name 'IEC958 Playback Switch'
		index 4
		value true
		comment {
			access 'read write'
			type BOOLEAN
			count 1
		}
	}
	control.30 {
		iface PCM
		device 10
		name ELD
		value ''
		comment {
			access 'read volatile'
			type BYTES
			count 0
		}
	}
	control.31 {
		iface CARD
		name 'HDMI/DP,pcm=11 Jack'
		value false
		comment {
			access read
			type BOOLEAN
			count 1
		}
	}
	control.32 {
		iface MIXER
		name 'IEC958 Playback Con Mask'
		index 5
		value '0fff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
		comment {
			access read
			type IEC958
			count 1
		}
	}
	control.33 {
		iface MIXER
		name 'IEC958 Playback Pro Mask'
		index 5
		value '0f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
		comment {
			access read
			type IEC958
			count 1
		}
	}
	control.34 {
		iface MIXER
		name 'IEC958 Playback Default'
		index 5
		value '0400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
		comment {
			access 'read write'
			type IEC958
			count 1
		}
	}
	control.35 {
		iface MIXER
		name 'IEC958 Playback Switch'
		index 5
		value true
		comment {
			access 'read write'
			type BOOLEAN
			count 1
		}
	}
	control.36 {
		iface PCM
		device 11
		name ELD
		value ''
		comment {
			access 'read volatile'
			type BYTES
			count 0
		}
	}
	control.37 {
		iface PCM
		device 3
		name 'Playback Channel Map'
		value.0 0
		value.1 0
		value.2 0
		value.3 0
		value.4 0
		value.5 0
		value.6 0
		value.7 0
		comment {
			access 'read write'
			type INTEGER
			count 8
			range '0 - 36'
		}
	}
	control.38 {
		iface PCM
		device 7
		name 'Playback Channel Map'
		value.0 0
		value.1 0
		value.2 0
		value.3 0
		value.4 0
		value.5 0
		value.6 0
		value.7 0
		comment {
			access 'read write'
			type INTEGER
			count 8
			range '0 - 36'
		}
	}
	control.39 {
		iface PCM
		device 8
		name 'Playback Channel Map'
		value.0 0
		value.1 0
		value.2 0
		value.3 0
		value.4 0
		value.5 0
		value.6 0
		value.7 0
		comment {
			access 'read write'
			type INTEGER
			count 8
			range '0 - 36'
		}
	}
	control.40 {
		iface PCM
		device 9
		name 'Playback Channel Map'
		value.0 0
		value.1 0
		value.2 0
		value.3 0
		value.4 0
		value.5 0
		value.6 0
		value.7 0
		comment {
			access 'read write'
			type INTEGER
			count 8
			range '0 - 36'
		}
	}
	control.41 {
		iface PCM
		device 10
		name 'Playback Channel Map'
		value.0 0
		value.1 0
		value.2 0
		value.3 0
		value.4 0
		value.5 0
		value.6 0
		value.7 0
		comment {
			access 'read write'
			type INTEGER
			count 8
			range '0 - 36'
		}
	}
	control.42 {
		iface PCM
		device 11
		name 'Playback Channel Map'
		value.0 0
		value.1 0
		value.2 0
		value.3 0
		value.4 0
		value.5 0
		value.6 0
		value.7 0
		comment {
			access 'read write'
			type INTEGER
			count 8
			range '0 - 36'
		}
	}
}
--endcollapse--


!!All Loaded Modules
!!------------------

Module
uas
usb_storage
xt_CHECKSUM
ipt_MASQUERADE
nf_nat_masquerade_ipv4
tun
ip6t_rpfilter
ip6t_REJECT
nf_reject_ipv6
xt_conntrack
ip_set
nfnetlink
ebtable_broute
bridge
stp
llc
ebtable_nat
ip6table_nat
nf_conntrack_ipv6
nf_defrag_ipv6
nf_nat_ipv6
ip6table_mangle
ip6table_raw
ip6table_security
iptable_nat
nf_conntrack_ipv4
nf_defrag_ipv4
nf_nat_ipv4
nf_nat
iptable_mangle
iptable_raw
iptable_security
ebtable_filter
ebtables
ip6table_filter
ip6_tables
joydev
snd_hda_codec_hdmi
snd_hda_intel
snd_virtuoso
kvm_amd
snd_hda_codec
snd_oxygen_lib
snd_hda_core
kvm
snd_hwdep
snd_mpu401_uart
snd_rawmidi
snd_seq
snd_seq_device
ppdev
snd_pcm
irqbypass
k10temp
snd_timer
snd
soundcore
wmi
parport_pc
parport
shpchp
sp5100_tco
i2c_piix4
acpi_cpufreq
tpm_tis
tpm_tis_core
tpm
binfmt_misc
amdkfd
amd_iommu_v2
amdgpu
i2c_algo_bit
firewire_ohci
drm_kms_helper
serio_raw
ttm
firewire_core
ata_generic
pata_acpi
crc_itu_t
drm
r8169
pata_jmicron
mii
fjes
nf_conntrack_pptp
nf_conntrack_proto_gre
nf_conntrack


!!Sysfs Files
!!-----------

/sys/class/sound/hwC1D0/init_pin_configs:
0x03 0x185600f0
0x05 0x185600f0
0x07 0x185600f0
0x09 0x185600f0
0x0b 0x185600f0
0x0d 0x185600f0
0x0f 0x585600f0

/sys/class/sound/hwC1D0/driver_pin_configs:

/sys/class/sound/hwC1D0/user_pin_configs:

/sys/class/sound/hwC1D0/init_verbs:

/sys/class/sound/hwC1D0/hints:


!!ALSA/HDA dmesg
!!--------------

[    1.904555] [drm] Connector 3:
[    1.904555] [drm]   HDMI-A-1
[    1.904555] [drm]   HPD5
--
[   16.497842] kvm: Nested Paging enabled
[   16.527675] snd_hda_intel 0000:01:00.1: Handle vga_switcheroo audio client
[   16.527682] snd_hda_intel 0000:01:00.1: Force to non-snoop mode
[   16.561055] audit_printk_skb: 33 callbacks suppressed
[   16.561066] audit: type=1130 audit(1481041428.485:66): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-fsck@dev-disk-by\x2duuid-*removed_for_privacy* comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   16.801507] input: HDA ATI HDMI HDMI/DP,pcm=3 as /devices/pci0000:00/0000:00:02.0/0000:01:00.1/sound/card1/input8
[   16.801761] input: HDA ATI HDMI HDMI/DP,pcm=7 as /devices/pci0000:00/0000:00:02.0/0000:01:00.1/sound/card1/input9
[   16.801938] input: HDA ATI HDMI HDMI/DP,pcm=8 as /devices/pci0000:00/0000:00:02.0/0000:01:00.1/sound/card1/input10
[   16.802127] input: HDA ATI HDMI HDMI/DP,pcm=9 as /devices/pci0000:00/0000:00:02.0/0000:01:00.1/sound/card1/input11
[   16.802299] input: HDA ATI HDMI HDMI/DP,pcm=10 as /devices/pci0000:00/0000:00:02.0/0000:01:00.1/sound/card1/input12
[   16.802771] input: HDA ATI HDMI HDMI/DP,pcm=11 as /devices/pci0000:00/0000:00:02.0/0000:01:00.1/sound/card1/input13
[   16.922014] EXT4-fs (sdd1): mounted filesystem with ordered data mode. Opts: (null)



```

**Comment by Tele42** [comment]
Hello @Germano0, please copy the majority of your last comment into a gist and link it in the comment instead of having a large spam post.

**Comment by Germano0** [comment]
@Tele42 done

**Comment by Germano0** [comment]
Downstream bugreport https://bugzilla.rpmfusion.org/show_bug.cgi?id=4372

**Comment by Germano0** [comment]
This sounds crazy: I killed pulseaudio with
$ pulseaudio -k
(the autospawn was already been disabled), then runned
$ pulseaudio -vvvvv
and the problem suddendly disappeared. I attach the pulseaudio log at https://bugzilla.rpmfusion.org/attachment.cgi?id=1701
Tomorrow I will test if the problem is still reproducible

**Comment by kisak-valve** [comment]
Hello @MaxPayneFH, are you still experiencing this this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
