### ISSUE TITLE
Steam gives me errors about pgrep and refuses to start

### ISSUE THREAD

**Issue by JoshuaMurphynz** [ValveSoftware/steam-for-linux#4548]
#### Your system information
- Steam client version:
- Distribution: Ubuntu 14.04 LTS
- Opted into Steam client beta?: Yes
- Have you checked for system updates?: Yes
#### Please describe your issue in as much detail as possible:

Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

All I did was get a new update, apply it, and now my steam is completely broken.

https://gist.github.com/not83/239013eda40577f1248b28dc63a1ca11
#### Steps for reproducing this issue:
1. Start Steam
2. See you are logging in
3. Steam crashes

**Comment by not83** [comment]
FIXED: No idea why AT ALL. But Steam for some reason now works.


https://gist.github.com/not83/043ac2b639d0c3536787c829be129989

No idea at all

**Comment by not83** [comment]
NEVERMIND: Now it is NOT working. The client loads then crashes: https://gist.github.com/not83/d08c9ff11418625cbd414319aa9d47de

**Comment by Storm-Engineer** [comment]
Not sure if same issue, but Steam worked yesterday, then after updating itself it stopped to work. I did a system upgrade to see if that fixes but no.

Dumps:
https://www.dropbox.com/sh/hqu2f06b8pirant/AADEtPRyR1H5uaqO73k42obPa?dl=0

How do I start a game that is supposed to run without Steam and does so on Windows? They tell me go to game folder in Steam and just run it - that works on Windows but on Linux it will cry about not finding all kinds of dirs. This game should run without Steam, and I want to play! Please help!

**Comment by Storm-Engineer** [comment]
I just tried now and Steam started up, it seemed to work... then while I came here to report that it crashed, and now won't start again. So the issue persists, but it's weird that at first it started up. Here is the dump for that crash: https://www.dropbox.com/s/hd8v7xw5wgf2hi7/crash_20160721032114_1.dmp?dl=0

**Comment by Storm-Engineer** [comment]
Apparently my issue was #4561 - an issue caused with beta participations no longer existing.

**Comment by kisak-valve** [comment]
Hello @JoshuaMurphynz, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
