### ISSUE TITLE
Adding a non-steam game adds a broken link to a different game altogether - ? error parsing spaces in .desktop file paths

### ISSUE THREAD

**Issue by mcphail** [ValveSoftware/steam-for-linux#5220]
#### Your system information
```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD A4-7300 APU with Radeon HD Graphics        
    CPU Family:  0x15
    CPU Model:  0x13
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3800 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 16.04.3 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.4.0-97-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11804000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-beta-release_2017-07-24

Video Card:
    Driver:  NVIDIA Corporation GeForce GT 430/PCIe/SSE2
    Driver Version:  4.5.0 NVIDIA 381.22
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0xde1
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1280 x 1024
    Desktop Resolution: 1280 x 1024
    Primary Display Size: 13.31" x 10.63" (17.01" diag)
                                            33.8cm x 27.0cm (43.2cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC887-VD

Memory:
    RAM:  7990 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.UTF-8
    Total Hard Disk Space Available:  928692 Mb
    Largest Free Hard Disk Block:  385423 Mb
    VR Headset: None detected

Recent Failure Reports:

```

#### Please describe your issue in as much detail as possible:

I cannot add some non-steam games to my library. Please see the [video showing a failure to add the GOG version of Baldur's Gate Enhanced Edition](https://ovh.themcphails.uk/index.php/s/WpzGB9SS5UW95LN), which demonstrates the problem thus:

I have a working .desktop file for the GOG version of Baldur's Gate Enhanced Edition under `$HOME/.local/share/applications` which can be used to launch the game normally from the Unity dash. I try to add the game to steam, but it does not show up in the list of applications. Note there is an "Icewind Dale Enhanced Edition" option (another one of my GOG games) detected automatically with an incorrect launch path (pointing to `$HOME` rather than `$HOME/GOG Games/Ice...`).

I try to browse for the Baldur's Gate .desktop file manually. I locate and select it, but instead I get a selection for Icewind Dale (again, with the dodgy path). If I add this file, I get a broken launcher which does not launch either game. The Target is set to `""$HOME/GOG"` (which is not a valid path, and suggests the space in the path has not been parsed correctly) and Start In is set to `""$HOME"`.

I think steam is not parsing the desktop files correctly, so certain games do not show up automatically in the selection dialog and trying to add these games manually results in broken links being created.

**Comment by Lyle-Tafoya** [comment]
I am able to confirm this issue. Despite having no problems when launching my desktop files from krunner, Steam fails to launch applications added with Exec lines such as the following:

    Exec=env SteamGameId=233610 SteamAppId=233610 STEAM_COMPAT_DATA_PATH="/home/username/.local/share/proton_tools/compatdata/233610" "/home/username/.local/share/Steam/steamapps/common/Proton 3.16 Beta/proton" run /home/username/.local/share/proton_tools/common/Distance/Distance.exe

As a workaround, I have found it necessary to create launcher scripts and have the desktop file exec the launcher script. This is not a perfect workaround. I recommend that the following specification be referenced: https://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables

**Comment by RickRNF** [comment]
Here's a little more information. 
Everything after the space in a path gets sent to "SET LAUNCH OPTIONS"
Workaround: Remove "SET LAUNCH OPTIONS" and manually finish the path in "Target:" will fix the issue

#### Please describe your issue in as much detail as possible:
Folder names with spaces cause issues when adding Non-Steam games.

If you add a Non-Steam game with a space in the path, Steam will cut off the "Target:" before the space and place the rest of the path within the "SET LAUNCH OPTIONS"

Manually fixing the "Target:" and removing the "SET LAUNCH OPTIONS" will fix the issue

#### Steps for reproducing this issue:

1. Add Non-Steam game to library with path containing space(s) 
    (example: /data/game folder/game.exe)
2. "Target:" becomes "/data/game"
3. "SET LAUNCH OPTIONS" becomes "folder/game.exe"
4. Launching game from library does nothing

**Comment by MobiusTesseract** [comment]
Confirming this. Additionally, setting the target again using the "Change..." button in the properties, sets it correctly even if it contains spaces so no need to type it manually. This also shows there is code to handle this properly already in the client, can be re-used.

**Comment by jarrard** [comment]
Yes this is the same issue as the one I mentioned [1]. 

The second issue similar to this is related to the set launch options function itself ignoring %command% placement.

**Comment by dreamer** [comment]
(commenting to keep track of this bug)

To Valve developers: this bug seems to be really "low-hanging fruit", most likely broken quoting or path splitting, I wouldn't be surprised if this was a bug on Windows or OSX as well.

I managed to hit this issue (on Linux) while pointing directly to .exe file inside `~/.wine`. Every single game from GOG will be affected.

**Comment by ThatAnnoyedGuy** [comment]
This is a very annoying issue and it shouldn't take much to resolve this. Why has this not been looked at yet, in years?

**Comment by jarrard** [comment]
yes its just a steam gui interface issue, not sure if its present under windows client. no idea why valve ignores this issue.

**Comment by MobiusTesseract** [comment]
It is not present under Windows, works fine there. It's not even present in the "Change" button routine in the Linux version. It baffles me too why this has not been fixed yet, it's so easy to correct.

**Comment by patrickm32** [comment]
I hate to bother with this, but three years after the first bug report the problem still persists. As far as I can tell the problem should be quite easy to solve, if not by a few lines of code.

**Comment by jarrard** [comment]
Yes it still exists, you can work around it by going into the added non-steam games Properties and re-select the exe again and adjust the launch options, be aware however when you change the NAME or LINKED exe it makes a entirely new shortcut and you need to close the properties down and look for that new shortcut and go over it again.

Its not intuitive so lots of people are likely unable to use this steam feature thinking its completely broken, however its only semi-broken if you follow the steps I said above. 

Yes it is annoying to have to do this.

**Comment by VictorKruger** [comment]
I'm adding to the pile of people to this ticket. It is very annoying that this bug was initially discovered in 2017 and yet it's not even at least assigned for someone to look at.

The most annoying part is not the code unproperly parsing the string, it's the fact that after EVERY CHANGE you need to close out or everything after your first change drops.

**Comment by lucifertdark** [comment]
It's not happening for all non-steam games that I add, only the ones with spaces in the name or path.

**Comment by jarrard** [comment]
I wonder if the community can patch this bug themselves? like do we have access to look at that portion of steam code?   I don't believe this is a issue under windows is it?

**Comment by patrickm32** [comment]
Probably not, since the Steam client is not open source (and I doubt they will simply release snippets of code). However, I can't imagine that it's that difficult to fix this bug, especially for experienced developers at Valve.

Seems like all we can do is hope the problem is fixed soon. In the meantime, I will probably continue to use Lutris (which is probably better for the task anyway).

**Comment by eode** [comment]
This is occurring with "among us" installed on Linux from Steam.

**Comment by DeathTBO** [comment]
Still present on the latest client/beta client. Using Fedora 33.

This is a major headache, especially since Proton is so useful.

**Comment by eode** [comment]
omg this is literally just a quoting issue, and still isn't done.   Steam..
..uh..  ..get it together.

**Comment by xard-dev** [comment]
I can confirm that this issue still present in Dec 16 2021 steam client release: When trying yo add external programs (which can be used for proton as well) from paths with spaces the path is split to properties to *TARGET* and *START IN* fields from the first space the parser faces.

**Comment by kisak-valve** [comment]
Hello, per "Fixed adding non-Steam shortcuts with spaces in the path" in the [2022-03-31](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3189118991320514548) Steam client beta update, please opt into Steam's beta client and retest this issue.

**Comment by moll** [comment]
I can confirm that the Mar 31, 2022 23:11:43 build indeed finally correctly added a shortcut an executable with spaces in its path.

Btw, might want to make the "About Steam" page contain copyable text. I could've copied the date and package versions then. ;)

**Comment by xard-dev** [comment]
> Hello, per "Fixed adding non-Steam shortcuts with spaces in the path" in the [2022-03-31](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3189118991320514548) Steam client beta update, please opt into Steam's beta client and retest this issue.

Hello,

I tested following beta version:
```
Mar 31 2022, at 23:11:43
Steam API: v020
Steam package versions: 1648789923
```

I confirm that it worked with following test case:
```
/home/share/programs/win32/Folder Name With Spaces/Double  Spaces/UTF-8 テストケース  ÿ Földer/test program.exe
```

1. There can be more than one folders with spaces
2. There can be other UTF-8 characters
3. The executable name can have spaces
4. The file picker set correct **TARGET** and **START IN** for the executable
5. The executable ran as expected

![image](https://user-images.githubusercontent.com/65303522/161427366-5055244a-2544-41ae-bed1-7dc12dc73d70.png)

**Comment by kisak-valve** [comment]
Thanks for retesting. Closing as fixed in the [2022-05-12](https://store.steampowered.com/oldnews/138198) Steam client update.

**Comment by eode** [comment]
Thank you!
