### ISSUE TITLE
Linux Steam Beta 2x scaling: window resizing and placement broken/misbehaving

### ISSUE THREAD

**Issue by DerRidda** [ValveSoftware/steam-for-linux#5354]
#### Your system information

* Steam client version (build number or date): Jan 25 2018, at 21:25;:7
* Distribution (e.g. Ubuntu): Solus
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Using the newest Steam beta on Solus with Budgie in the new 2x scale mode (implicit and explicit with the envar) on 4K dual monitors the resizing behavior is now almost entirely broken, it only works on some starts of Steam, most of the time it just refuses to retain the new size and instantly snaps back to its old size.

The few times it does work it can usually be broken by dragging the window, which itself is also broken that quite often the window will not stay in its new position and also snap back to where it started from.

When that happens it's usually over for resizing as well.

Once its in that bad state it will not recover and has to be restarted, which still isn't guaranteed to work.

Starting Steam with GDK_SCALE=1 always behaves nicely.

#### Steps for reproducing this issue:

Try to mimic my setup and see what happens...

#### System information ####

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 7 1800X Eight-Core Processor         
    CPU Family:  0x17
    CPU Model:  0x1
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3600 Mhz
    16 logical processors
    8 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Solus" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.14.14-47.current
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11905000
    X Window Manager:  Mutter(Budgie)
    Steam Runtime Version:  steam-runtime-beta-release_2017-10-05

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 1080 Ti/PCIe/SSE2
    Driver Version:  4.5.0 NVIDIA 384.111
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x1b06
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  3840 x 2160
    Desktop Resolution: 7680 x 2160
    Primary Display Size: 23,90" x 13,58" (27,48" diag)
                                            60,7cm x 34,5cm (69,8cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 11264 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Nvidia GPU 82 HDMI/DP

Memory:
    RAM:  32168 Mb

Miscellaneous:
    UI Language:  English
    LANG:  de_DE.UTF-8
    Total Hard Disk Space Available:  1923705 Mb
    Largest Free Hard Disk Block:  1299160 Mb
    VR Headset: HTC Vive detected

Recent Failure Reports:
```

**Comment by ernstp** [comment]
Same here on Ubuntu 17.10 with dual 4K monitors.

**Comment by dgutov** [comment]
Same here, for resizing and moving the main or, say, the Settings window.

Ubuntu 17.04, one 4K display (the laptop's screen).

**Comment by jmgomezpoveda** [comment]
As I mentioned on the other bug, under Cinnamon there seems to be no problem here (XPS 9530, 3200x1800) with resizing the window, but when trying to change its position goes back to nearly where it was before. The window looks fine when maximized.

**Comment by LubosD** [comment]
I'm having the same problem, but with a very large UHD screen:

Primary Display Resolution: 3840 x 2160
Desktop Resolution: 3840 x 2160
Primary Display Size: 34.57" x 19.09" (39.49" diag)
87.8cm x 48.5cm (100.3cm)

The whole UI is just super large. I don't understand why I should be getting 2x scaling if my display has a standard (low) DPI.

**Comment by DerRidda** [comment]
@LubosD This issue isn't about 2x scaling mode being enabled on a normal DPI system but rather erroneous behavior when resizing or moving Steam's windows in HiDPI mode.

The other issue you created is the better place for that.

**Comment by Mirarkitty** [comment]
Haven't started steam in a while, starting it today I was happy to see the 2x mode but the window __literally__ moved away (slowly, over half a minute) to the bottom right away from the screen area. I'm fascinated.

**Comment by ekaris** [comment]
I have the same problem after the update was pushed to the stable channel!

**Comment by DerRidda** [comment]
I also have no idea why this wasn't addressed at all after multiple people on different configurations confirmed the same behavior.

**Comment by adomas187** [comment]
Same issue here. Problems resizing windows. For example Friends window got huge and I am unable to make it smaller. Now it covers most of my screen, while I would like to resize it to reasonable size.

I use 2x scaling.

-  Steam client version (build number or date): **Apr 6 2018, at 16:07:06**
-  Distribution (e.g. Ubuntu): Arch Linux
-  Opted into Steam client beta?: Yes
-  Have you checked for system updates?: Yes

**Comment by DerRidda** [comment]
This issue is now resolved for me with the latest Steam beta build (May 04 2018, at 18:35:49).
Would like to hear from the other affected users.

**Comment by ernstp** [comment]
Yeah it seems to be fixed in the latest beta update.

**Comment by srsgores** [comment]
Not fixed for me.  Did I explicitly pass in the params correctly for `GDK_SCALE`?

```steam GDK_SCALE=2```

**Comment by OvermindDL1** [comment]
@srsgores I think that is supposed to be an environment variable so try `GDK_SCALE=# steam` for whatever value `#`.

**Comment by adomas187** [comment]
With **June 1, 2018 build** it seems now everything is OK with window resizing. I do not force GDK_SCALE, but I have 2x scaling because of Font DPI (I think).

**Comment by kisak-valve** [comment]
Closing as fixed.
