### ISSUE TITLE
0 bytes updates

### ISSUE THREAD

**Issue by kisak-valve** [ValveSoftware/steam-for-linux#5644]
Issue transferred from https://github.com/ValveSoftware/Proton/issues/130.
@MartinPL posted on 2018-08-22T17:33:25:

So problem is that Steam after start keep downloading empy updates, i thinks it some save stuff.
https://i.imgur.com/im16Jsn.png

**Comment by mamoit** [comment]
I got 21 of these a couple of hours ago when I turned on Steam.

**Comment by vanyasem** [comment]
For me some updates were not 0-bytes (but still looks like a savegame sync, and not a game update)
![2018-08-23-042945_2880x1572_scrot](https://user-images.githubusercontent.com/13350458/44499596-3edbec80-a68d-11e8-9c73-1ab47e9289b5.png)

**Comment by MartinPL** [comment]
You will get this in all Steam starts

**Comment by sizeofbool** [comment]
Surprisingly, not all windows-only games are affected by this issue.
By checking cache of each affected game steam client marks them as normal ones, but if I restart Steam client all those games return to previous state and require checking game cache again.

Steam library folder is on ext4 filesystem. This behaviour happens only with windows-only games.

**Comment by meowmeowfuzzyface** [comment]
I'm having the same issue:

The "update" completes almost instantly for every game. Every time the Steam client is restarted, the Windows games must download this "update" again. The Steam library folder is on a secondary ext4 hard drive on which I have full read/write permissions. I'm on Ubuntu 18.04.

All native games and most Windows games I've tried so far run successfully, but the Windows games require this instant, 0 byte "update" to be installed before launching. Also, the Windows games run their first time setup every time they are launched, but I'm not sure if it's related. Native games don't have this problem.

**Comment by MordragT** [comment]
Yep i got this Problem too

**Comment by vanyasem** [comment]
@MordragT please avoid the spam of "me too" messages. If you are also affected, give this issue a "thumbs up". Thank you for understanding.

**Comment by nightsky30** [comment]
Same issue.

**Comment by romulasry** [comment]
Subscribing.

**Comment by DanMan** [comment]
Same here. But I copied the games and the appmanifest files over from my Windows install to my Linux library (ext4). Maybe that's the problem? Maybe there's something in the manifest file that causes this?

**Comment by d10sfan** [comment]
I see the same issue with all natively (through steamplay) downloaded games.

**Comment by hamid-elaosta** [comment]
This is a bigger issue than just 0 byte updates. I'm on Ubuntu 18.04 as well, when I launch it re-downloads ~13GB of Darksiders II, ~33GB of Dishonoured 2 and I uninstalled everything else for now to stop it downloading them.

**Comment by axredneck** [comment]
Is it related to case-sensitivity of ext4 somehow?

**Comment by JackRyder** [comment]
Luckily all mine are 0 bytes, although DOOM occasionally tries to download about 280mb.

**Comment by Zamundaaa** [comment]
My windows games are all in a steam library shared with my windows steam client and thus it's on a NTFS partition on another hard drive, so it's most likely not ext4 related. Also sometimes it actually downloads something for me, too. Like The Witcher 3 gets a 130MB download pretty often. And some don't need such an update ever, like Beat Saber or Superhot VR

**Comment by JackRyder** [comment]
@Zamundaaa I think that's just games which have updated, I have it occasionally for my newer games

**Comment by veikk0** [comment]
This is also happening to me. However, for some games the update size is 354.3 MB (Bejeweled 3, Might & Magic: Clash of Heroes, Slab) while for others it's 0 bytes (Spelunky, Sorcery! Parts 1 & 2). This is not happening with native games.
The machine is running Linux Mint Cinnamon 18. With the exception of Slab, I moved these over from my other Linux machine (Linux Mint Mate 18) by using the backup and restore backup functionality of Steam. Both machines are in the Steam Beta. With the exception of Slab, all these games are on a 4TB hard drive (full-disk encrypted EXT4) that's separate from my OS installation which resides on an SSD.

**Comment by axredneck** [comment]
@veikk0 
> 354.3 MB
It's Proton

**Comment by MrNessuno** [comment]
Happened that connecting my windows steam library (NTFS file system). Some games got deleted, or with 300MB circa of data remaining. I had to re-download all missing games.

**Comment by MrCapone** [comment]
Same problem here. Affected only steam play (proton) games.

**Comment by vanyasem** [comment]
@MrCapone please avoid the spam of "me too" messages. If you are also affected, give this issue a "thumbs up". Thank you for understanding.

**Comment by glaere** [comment]
Occurs with Sins of a Solar Empire: Trinity. I don't use Steam Cloud.

Ubuntu 18.04.1.

**Comment by JackRyder** [comment]
![image](https://user-images.githubusercontent.com/8694395/45589177-4c496700-b919-11e8-8dda-7ce727099c40.png)

The following games seemed to have the same update. After allowing one of them to update they all moved to completed. Guessing there's something in these

**Comment by axredneck** [comment]
@JackRyder it's update of Proton itself, not games

**Comment by schmidtbag** [comment]
I've also had this problem (of 0b downloads), though I've had it long before Proton or any Windows games installed on my Steam account.  However, it would only occasionally come up, so it wasn't really annoying.  Now, it's starting to get pretty irritating when I have 10+ games asking to update.

**Comment by MysticTempest** [comment]
There seems to be a few issues regarding this bug with 0 byte updates that started after opting into SteamPlay(Proton).

At its most basic; it seems to be Steam bugging out when modifying the "appmanifest_*.acf" files of these SteamPlay(Proton)-games.
Everytime a Windows game is launched with SteamPlay(Proton); Steam edits the manifest to add the Proton(858280/930400-beta) depot as a "shared depot" to the game's manifest.
Then at next startup, it is removed; only being re-added when the game is launched through SteamPlay(Proton) again.


However, some games seem to get out of sync and stuck in an update loop. You end up with manifests that already have the shared depot enabled at startup. Then Steam tries adding it & then removes it at startup. That's where it notices a 'big' change has occurred & the stateflag in the manifest is changed to 'update required'. The update happens, and it is out of sync again with the depot re-enabled. From there is where you get the constant 0 byte updates.
Not all of them show up in the "Downloads" section, but it's visible in the logs.

I've tried fixing the files manually, but Steam seems to have a local backup it restores from which interferes; or complains about disk write errors if you try to make the manifests read-only.
The most noticeable part of this bug; is either when updates continuously get stuck as "delayed/scheduled", or they take too long to update at startup. So, they end up showing in the "Downloads" section even though they completed updating.


Some example log info:
https://gist.github.com/MysticTempest/a5ae8205aacf921b829d7fe1da31a80a

**Comment by sceglimilano** [comment]
I've 1 ext4 drive with native Linux games and 1 NTFS drive with Windows only games; I've added them as Steam libraries (LG for Linux Games and WG for Windows Games).

Various (but not all) Windows only games from WG library present this 0.0 KB update issue, some of these games work, some no.

I've another "strange" issue that may be unrelated: Shadow of Mordor and Batman Arkham Knight need to be fully downloaded (45 GB each), despite being already fully installed from Windows.

**Comment by sceglimilano** [comment]
> > I've another "strange" issue that may be unrelated: Shadow of Mordor and Batman Arkham Knight need to be fully downloaded (45 GB each), despite being already fully installed from Windows.
> 
> Shadow of Mordor has a native version.

I've checked, and it's on my Linux partition, hence I've should have installed it from Linux. So I'd say the download problem is unrelated to Proton.

**Comment by MadPierrot** [comment]
Same problem here.

**Comment by vanyasem** [comment]
@MadPierrot please avoid the spam of "me too" messages. If you are also affected, give this issue a "thumbs up". Thank you for understanding.

**Comment by bluejamz** [comment]
@vanyasem the problem is though that if you give thumbs up to the op that's like months old, so everyone might think the problem has already been solved, but by adding "me too" you can see the latest date the problem still persists to pester users.

**Comment by Vash63** [comment]
> @vanyasem the problem is though that if you give thumbs up to the op that's like months old, so everyone might think the problemmight no longer show up, but by adding "me too" you can see the latest date the problem still persists to pester users.

If the problem was solved the issue report would be closed. Proper bug etiquette is to use the tools provided to follow or track a bug, otherwise everyone watching the bug is getting emails with worthless 'me too' emails rather than actual development updates on the bug itself.

**Comment by oblitum** [comment]
This has been reported outside of Proton context:

- https://steamcommunity.com/groups/SteamClientBeta/discussions/1/1483235412197539850/

**Comment by Fluffkin** [comment]
> This has been reported outside of Proton context:

I think that's probably a different issue (some comments say it's been happening to them for years). This git issue only happened to me after installing Proton games and only Proton games in my library have the zero byte download problem.

**Comment by oblitum** [comment]
@Fluffkin it may be not technically the same, but the behavior is the same. I had hit it before Proton too, but it was not that annoying, with Proton, things simply got worse.

**Comment by oblitum** [comment]
Not sure if it helps, but this game in particular has literally always a 0 size update anytime I start steam, others do it, but not always: https://store.steampowered.com/app/674940/Stick_Fight_The_Game/.

**Comment by Fluffkin** [comment]
@oblitum It matters that it's not technically the same because this github issue is for the 0 byte problem with Proton games and Proton games only. It isn't the place to try and expand the issue to other problems with downloads. If you scroll back up a long way @MysticTempest seems to have done a decent job of identifying the issue. When that issue is fixed, you will need to find another appropriate bug report for any remaining download issues you may still have.

**Comment by oblitum** [comment]
Not sure whether you ever programmed before, but this kind of association is helpful at problem resolution. _It is_ the same behavior, and that _may_ be helpful at identification.

I didn't post information to solve another problem. It was _solely_ to provide more context for resolution.

**Comment by Fluffkin** [comment]
@oblitum I'm sorry you seem to feel insulted. (I'm not sure whether you've ever tried bug fixing). But read https://github.com/ValveSoftware/steam-for-linux/issues/5644#issuecomment-423718402 .. If that is the main issue here (which seems highly likely), then it can *only* affect Proton games. Once that issue is solved, any remaining issues will be due to a different problem. This issue is tagged "Proton".

**Comment by oblitum** [comment]
@Fluffkin I take no offense, I just provided info that may be of interest for anyone resolving it, which I assume not targeted at you. Enough of chatting in the issue tracker right?

**Comment by Cxpher** [comment]
I have this problem even without opting into Proton. Basically started when Proton started shipping with Steam.

**Comment by MrCapone** [comment]
Yesterday after 3.16-5 proton update steam decide redownload all my proton games. It wasnt 0 byte downloads, i had to download about 60 gb.

**Comment by oblitum** [comment]
@MrCapone I guess that's what's called a beta user experience, for real.

**Comment by dhollinger** [comment]
@oblitum I don't believe 3.16-5 is in beta anymore.

@MrCapone Thanks for reporting what you're seeing, one of the most difficult things to account for with tracking down and fixing bugs is if the issue is reproducible by the developer. To help with this, it'd be good to let @kisak-valve know if your system is configured in a "non-standard" way (I.E. storing the proton games on an NTFS partition mounted in your linux distro).

**Comment by MrCapone** [comment]
@dhollinger 
My system is Linux Mint 19 (Based on Ubuntu 18.04). I use default steam path (~/.local/share/Steam/). And my /home directory on ext4 partition.

**Comment by kisak-valve** [comment]
Per "Fixed 0-byte downloads getting queued on startup for all Steam Play titles" in the [2019-01-16](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1703951108822305086) Steam client beta update, please opt into the beta and retest this issue.

**Comment by wRAR** [comment]
Fixed for me.

**Comment by SketchStick** [comment]
Fixed! (Arch + Btrfs)

**Comment by frostworx** [comment]
after another "download" of all installed games it is gone here too.
thanks a lot!

**Comment by Zamundaaa** [comment]
I had to let them all update once but on restart none rescheduled anymore. Thanks. It was very annoying

**Comment by LiamDawe** [comment]
Yup, needed one more update to each Steam Play title and now it's solved. :+1:

**Comment by AndrewC437** [comment]
Like a few stated, after restarting, updates still showed but after
"updating," the showed no updates available even after quitting Steam.
We'll see if games update property now.

**Comment by hetdegon** [comment]
Seems to be fixed. Thank you!

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.

**Comment by oblitum** [comment]
I'm already into beta (3.16-6). Should I do something to force redownload? Nothing changed for me, both regarding a client update or the zero sized updates.

**Comment by nightsky30** [comment]
Wondrous!

**Comment by kisak-valve** [comment]
Hello @oblitum, downloads are managed by the Steam client, not Proton. You'll want to give https://support.steampowered.com/kb_article.php?ref=7021-EIAH-8669 a read if you need help switching to the beta client.

**Comment by oblitum** [comment]
@kisak-valve I'm using the beta client (necessary for proton 3.16-6 Beta), but I didn't get a recent client update, if I recall correctly, and the system is behaving basically like before, often full of zero sized updates. I asked because it there's any means to force the beta client to update. I could have got the update already and don't know, or I still need it to be applied but for some reason didn't receive it.

**Comment by oblitum** [comment]
Update just arrived, thank god this is finally fixed \o/ Move this fix out of beta soon! No one deserve this, it was painful.

**Comment by oblitum** [comment]
By the way, just for anyone info, my games on a NTFS partition, it has never been an issue (just needs to mount it with my user as owner).

**Comment by ThoreauHenry** [comment]
> Per "Fixed 0-byte downloads getting queued on startup for all Steam Play titles" in the [2019-01-16]

Thank you Baby Jesus.  Clicking through all that crap became a psychological test/game in itself.

**Comment by Unaccounted4** [comment]
With the re-release of the patch, I have noticed there's always 1 game which still presents a 0 byte download.

**Comment by OlliC** [comment]
I have now a few games that are always in planned update state and cannot be brought to actually update.

**Comment by lucifertdark** [comment]
> I have now a few games that are always in planned update state and cannot be brought to actually update.

If the games are small enough have you tried reinstalling them?

**Comment by evilynux** [comment]
The issue seems to have reappeared with today's update...?

**Comment by oblitum** [comment]
@evilynux it happened just once after the update for me, for all games.

**Comment by evilynux** [comment]
Ah, trying to play one of the game affected forces a redownload. This may actually fix the issue. To be continued... the download will take some time. I'll update the status here once it's over.

**Comment by frostworx** [comment]
be careful! with todays update default settings changed and many games are forced to re-download.
"To reduce the amount of lost data, when you start the client after the update, go straight to the Steam settings > Steam Play and enable Proton for all titles and restart the client. The faster you can do that, the less data steam is able to delete." via https://www.reddit.com/r/linux_gaming/comments/ahi5i8/steam_client_beta_update_january_18th/eeet4t4
thx NoXPhasma!

**Comment by frostworx** [comment]
& https://github.com/ValveSoftware/steam-for-linux/issues/6035

**Comment by kisak-valve** [comment]
The discussion here has derailed from the original topic and is most likely a side effect of "Fixed an issue with invalid Steam Play tool selections if user had previously opted in to enable Steam Play for all titles. (Note: this will cause a one-time reset of all Steam Play global and per-app selections to the default state)."  in the [2019-01-18](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1703951108833155107) Steam client beta update and #5901.
