### ISSUE TITLE
Update to 3.7.6 regular deleted every SteamPlay game

### ISSUE THREAD

**Issue by kisak-valve** [ValveSoftware/steam-for-linux#5761]
Issue transferred from https://github.com/ValveSoftware/Proton/issues/1448.
@nilleairbar posted on 2018-09-14T16:37:16:

Every game that I had downloaded via SteamPlay got deleted. Folder structure of the games are still intact but the Steam update deleted all other files of the games. Back to Windows I guess. No way in hell will I download hundreds of GB again just to get those removed again with the next update.

**Comment by nilleairbar** [comment]
System Info gist is [here](https://gist.github.com/nilleairbar/47b7c99502bac55f270a9f813d71fd54).
I didn't change anything in the Steam Play settings. Booted up Steam and wanted to start DQ 11 and got a notification telling me that I'm running the wrong OS for the game.
I guessed it was a Steam Play issue, restarted Steam and at that point the game folders were empty and Steam initiated the download again. 
The filesystem for all of my Steam games is XFS on a LVM logical volume reserved for the games.

**Comment by sputniktr02** [comment]
I can confirm the issue. Most of my games showed up in the update queue and i thought it was another 0 byte updates or proton update but steam started to download whole games again deleting already downloaded game files so if the update starts there is no way but download the game once again. Even the one of them was finished hours ago.
Even some games that doesn't show up in the update queue was deleted once i attempt to launch them. I have lost more than 7 games already. I am on Steam beta, would going back to stable channel help? I don' want to lose remaining games (near 1 TB of data)

My Specs: https://gist.github.com/sputniktr02/3f410eb3d6206ab7bd35b70c6a1bb12c

**Comment by kisak-valve** [comment]
So, no changed steam settings besides enabling Steam Play for all game titles? I asked because this may have been related to #5745.

**Comment by nilleairbar** [comment]
Nope, though that issue reads pretty similar to our issue here. I guess it is a similar issue in that the most recent beta branch got disabled which leads to Steam deleting the Windows games.

**Comment by byte1024** [comment]
I think there's a reason too involving a shared drive with Windows that the OP states also uses Windows, but I can't recall the steps.

Partially, at least if the drive where games are used is not mounted and Steam is started this scenario can lead to a situation where games are all re-downloaded and then mounting poses another problem if I remember correctly.

At least when it happened to me, the 3.7.6 non-beta wasn't there yet. And I've seen this re-download problem happen 2x or more since testing a shared Windows drive where games were installed from Steam via Windows.

**Comment by byte1024** [comment]
> Nope, though that issue reads pretty similar to our issue here. I guess it is a similar issue in that the most recent beta branch got disabled which leads to Steam deleting the Windows games.

At first I was thinking it was a problem from sharing the Drive with Windows and the games becoming available with Proton, since I didn't remember doing anything other than testing that before it happened.

But if a branch was disabled then I suppose that could be a reason that it had to re-download everything to swap to a different one. Kind of lame though.

**Comment by nilleairbar** [comment]
> But if a branch was disabled then I suppose that could be a reason that it had to re-download everything to swap to a different one. Kind of lame though.

That's actually my guess. The games were configured to be run with the Beta branch of Proton, that got dumped with the full release and the client identified those games as Win games without Proton attached so dumped those folders.

**Comment by byte1024** [comment]
> > But if a branch was disabled then I suppose that could be a reason that it had to re-download everything to swap to a different one. Kind of lame though.
> 
> That's actually my guess. The games were configured to be run with the Beta branch of Proton, that got dumped with the full release and the client identified those games as Win games without Proton attached so dumped those folders.

I think its a good guess =)

**Comment by Plagman** [comment]
The new Beta client should improve behavior in that situation.

**Comment by MartynHare** [comment]
This happened to me and made me very angry at the time as I only have 8Mb ADSL broadband.   I hope the new client does fix this.

**Comment by FederalRecall** [comment]
> The new Beta client should improve behavior in that situation.

Has the beta client version of that fix been released fully into the stable client side yet? I would appreciate an update straight away with the fix so that when Proton does get updated I myself won't loose any game that was downloaded.

**Comment by tuxtergames** [comment]
Its happen here today with me, I spent my last night playing warframe, now steam re-downloaded 19GB of my game and Rise sons of rome too, more 24GB, holly hell its really anoying, even with my 1MB of internet, almost a day do re-download the game.

**Comment by kisak-valve** [comment]
Hello @tuxtergames, are you using the beta for Steam's client (not Proton)?

**Comment by tuxtergames** [comment]
> Hello @tuxtergames, are you using the beta for Steam's client (not Proton)?

Sorry, I forgot to left here, I'm using the stable client of steam, with proton beta 3.7.8, and I didn't make anything, just turn off my computer last night and turn on today.

**Comment by kisak-valve** [comment]
Right, so that's older than the [improved behavior](https://github.com/ValveSoftware/steam-for-linux/issues/5761#issuecomment-423011769) changed in the Steam client beta a couple weeks back.

**Comment by tuxtergames** [comment]
> Right, so that's older than the [improved behavior](https://github.com/ValveSoftware/steam-for-linux/issues/5761#issuecomment-423011769) changed in the Steam client beta a couple weeks back.

This make no sense, fixed for beta client and not stable?

**Comment by mistertux** [comment]
Can also confirm, this happened to me as well. All steamplay games were removed, the option "enable steamplay for all other titles" was disabled after the last client upgrade. I hope this doesn't happen again. I am running Arch Linux, Steam Client Beta version 1548107472. I have been on the beta for a long time, and steam is updated regularly. I use the 3.16-6 beta for proton.

**Comment by kisak-valve** [comment]
Hello @mistertux, you've described #5901 as a side effect of "Fixed an issue with invalid Steam Play tool selections if user had previously opted in to enable Steam Play for all titles. (Note: this will cause a one-time reset of all Steam Play global and per-app selections to the default state)." in the [2019-01-18](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1703951108833155107) Steam client beta update.

The issue described here is Steam Play games getting deleted when the variant of Proton in use is removed from Steam's database. The fix for this from back in September should have made it into Steam's stable client and the issue tracked here should be resolved.

If someone comes across this specific scenario, let me know and I can re-open this issue report.

**Comment by Saroufim** [comment]
I just came across this. Steam just deleted all my proton games because I unticked and reticked the option to enable steam play for all titles. All the games except Elder Scrolls Online were deleted and queued again to be downloaded.

**Comment by fsyy** [comment]
same here. steam wanted to update steam client, then it began to loop the update. so i did a reset. after that steamplay for all games was unticked, so i activated it, and half of my games where gone.

**Comment by cookiEoverdose** [comment]
Happened to me too.

**Comment by Saroufim** [comment]
@kisak-valve with 3 different people still experiencing the bug, perhaps it's time to reopen this again?

Additional info from my side: The bug seems to happen a title is using a specific proton version and that version is deleted. Steam turns off steamplay for that game and reenabling it with a valid proton version wipes it and redownloads it again. Similarly, turning steamplay off and back on wipes most of the titles.

**Comment by random2324** [comment]
Just faced this too. I had custom proton versions installed. For some unknown reason it failed to detect them, so I switched to proton 4.11-11. I clicked on play but it told me "Wrong platform". Now some of my games are deleted. Even ones I didnt tried to play. But some do still wrong and doesnt need to redownload.

Really strange behavior. Using up to date Steam Beta Client.

**Comment by random2324** [comment]
And it just happend again. Lost again 100 gigs of content. This time things were different:
I didnt opened Steam for a week. Once opened it installed a steam update. Next it updated some linux native games properly. There was also some updates for proton games. But these were all zero in size.
When I opened Steam for the next time, it also updated steam again. But now, it showed me lot of games in the download queue and all most of them were  complete re downloads.

So I think the problem is, that it sometimes doesnt see proton installed.
I use custom proton from tk glitch and enabled it globally. Maybe thats a bad idea? I probably should use latest official proton version for global enable or enable proton specifically.

**Comment by blastermaster77** [comment]
I got kind of the same problem when I switch off steamplay, on settings and then when I enbaled it, it started to download my last proton game that I launched the others where ok, did this with 2 more games and they did get deleted and redownloaded, the proton games that I did not launch they are still intact so the problem might be with manually switching proton versions on that game or deselecting the steam play option, please test to see if what happens to me happens to someone else.

**Comment by se5a** [comment]
I've got something similar happen in steam feb 11 2020. 

I was messing around with trying to get Mech Warrior Online to run in proton, trying different proton versions, the dropdown box also includes "Steam Linux Runtime" unsure what this was at the time but clicked it anyway just to see what would happen. 
MWO is now re-downloading the whole 20gb. (even though it doesn't have a native client). 
switched it back to proton 5.x but it's still downloading it all. 
this option needs to come with a popup warning. and should probilby be disabled for games that do not have a native Linux client.

**Comment by kisak-valve** [comment]
Hello @se5a, you encountered https://github.com/ValveSoftware/steam-runtime/issues/200, not the issue reported here.

**Comment by random2324** [comment]
Just hit this again. I actually should be smart enough now to keep a backup of all files but unfortunately I'm dumb.
Anyway in my case it has probably something to do with custom proton version. I removed some versions because I needed disk space but this broke some games again. You really have to get alerted if you see 0 Byte updates. Its very likely Steam took the opportunity and just freed some disk space for you.

Different this time was that I couldn't reinstall my games. First steam was crashing when I tried to reach the properties tab then I launched steam from command line and it didnt crash. Strange, as I actually wanted to see the crash backtrace. Another strange thing is that even though the files are completely wiped, the games are still shown as installed in library. When you launch it says it cant find game exe. But trying file integrity check on them also doesnt work. It completes the check very quickly without downloading a single byte, stating everything OK.

The solution to this was to force a specific proton version for the games. Once doing this, the download started immediately.

Conclusion is that Steam is still missing a fallback mechanism. If a game was linked to a specific proton version and this version is no longer available, it should just fallback to the last installed stable one.

**Comment by DanMan** [comment]
Nothing ought to happen until you close the whole settings dialog. Instead it immediately changes files the moment you choose something different in the Proton settings (switching version, enable/disabling it altogether). That's bound to mess up people's files eventually.

**Comment by fsyy** [comment]
> Just hit this again. I actually should be smart enough now to keep a backup of all files but unfortunately I'm dumb.
> Anyway in my case it has probably something to do with custom proton version. I removed some versions because I needed disk space but this broke some games again. You really have to get alerted if you see 0 Byte updates. Its very likely Steam took the opportunity and just freed some disk space for you.
> 
> Different this time was that I couldn't reinstall my games. First steam was crashing when I tried to reach the properties tab then I launched steam from command line and it didnt crash. Strange, as I actually wanted to see the crash backtrace. Another strange thing is that even though the files are completely wiped, the games are still shown as installed in library. When you launch it says it cant find game exe. But trying file integrity check on them also doesnt work. It completes the check very quickly without downloading a single byte, stating everything OK.
> 
> The solution to this was to force a specific proton version for the games. Once doing this, the download started immediately.
> 
> Conclusion is that Steam is still missing a fallback mechanism. If a game was linked to a specific proton version and this version is no longer available, it should just fallback to the last installed stable one.

Same thing happened to me too.
