### ISSUE TITLE
Steam Client Update Dialogue Empty

### ISSUE THREAD

**Issue by nightsky30** [ValveSoftware/steam-for-linux#5789]
#### Your system information

* Steam client version (build number or date): 
![screenshot_2018-09-27_17-37-41](https://user-images.githubusercontent.com/6024315/46178346-193d9680-c27c-11e8-9a47-79b8e021465a.png)

* Distribution (e.g. Ubuntu): Ubuntu 18.04
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
The Steam Client Update Dialogue is empty, and has been empty since perhaps the September 8th or September 19th update.  No information regarding the current update or accordion / expandable update change history is listed in the update dialogue window when the user is prompted to update.  The user is forced to check the Steam Client group for update info.

#### Steps for reproducing this issue:

1. Check for a Steam Client update.
2. Look at update dialogue.
3. Notice blank dialogue window.

![screenshot_2018-09-27_07-20-32](https://user-images.githubusercontent.com/6024315/46178553-fa8bcf80-c27c-11e8-8416-25a812042a15.png)

**Comment by nightsky30** [comment]
Just wanted to mention that it worked today, but hadn't worked the past few updates.  Is it an issue with the client, or was it just a network hiccup?

![screenshot_2018-10-01_20-52-32](https://user-images.githubusercontent.com/6024315/46325071-419afd00-c5bc-11e8-91c3-6477733fb718.png)

**Comment by mozai** [comment]
Still happening.  Build Oct 2 2018, API v018, package versions: 1538443129
![tmp wjsdohge](https://user-images.githubusercontent.com/2396738/46452263-e5291080-c768-11e8-9fea-29c3e33a57ab.png)

**Comment by nightsky30** [comment]
Same here
![screenshot_2018-10-06_01-10-08](https://user-images.githubusercontent.com/6024315/46568054-9ca65a00-c904-11e8-84ba-feb84cdfea6c.png)
![screenshot_2018-10-06_01-08-58](https://user-images.githubusercontent.com/6024315/46568055-a039e100-c904-11e8-9c5d-96f4c75b3844.png)

**Comment by nightsky30** [comment]
Ok, so this was supposedly fixed with today's update (Beta Client, 10/10/2018).  The bug actually didn't happen today, but the possibility was there.  With me the bug was hit or miss.  Should be fixed now.  I'll watch future updates.

**Comment by mozai** [comment]
due to the nature of the bug, I can only test the _previous_ version of Steam.  And the previous version (Oct 5 2018 at 19:12:13, api v018, package 1538771663) still had it.  upgrading now.

**Comment by mozai** [comment]
another update so soon.  the most recent last version (Oct 10 2018 20:36:25, API v018, package 1539205657) _does_ show me the update news... which says "Fixed a regression causing a black rectangle in place of updaet notes for some users when Steam is updated. Note that this fix will work for the next update following this one, but users may still see the black rectangle when recieving this one."

**Comment by mozai** [comment]
Oct 10 2018 23:39:11 API v018 package version 1539216652 prompted me for an update today, and I can see the Steam Client Update dialogue is _not_ empty.  I'm satisfied.

**Comment by h1z1** [comment]
Is this still being tracked under something else because it still randomly happens for me.

**Comment by kisak-valve** [comment]
Hello @h1z1, #6353, #6451.

**Comment by h1z1** [comment]
@kisak-valve  Thanks.  I blame github, those did not show up when I searched.. strange because I have a comment in one of them too.

**Comment by smirkybg** [comment]
Happening on latest Steam Client on Arch Linux. Clicking Restart actually shows it for less than a second, since it's shutting down the client for an update.
