### ISSUE TITLE
iscriptevaluator.exe: cannot execute binary file: Exec format error` - Proton 3.16-4 & -5 beta

### ISSUE THREAD

**Issue by Yorper** [ValveSoftware/steam-for-linux#5963]
_Originally posted by @kisak-valve in https://github.com/ValveSoftware/Proton/issues/556#issuecomment-447582158_

As requested...

With the new proton 3.16-4 and 3.16-5 beta i can no longer launch Elder Scrolls Online. This is the only game i play with proton so i cant test any other games. (TESO works pretty well on 3.7-8 though).

This is the error message when i try to launch the game (with steam started from terminal).

```
GameAction [AppID 306130, ActionID 1] : LaunchApp changed task to ProcessingInstallScript with ""
sh: /home/david/.local/share/Steam/legacycompat/iscriptevaluator.exe: cannot execute binary file: Exec format error
sh: /home/david/.local/share/Steam/steamapps/common/Zenimax Online: Is a directory
sh: /home/david/.local/share/Steam/legacycompat/iscriptevaluator.exe: cannot execute binary file: Exec format error
[2018-12-16 10:56:56] Startup - updater built Nov 26 2018 20:15:21
[2018-12-16 10:56:56] Verifying installation...
[2018-12-16 10:56:56] Verification complete
installscript_posix.cpp (416) : Assertion Failed: Standalone evaluator returned error code for app 306130
installscript_posix.cpp (416) : Assertion Failed: Standalone evaluator returned error code for app 306130
Installing breakpad exception handler for appid(steam)/version(1543346820)
assert_20181216105714_24.dmp[2698]: Uploading dump (out-of-process)
/tmp/dumps/assert_20181216105714_24.dmp
GameAction [AppID 306130, ActionID 1] : LaunchApp changed task to ProcessingShaderCache with ""
GameAction [AppID 306130, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 306130, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 306130, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 306130, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
Opted-in Controller Mask for AppId 306130: 0
Game update: AppID 306130 "", ProcID 2700, IP 0.0.0.0:0
>>> Adding process 2700 for game ID 306130
GameAction [AppID 306130, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
GameAction [AppID 306130, ActionID 1] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/home/david/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/bin/sh: /home/david/.local/share/Steam/steamapps/common/Zenimax Online/zosSteamStarter.exe: cannot execute binary file: Exec format error
Game removed: AppID 306130 "", ProcID 2700 
>>> Adding process 2701 for game ID 306130
No cached sticky mapping in ActivateActionSet.assert_20181216105714_24.dmp[2698]: Finished uploading minidump (out-of-process): success = yes
assert_20181216105714_24.dmp[2698]: response: CrashID=bp-a4287c6e-46d2-4421-a6ff-18d982181215
assert_20181216105714_24.dmp[2698]: file ''/tmp/dumps/assert_20181216105714_24.dmp'', upload yes: ''CrashID=bp-a4287c6e-46d2-4421-a6ff-18d982181215''
```

This is the system spec of the running machine...

```
System:    Host: neon Kernel: 4.19.8-2-MANJARO x86_64 bits: 64 compiler: gcc v: 8.2.1 
           Desktop: Xfce 4.12.4 Distro: Manjaro Linux 
Machine:   Type: Desktop System: ASUS product: All Series v: N/A serial: <filter> 
           Mobo: ASUSTeK model: MAXIMUS VI IMPACT v: Rev 1.xx serial: <filter> 
           UEFI: American Megatrends v: 1603 date: 08/15/2014 
CPU:       Topology: Quad Core model: Intel Core i7-4771 bits: 64 type: MCP arch: Haswell rev: 3 
           L2 cache: 8192 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 28010 
           Speed: 800 MHz min/max: 800/3700 MHz Core speeds (MHz): 1: 800 2: 800 3: 800 4: 800 
Graphics:  Device-1: NVIDIA GP106 [GeForce GTX 1060 6GB] vendor: Micro-Star MSI driver: nvidia 
           v: 415.22 bus ID: 01:00.0 
           Display: x11 server: X.Org 1.20.3 driver: nvidia resolution: 1920x1080~60Hz 
           OpenGL: renderer: GeForce GTX 1060 6GB/PCIe/SSE2 v: 4.6.0 NVIDIA 415.22 direct render: Yes 
Audio:     Device-1: Intel 8 Series/C220 Series High Definition Audio vendor: ASUSTeK 
           driver: snd_hda_intel v: kernel bus ID: 00:1b.0 
           Device-2: NVIDIA GP106 High Definition Audio vendor: Micro-Star MSI driver: snd_hda_intel 
           v: kernel bus ID: 01:00.1 
           Sound Server: ALSA v: k4.19.8-2-MANJARO 
Network:   Device-1: Intel Ethernet I217-V vendor: ASUSTeK driver: e1000e v: 3.2.6-k port: f040 
           bus ID: 00:19.0 
           IF: eno1 state: up speed: 100 Mbps duplex: full mac: <filter> 
           Device-2: Intel Wireless 7260 driver: iwlwifi v: kernel port: e000 bus ID: 03:00.0 
           IF: wlp3s0 state: down mac: <filter> 
Drives:    Local Storage: total: 3.17 TiB used: 461.67 GiB (14.2%) 
           ID-1: /dev/sda vendor: Intel model: SSDSC2BP240G4 size: 223.57 GiB 
           ID-2: /dev/sdb vendor: Intel model: SSDSC2BW240H6 size: 223.57 GiB 
           ID-3: /dev/sdc vendor: Western Digital model: WD3003FZEX-00Z4SA0 size: 2.73 TiB 
Partition: ID-1: / size: 206.63 GiB used: 16.54 GiB (8.0%) fs: ext4 dev: /dev/sda2 
           ID-2: /home size: 2.67 TiB used: 445.13 GiB (16.3%) fs: ext4 dev: /dev/sdc1 
           ID-3: swap-1 size: 17.18 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/sdc2 
Sensors:   System Temperatures: cpu: 29.8 C mobo: 27.8 C gpu: nvidia temp: 41 C 
           Fan Speeds (RPM): cpu: 0 gpu: nvidia fan: 0% 
Info:      Processes: 173 Uptime: 27m Memory: 15.60 GiB used: 1.04 GiB (6.7%) Init: systemd Compilers: 
           gcc: 8.2.1 clang: 7.0.0 Shell: bash v: 4.4.23 inxi: 3.0.28
```

**Comment by Yorper** [comment]
Agreed, it does seem like a steam issue and not a proton one.

I’m wondering if this is unique to Elder Scrolls Online? In so far as Steam only really downloads a launcher and base files and the games launcher is where it actually updates itself... Not via steam updates.

Maybe this is why I can’t verify game files in steam and why proton doesn’t seem to change version....

Let me know if I can provide any more information to help with a fix?

Thanks.

**Comment by kisak-valve** [comment]
Hello @Yorper, per "Fixed more instances of 0-byte downloads and missing Proton or data files for Steam Play titles" in the [2019-03-06](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1798531141142819058) Steam beta client update, please opt into Steam's beta client if you are not already and retest this issue.

**Comment by Yorper** [comment]
Sorry for the late reply.

After changing to the latest beta client and changing in my settings to a version of proton not currently installed. I can now confirm steam client downloads the new proton version selected. I would say this issue is now resolved.

Thanks for your work.

**Comment by burakcoskun** [comment]
I still have the very same issue,

using steam on arch linux with i3wm. if i download a new game it will download steam 3.16.8 beta but otherwise it wont and im getting the exact same errors described on this report.

I am opted into steam beta
