### ISSUE TITLE
Selecting a custom proton unchecks "Enable Steam Play for all other titles"

### ISSUE THREAD

**Issue by popsUlfr** [ValveSoftware/steam-for-linux#6043]
#### Your system information

* Steam client version (build number or date): **1547865289 (Jan 19 2019, at 02:01:59)**
* Distribution (e.g. Ubuntu): **Arch Linux**
* Opted into Steam client beta?: **Yes**
* Have you checked for system updates?: **Yes**

#### Please describe your issue in as much detail as possible:

Hello, selecting a custom proton version that has been installed into `~/.steam/root/compatibilitytools.d` in the Advanced settings of the Steam Play tab unchecks "Enable Steam Play for all other titles".

![screenshot_20190120_142825](https://user-images.githubusercontent.com/1030423/51439861-6a0c4b80-1cc0-11e9-8bbf-d88c275250f4.png)

This seems to be a UI bug since the client still considers the option to be enabled. For non-whitelisted games the custom proton is indeed used : 

![screenshot_20190120_143615](https://user-images.githubusercontent.com/1030423/51439901-f0c12880-1cc0-11e9-894c-bd3819ca804a.png)

There's no problem when selecting an official proton.

#### Steps for reproducing this issue:

1. Install a custom proton (e.g. https://github.com/popsUlfr/Proton/releases)
2. Go to the "Steam Play" tab in the client settings
3. Check "Enable Steam Play for all other titles" if not already done
4. "Run other titles with:" Select the custom proton
5. Restart Steam
6. "Enable Steam Play for all other titles" will be unchecked

**Comment by matveyryabov** [comment]
I am having the same issue - am trying to install glorious eggroll's custom proton script.

**Comment by tjbp** [comment]
I still have this bug. The per-game checkbox setting works fine, so suspect that perhaps has a working custom Proton check that could be used for the global equivalent?

**Comment by dekipantelija** [comment]
Same here, on Manjaro 64bit, the Advances tickbox keeps disabling... 
Having native or manjaro steam changes nothing. The custom protons are recognized though, but i cannot use them.
They also aren't available on individual games

**Comment by cornytrace** [comment]
I am having this problem as well.
I'm on Manjaro KDE 64 bit.

**Comment by JHrenyk** [comment]
Same, having issues on both PoP_OS 20 and Manjaro.

**Comment by romulasry** [comment]
It was working for me a day or so ago, strange.

**Comment by romulasry** [comment]
Had the same issue on the Steam Clear Linux flatpak.

**Comment by LudwigMuggli** [comment]
Same issue on Ubuntu 20.04 with GloriousEggroll Proton-5.9-GE-3-ST

**Comment by LudwigMuggli** [comment]
> It was working for me a day or so ago, strange.

Same with me. It worked one day and the other day this issue occoured

**Comment by romulasry** [comment]
Had a Steam client update, same bug.

**Comment by romulasry** [comment]
Still not working. Would like to play some games that only work in GE.

**Comment by romulasry** [comment]
Is there going to be a proton next update before this is fixed?

**Comment by monterrr** [comment]
The proton setting does become unchecked for me BUT **it still works** and selects that proton as the default for all
Click on (i) button under games banner to check which tool is selected for it.

**Comment by shoober420** [comment]
This is still a thing. On gentoo here non-flatpak.

**Comment by Robob12345** [comment]
Still an issue on Arch and its derivatives. Attempted to set proton ge as well as proton tkg globally and both unchecked the ability to use proton for all titles.

**Comment by Lastique** [comment]
This is still a problem. Valve, is this checkbox so hard to fix that it is still an issue after two years?

**Comment by lucax88x** [comment]
Still a problem on Arch

**Comment by IBBoard** [comment]
Experiencing this on openSUSE Tumbleweed. The tip from @MythicSpirit doesn't seem to work because Proton GE is already set correctly for "0" for me. It looks like it's just the UI not rendering it correctly.

```
                                "CompatToolMapping"
                                {
                                        "0"
                                        {
                                                "name"          "Proton-7.1-GE-2"
                                                "config"                ""
                                                "Priority"              "75"
                                        }
                                        "252950"
                                        {
                                                "name"          "Proton-6.20-GE-1"
                                                "config"                ""
                                                "Priority"              "250"
                                        }
                                        "566440"
                                        {
                                                "name"          "Proton-6.20-GE-1"
                                                "config"                ""
                                                "Priority"              "250"
                                        }
                                …
                                }
```

**Comment by S1ngl3-x** [comment]
Can confirm this is not working on Fedora 35 either. I am using non-flatpak steam.

**Comment by doubledge-spec** [comment]
Issue occurs on a fresh arch install. Used the archinstall tool that came with the iso.

**Comment by sharma** [comment]
Still an issue on a fresh install of Arch.

**Comment by Mossy93** [comment]
I am having this issue on EndeavourOS. I guess the workaround is to set default Proton and just tell each game individually to use custom Proton versions.

**Comment by dankrr** [comment]
> I am having this issue on EndeavourOS. I guess the workaround is to set default Proton and just tell each game individually to use custom Proton versions.

I'm having the same issue on endeavour as well and your workaround works but did you ever find a fix ?

**Comment by NOCx420** [comment]
Still an issue, using Arch

**Comment by otuva** [comment]
still an issue on arch after 3 years almost 4...

**Comment by ranomier** [comment]
![](https://media.tenor.com/rec5dlPBK2cAAAAd/mr-bean-waiting.gif)

**Comment by GamezombieCZ** [comment]
Still and issue, currently on Nobara.

**Comment by viggy96** [comment]
Still a problem, Steam Flatpak, Manjaro.

**Comment by IBBoard** [comment]
This might finally have been fixed in the new UI? The box appears to be ticked for me and the "run with" box retains a selection.
![Screenshot of the new Steam compatibility settings](https://github.com/ValveSoftware/steam-for-linux/assets/388582/7b2b6095-1abb-4072-904a-0c40203fba85)

**Comment by kisak-valve** [comment]
Closing as fixed in the [2023-09-11](https://store.steampowered.com/news/app/593110/view/3651911507669747463) Steam client update.
