### ISSUE TITLE
Steam on Ubuntu 18.04 - "run.sh: No such file or directory"

### ISSUE THREAD

**Issue by CMBadiuk** [ValveSoftware/steam-for-linux#6077]
#### Your system information

* Steam client version (build number or date): Feb 4, 2019
* Distribution (e.g. Ubuntu): Ubuntu 18.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Since installing Ubuntu a couple weeks ago, I've been trying multiple methods to get Steam to start. Whenever I click the icon in my app tray or try to start it via the terminal, it won't. Nothing shows up on my screen at all. After trying to start the app via the terminal, I got this error message:

`Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
/home/hc259/.local/share/Steam/steam.sh: line 828: /home/hc259/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: No such file or directory`

I completely purged Steam and its working folders, then tried to install again from the official .deb package.

#### Steps for reproducing this issue:

1. Install Steam from official Debian package
2. Run Steam in Terminal using `steam`
3. Check command line for error(s)

**Comment by CMBadiuk** [comment]
Yes, I just confirmed that `glxinfo` works, and that I have `mesa-utils:i386`. After making sure I had the mesa utils, I tried running Steam again, then had the same error.

**Comment by waynew** [comment]
I'm having the same problem - Ubuntu 18.04, no such file or directory. `glxinfo` and `glxgears` exist.

And there does, in fact, not exist any `$HOME/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh`.

**Comment by leimao** [comment]
One of the solutions seems to be to install Steam via Ubuntu store (using snap). But I like deb and don't like snap.

**Comment by leimao** [comment]
Sorry, I tried snap on Ubuntu 18.04, it did not work.

**Comment by alwayslivid** [comment]
The template file of `run.sh` can be found here; https://github.com/ValveSoftware/steam-runtime/blob/master/templates/run.sh

I tried adding it manually to the directory `~/.local/share/Steam/ubuntu12_32/steam-runtime/` and running the command `sudo chmod +x` (which gives the script execution privileges), however this didn't quite do the trick for me.

**Comment by leimao** [comment]
> The template file of `run.sh` can be found here; https://github.com/ValveSoftware/steam-runtime/blob/master/templates/run.sh
> 
> I tried adding it manually to the directory `~/.local/share/Steam/ubuntu12_32/steam-runtime/` and running the command `sudo chmod +x` (which gives the script execution privileges).

Does it work?

**Comment by CyberDuncan** [comment]
The error is gone, but steam does not launch. 
Is it a Problem with the Official NVIDIA Driver? 
Because some people on the internet say it is.

**Comment by MagB93** [comment]
I'm observing the same error. :/

**Comment by kiikoh** [comment]
same.

**Comment by TTimo** [comment]
@MagB93 @kiikoh - is your problem `run.sh` error, or that steam does not launch?

**Comment by TTimo** [comment]
Assuming original issue is fixed, closing.

**Comment by jtatusko** [comment]
same issue

**Comment by leimao** [comment]
> Assuming original issue is fixed, closing.

How was it fixed?

**Comment by MagB93** [comment]
@TTimo Sorry for the late answer. I've been busy at work.

I get the following error in the terminal 

```
$ steam
Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
/home/mbad/.local/share/Steam/steam.sh: line 828: /home/mbad/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: No such file or directory
Installing breakpad exception handler for appid(steam)/version(0)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

```
the output of `nvidia-smi` is

```
Thu Mar 28 19:45:13 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2080    Off  | 00000000:29:00.0  On |                  N/A |
| 22%   32C    P8    15W / 215W |    457MiB /  7949MiB |     15%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1265      G   /usr/lib/xorg/Xorg                            28MiB |
|    0      1309      G   /usr/bin/gnome-shell                          58MiB |
|    0      1548      G   /usr/lib/xorg/Xorg                           250MiB |
|    0      7254      G   ...uest-channel-token=16894064775485970758    97MiB |
+-----------------------------------------------------------------------------+

```

Do you need something else?

**Comment by kisak-valve** [comment]
Hello @MagB93, can you verify any 32 bit opengl application like `glxinfo` from `mesa-utils:i386` works? Swrast is mesa's slower cpu opengl renderer and hints that the system is trying to use mesa's libGL.so.1 with nvidia's proprietary driver, which is incompatible.

You are most likely encountering #5778 and run.sh missing could be a red herring.

**Comment by MagB93** [comment]
@kisak-valve no nothing of that matter was installed. I removed the driver from nvidia's site 
and I've tried to install the one from the ppa you've mentioned. But without success. 
The new installed driver just won't load. In Ubuntu-GUI where I can install the driver I can't
fix on the 418 driver. If I install it on the command line won' work either.

I guess I'll return the nvidia card and get an Vega VII instead, my workload besides gaming was FP64 anyway. ^^

Sorry for the trouble.

**Comment by TTimo** [comment]
- Please see kisak's comment about and check that your 32 bit opengl drivers are setup correctly. If not consider opening a separate support issue.

- If your drivers are working correctly, but steam does not start, and you are seeing an error about `run.sh` during startup. Please do the following the report back:

  - start steam with debug verbose, like so: `STEAM_DEBUG=1 steam` - save the output
  - move your current runtime out of the way, to force an extract again: ` mv ~/.local/share/Steam/ubuntu12_32/steam-runtime ~/.local/share/Steam/ubuntu12_32/steam-runtime.off`
  - run `STEAM_DEBUG=1 steam` again - save the output if that still doesn't work and report back ..

Thanks!

**Comment by crawforc3** [comment]
Installed Steam using the instructions here: [https://github.com/ValveSoftware/steam-for-linux](https://github.com/ValveSoftware/steam-for-linux)

First got the error about a missing `run.sh` so I did what @leimao did and manually downloaded it from this repo and put it in the correct folder: https://github.com/ValveSoftware/steam-for-linux/issues/6077#issuecomment-471270471

The missing run.sh error goes away but I am left with two libGL errors.

```
crawforc3@computer:~ $ steam
Setting up Steam content in /home/crawforc3/.local/share/Steam
Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins potentially out-of-date, rebuilding...

/home/crawforc3/.local/share/Steam/steam.sh: line 828: 
/home/crawforc3/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: No such file or directory

Installing breakpad exception handler for appid(steam)/version(0)

libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```

**Comment by kisak-valve** [comment]
Hello @crawforc3, both `glxinfo` from `mesa-utils` (without :i386) and nvidia-smi told you that you have 64 bit nvidia drivers installed properly, but tells you nothing about 32 bit support. In your case you've encountered #5778, which is a driver issue.

**Comment by crawforc3** [comment]
@kisak-valve Thanks, I went back and removed mesa-utils and installed mesa-utils:i386. And you're right. glxinfo now has this output:
```
crawforc3@computer:~ $ glxinfo
name of display: :1
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  54
  Current serial number in output stream:  53
```
Thanks for the quick response!

**Comment by TTimo** [comment]
> First got the error about a missing run.sh so I did what @leimao did and manually downloaded it from this repo and put it in the correct folder: #6077 (comment)

I would like to understand how this happens - there should be no need to get `run.sh` anywhere. It is packaged in the steam runtime that the steam client downloads during first run. If you are able, please run through the steps in https://github.com/ValveSoftware/steam-for-linux/issues/6077#issuecomment-478062644 and report.

**Comment by mr-bjerre** [comment]
Same issues here

**Comment by simos** [comment]
I had this issue when I first installed Steam. It makes it really difficult to replicate if you install it on your desktop. Every Linux installation is somewhat different from another. 

I managed to get Steam to install in a LXD system container and I just completed the instructions,
https://blog.simos.info/running-steam-in-a-lxd-system-container/
That is, you launch a brand new and pristine Ubuntu 18.04 in a LXD system container and then set it up to run Steam in there. Any user-space configuration is restricted in the container.

**Comment by Meru** [comment]
@TTimo that's the issue. When you run steam for the 1st time it does nothing/downloads nothing. Thats why this error appears.
From myself I want to add that this issue does NOT happen with linux mint 19.1 whatever livedvd or clean install but DOES happen after performing system update (prior to making any additional modifications). If steam installed 1st and THEN update is performed, everything continues to work fine.  
Therefore some update breaks steam installation process and not the actual steam.

**Comment by waynew** [comment]
If you can install it in a container both with and without this failure, can you do that and compare the diffs from the base image? I suspect there's a smoking gun somewhere in there - it may be an upstream bug, or it may be something that steam expects as a dependency that's not properly getting installed after the upgrade or something.

**Comment by simos** [comment]
@waynew Once I installed Steam in a LXD system container, it would work. I could not get a case where it stopped working after updates, etc. By default, the Ubuntu container images perform automatically any security updates but you need to explicitly do any non-security updates.

**Comment by Meru** [comment]
As I mentioned before, once steam is installed and was able to launch it would work fine, with or without updates. The problem is with installation process that is supposed to grab additional resources (with run.sh being of them).

**Comment by TTimo** [comment]
@Meru just to confirm - did you use the latest, official `steam_latest.deb` for your first install on ubuntu 18.04? e.g.

`8f8e1e573b5bdf0ffe516f4cba91ed4b  steam_latest.deb` (md5sum, version 1.0.0.59 out of http://repo.steampowered.com/steam/archive/precise/steam_latest.deb)

**Comment by TTimo** [comment]
This new steam debian package candidate should solve the `run.sh` problem (and potentially a number of other issues):

http://repo.steampowered.com/download/testing/steam-launcher_1.0.0.60_all.deb
`fc32d588a5b5fe04cd8d0781c6f934cf  steam-launcher_1.0.0.60_all.deb`

It will install the current steam beta client directly, but that shouldn't be a huge problem. You should still be able to come back down to the production steam client after the bootstrap.

Please test if you are able. We will probably push this new package to replace 1.0.0.59 some time after the current beta client goes to general availability.

**Comment by waynew** [comment]
FWIW for me this partially fixes the problem - i.e. I no longer get `run.sh: No such file or directory`. It hangs at

```
Repairing installation, linking /home/wayne/.steam/steam to /home/wayne/.local/share/Steam
Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(0)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```

Tried `rm -rf ~/.steam && rm -rf ~/Steam && rm -rf ~/.local/share/Steam` after a `sudo apt purge steam` and then relaunching, to no success :man_shrugging:

**Comment by kisak-valve** [comment]
Hello @waynew, swrast is mesa's slower cpu opengl implementation and is commonly seen when the system tries to use mesa's libGL.so.1 with the nvidia proprietary driver, which is incompatible.

What video card / driver version are you using?

**Comment by waynew** [comment]
```
 ~  sudo ldconfig -p | grep -i gl.so                                                                      (2s 911ms)
	libwayland-egl.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libwayland-egl.so.1
	libcogl.so.20 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcogl.so.20
	libOpenGL.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libOpenGL.so.0
	libOpenGL.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libOpenGL.so
	libGL.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libGL.so.1
	libGL.so.1 (libc6) => /usr/lib/i386-linux-gnu/libGL.so.1
	libGL.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libGL.so
	libEGL.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libEGL.so.1
	libEGL.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libEGL.so
 ~  glxinfo | grep OpenGL
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 960/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 415.27
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 415.27
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 415.27
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

```

@kisak-valve I think this should contain all the relevant info?

**Comment by kisak-valve** [comment]
There's a good chance you tested 64 bit glxgears, while Steam is 32 bit, and glxinfo/glxgears from `mesa-utils:i386` would be a better way to check if the 32 bit opengl stack is sane.

In your case, please check if you have `libnvidia-gl-415:i386` with something like `apt policy libnvidia-gl-415:i386` and install it with `sudo apt install libnvidia-gl-415:i386`.

**Comment by Meru** [comment]
@TTimo sorry I couldn't answer sooner. Yes I used latest one on a clean system with and without updating it.

**Comment by TTimo** [comment]
steam-launcher 1.0.0.61 is officially out, assuming this issue is fixed.

If steam doesn't work because you lack working OpenGL drivers, please open a different issue!

**Comment by leimao** [comment]
Still have the same problem with the latest steam client.
```
$ steam --version
tar: This does not look like a tar archive
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
find: ‘/home/leimao/.steam/ubuntu12_32/steam-runtime’: No such file or directory
```

**Comment by leimao** [comment]
I was able to turn on the software for the first time, and I could see that steam was updating. After update, there is nothing happened.

**Comment by leimao** [comment]
Somehow `mkdir /home/leimao/.steam/ubuntu12_32/steam-runtime` fix the problem. But I got another problem later.
```
SteamUpdateUI: An X Error occurred
```

**Comment by PatrickTCB** [comment]
I followed the steps in [comment-478062644](https://github.com/ValveSoftware/steam-for-linux/issues/6077#issuecomment-478062644) and the problem was not fixed. Instead, the app is stuck trying to update itself:

`$ steam STEAM_DEBUG=1                                                                                                                                                                                                                                                                                                                                        
Setting up Steam content in /home/patrick/.local/share/Steam
Running Steam on elementary 5.0 64-bit
STEAM_RUNTIME is enabled automatically
Pins potentially out-of-date, rebuilding...
Installing breakpad exception handler for appid(steam)/version(0)
`
I'll leave it for a few more hours just in case, but I'm quite sure at this point that nothing will happen.
