### ISSUE TITLE
Steam tray icon no longer responds to any clicks

### ISSUE THREAD

**Issue by flybd5** [ValveSoftware/steam-for-linux#6178]
#### Your system information

* Steam client version (build number or date): 18 Feb 2019
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
After the last client update the notification icon no longer responds to any clicks.

#### Steps for reproducing this issue:

1. Update steam client on Linux to latest version
2. Restart client
3. Try to click on the notification bar icon

**Comment by peon501** [comment]
What do you mean?
I have ubuntu 18.10 and tray icon works for me.
When you click on it it opens that dropdown list of games and so on...

**Comment by flybd5** [comment]
I mean it doesn't work and if you check the community forum you'll see I'm
not the only one complaining about this.

**Comment by flybd5** [comment]
I just did a complete uninstall and reinstall with the latest .deb on the site and it still doesn't work.

**Comment by arzardk** [comment]
Same issue on KDE desktop.

**Comment by arzardk** [comment]
Fixed in latest update (2019 16 Apr) for KDE at least.
@flybd5 can you report what is the situation on your system with latest Steam for Linux update?

**Comment by flybd5** [comment]
It works now with the version you folks just released. Thank you.

**Comment by kisak-valve** [comment]
Closing per the last couple comments.

**Comment by Nuc1eoN** [comment]
I still have the isse with kde. It never actually worked corretcly.

**Comment by telans** [comment]
@kisak-valve perhaps this can be reopened? It no longer responds to left or right clicks for me.

Using Steam Beta
Arch Linux, everything up to date

**Comment by flybd5** [comment]
Perhaps someone needs training on regression testing....

---------
A black hole marks the spot where your deity divided by zero.

**Comment by kisak-valve** [comment]
Hello @telans, right clicking on the tray icon works fine on my Arch (KDE) test box with both steam-runtime and steam-native. Please move/remove `~/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_*` somewhere out of the way so that Steam will regenerate them on the next start of Steam. If that doesn't make a difference, please open a new issue report.

**Comment by telans** [comment]
Thank you @kisak-valve, that did the trick. I probably should have done some better searching within the issues on this repo.
