### ISSUE TITLE
Text in Steam tray menu is all rectangles

### ISSUE THREAD

**Issue by erjiang** [ValveSoftware/steam-for-linux#6637]
#### Your system information

* Client version: Oct 30 2019, at 20:05:34
* Distribution (e.g. Ubuntu): Ubuntu 18.04.3 LTS with XFCE.
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

All of the text in the Steam tray menu shows up as rectangles, even though most or all of the text should be just ASCII characters.  It's been like this for a while - not a recent problem.

![Selection_003](https://user-images.githubusercontent.com/321497/68043290-27858f80-fc92-11e9-8636-3173692c39fc.png)

 stdout/stderr do not say anything about missing fonts. I assume either I'm missing some font or the font selection has chosen a wingdings font on accident. 

Here's a list of my system fonts:
[fonts.txt](https://github.com/ValveSoftware/steam-for-linux/files/3798968/fonts.txt)

#### Steps for reproducing this issue:

1. Run Ubuntu 18.04 with XFCE.
2. Have my fonts?
3. Right-click steam tray icon.

**Comment by kisak-valve** [comment]
Hello @erjiang, can you check if there are any hints in `/tmp/dumps/<username>_stdout.txt` or `~/.steam/error.log`?

**Comment by erjiang** [comment]
I don't have any files matching `/tmp/dumps/<username>_stdout.txt`, but I looked through `~/.steam/error.log` and didn't find anything related to fonts, text rendering, etc. Do you know what font is supposed to be selected?

I also tried removing all user fonts from `~/.fonts` and restarting, but still had the same issue.

**Comment by mauriciodelos** [comment]
Hi @erjiang, @kisak-valve , I have the same issue today. First, I installed the Steam fonts in my current font directory (\~/.local/share/fonts) but it didn't work.
Then I figured out the fonts directories list in "\~/.local/share/Steam/bin/panorama/etc/fonts/fonts.conf" is pointing to a different place. So I fixed the path to redirect to my current font directory but did't work either because it is reverted each time I launch Steam. 
I finally opted to create a new "font directory" in the path that file reference (\~/.fonts) and it works well. 
I'm using Xubuntu 
```
uname -a
Linux xubuntu 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by erjiang** [comment]
Unfortunately downloading the steam fonts from https://support.steampowered.com/downloads/1974-YFKL-4947/SteamFonts.zip and extracting to ~/.fonts and also fiddling around with the `~/.local/share/Steam/bin/panorama/etc/fonts/fonts.conf` didn't seem to fix my issue. 

Just to clarify, fonts are rendering fine in the Steam UI, just not the systray menu.

**Comment by scalway** [comment]
I've copied fonts from `~/.local/share/fonts` to `~/.fonts` and it works. 

as mauriciodelos said editing file `~/.local/share/Steam/bin/panorama/etc/fonts/fonts.conf`nor creating symlink `ln -s .local/share/fonts .fonts` did not work.
