### ISSUE TITLE
Most of steam is unusably unresponsive

### ISSUE THREAD

**Issue by codedcosmos** [ValveSoftware/steam-for-linux#7245]
#### Your system information

* Steam client version (build number or date): 
Clicking Help -> About Steam Reveals
Built: Jun 4 2020, at 05:51:01
Steam API: v020
Steam package versions: 1591251555

* Distribution:
Arch Linux with kernel 5.7.7-zen1-1-zen
Using Gnome-Desktop and a 64 bit system.

* Opted into Steam client beta?:
No

* Have you checked for system updates?:
Yes, this issue has persisted through a kernel update as well.

* System Specifications:
Ryzen 7 1700
16 Gigs of ram
Boot SSD
AMD RX 570 (I have a spare 1070 that I can use to test if it's AMD related, but i'm currently using it for some machine learning experiments on a different system)

#### Please describe your issue in as much detail as possible:
Most UI elements take an unexpected amount of time to function. Hovering over the Help text at the top took a couple seconds to highlight it. Clicking it took a couple seconds for the dropdown to appear etc.

The library is mostly responsive, and the store is hit or miss.

Sometimes windows don't even switch, clicking library often takes quite a long time to load. I went to steam help for an unrelated issue, and typing was impossible. I ended up having to copy paste instead which still took quite a long time.

Once I can get to run games, they work perfectly fine. I can run them with the expected framerate, and no other applications on my system have this issue. 

#### Steps for reproducing this issue:
1) Start steam
2) Attempt to interact with the user interface

**Comment by codedcosmos** [comment]
Quick update on this issue. I tested it with my GTX 1070 and the bug disappears. I also have a r7-240 if that is required for testing. But I'd also like to mention I installed all the correct packages required for both graphics cards, and games functioned as expected with both configurations.

**Comment by Newbytee** [comment]
I'm having similar issues on my laptop. Many elements in Steam take a second or so to react to my input. I am, however, opted-in to the Steam Client beta.

Specs:
 - CPU: i7 4650U (something like that)
 - GPU: HD 5000 (Mesa 20.1.2)
 - RAM: 8GB
 - Storage: 512GB SSD
 - Display: 1440p
 - OS: Fedora 32 Workstation (GNOME 3.36)
 - Kernel: Linux 5.7.6

**Comment by Newbytee** [comment]
> Quick update on this issue. I tested it with my GTX 1070 and the bug disappears. I also have a r7-240 if that is required for testing. But I'd also like to mention I installed all the correct packages required for both graphics cards, and games functioned as expected with both configurations.

Seeing as this is an NVIDIA card I'm curious, do you usually use Wayland with the AMD card? I presume you'd use X.Org when using an NVIDIA card.

**Comment by olekolek1000** [comment]
Steam Client is based on Chromium renderer, which has **disabled** hardware acceleration on ALL graphics cards except nVidia..................
Ouch.

**Comment by codedcosmos** [comment]
I tested it with wayland on my AMD r7-240, this does appear to be a bug only effecting AMD based graphics cards. Though I only tested it on wayland, that might be the issue instead. I tried xorg, but I couldn't log in with xorg on gnome for some reason.

**Comment by Newbytee** [comment]
> I tested it with wayland on my AMD r7-240, this does appear to be a bug only effecting AMD based graphics cards. 

Did you miss my comment? I'm having similar issues on Intel.

> Though I only tested it on wayland, that might be the issue instead. I tried xorg, but I couldn't log in with xorg on gnome for some reason.

I'll try on X.Org. Might be why.

> Steam Client is based on Chromium renderer, which has disabled hardware acceleration on ALL (?) graphics cards based on Mesa (tested on Vega 10 and RX 5700 XT).
Ouch.

I had to disable hardware acceleration in Steam on my desktop (which is not affected by this issue in particular) due to web views randomly going black. I have an NVIDIA card there running non-Mesa drivers though.

**Comment by codedcosmos** [comment]
> Did you miss my comment? I'm having similar issues on Intel.

Sorry I misread your HD 5000 assuming it was an ATI Radeon HD 5xxx GPU

**Comment by Newbytee** [comment]
> > Did you miss my comment? I'm having similar issues on Intel.
> 
> Sorry I misread your HD 5000 assuming it was an ATI Radeon HD 5xxx GPU

My apologies, I should definitely have clarified that.

**Comment by Newbytee** [comment]
Some observations:

- I'm able to reproduce this in GNOME Wayland
- I'm not able to reproduce this in neither GNOME X.Org, Sway, nor Plasma (Wayland).

**Comment by Waddlen** [comment]
Pop_OS! 20.04 user, [my system information](https://gist.github.com/Waddlen/ad9804c9d0e4a151c7af5dc3aa95b414)

I can confirm that Steam is fine on X, but is extremely laggy on Wayland.

**Comment by Newbytee** [comment]
I'm unable to reproduce this any more on fully updated Fedora 32.

**Comment by Waddlen** [comment]
As of this morning, I am also no longer able to reproduce this on a fully updated Pop_OS.

**Comment by torar9** [comment]
Same problem here, my Steam UI freezes constantly. It takes few seconds to register clicks.
I tried to disable GPU acceleration, enabled low bandwidth and low performance modes.
This seems to be problem only on Wayland, Steam works completely normal on Xorg.

**Specs:**

**- CPU:** ryzen 7 3700x
**- GPU:** rx 5700 xt
**- GPU drivers:** Mesa 20.1.2
**- RAM:** 16GB
**- Storage:** 256GB NVMe SSD
**- Display:** 1080p 144Hz
**- OS:** openSUSE Tumbleweed (GNOME 3.36.4 Wayland)
**- Kernel:** 5.7.7
**- Steam Beta:** No

**Comment by Waddlen** [comment]
After a few days, I noticed that the issue was happening intermittently. After some investigation, the issue seems to be related to the "Friends & Chat" popup window:
![Friends Window](https://i.imgur.com/gGlxdNa.png)
Here are my findings:
| Main Steam Window Location | Steam Friends Window Location | Lag? |
| --- | --- | --- |
| Monitor 1 | N/A (closed) | No lag |
| Monitor 2 | N/A (closed) | No lag |
| Monitor 1 | Monitor 1 | Lag |
| Monitor 1 | Monitor 2 | No lag |
| Monitor 2 | Monitor 1 | No lag |
| Monitor 2 | Monitor 2 | Lag |

It seems lag in a GNOME Wayland setting is caused by the friends window being open on the same monitor as the main steam window. Closing the friends window by clicking the top-right x, or moving the friends window to a different monitor, or moving the main steam window to a different monitor, instantly makes the main steam window responsive and lag-free again.

**Comment by codedcosmos** [comment]
The latest steam update might fix this issue, can anyone confirm?

**Comment by Waddlen** [comment]
I tested the latest stable and beta Steam, but the issue isn't fixed on my i5-7200U laptop or 3700x+5700XT desktop. Both are running an up-to-date Pop_OS 20.04

**Comment by ben914** [comment]
I have had this issue as well. I think it has something to do with the new fossilize feature that processes shader pre-caching in the background. I will see a few fossilized_replay processes running in my system monitor, and if I open Steam settings and look under shader pre-caching it will show which games are being processed and the percentage complete. Until it finishes Steam is unusable slow, and it does this almost every time I start Steam. There are options that disable it, which might stop Steam from getting really slow, but I haven't tried that because I think it does help some games a lot if I am patient enough to let it finish. 

I have started just letting stay open and not shutdown at night, which seem to help, but if there is a Steam update and it needs to restart I have to wait for a good long while for it to finish pre-caching again.

**Comment by Newbytee** [comment]
> I have had this issue as well. I think it has something to do with the new fossilize feature that processes shader pre-caching in the background. I will see a few fossilized_replay processes running in my system monitor, and if I open Steam settings and look under shader pre-caching it will show which games are being processed and the percentage complete. Until it finishes Steam is unusable slow, and it does this almost every time I start Steam.

If this was the case, why would it only happen in XWayland?

**Comment by ben914** [comment]
> > I have had this issue as well. I think it has something to do with the new fossilize feature that processes shader pre-caching in the background. I will see a few fossilized_replay processes running in my system monitor, and if I open Steam settings and look under shader pre-caching it will show which games are being processed and the percentage complete. Until it finishes Steam is unusable slow, and it does this almost every time I start Steam.
> 
> If this was the case, why would it only happen in XWayland?

Might be different issues. I'm using X.org, not XWayland in my case.

**Comment by ben914** [comment]
Actually, in my case this my not be an issue for me any more. It seems to be responsive for me even while it is doing the background shader pre-caching now. I think a recent update may have resolved it.

**Comment by sannagy90** [comment]
Same issue here. 
Fedora 32 on wayland.
Closing the friends window stops the lag.
[system_information.txt](https://github.com/ValveSoftware/steam-for-linux/files/5179114/system_information.txt)

**Comment by sannagy90** [comment]
Still present on fedora 33 beta

**Comment by 143mailliw** [comment]
Still present on arch using mesa-git

**Comment by hansborr** [comment]
Just in case it is helpful to the devs, I've made a short video demonstrating the problem:

https://youtu.be/Pp-TYBuqm7w

**Comment by pazg1234** [comment]
Can confirm Sway on Debian Testing

**Comment by codedcosmos** [comment]
Just to check are people still getting this issue?

**Comment by hansborr** [comment]
> Just to check are people still getting this issue?

Yes.

**Comment by blutigJK** [comment]
Still an issue for me as well. On a fresh install of Arch Linux Gnome Wayland with a 5700xt using Mesa
Closing the Friends list instantly cures the problem. Kind of annoying.

**Comment by Saroumane** [comment]
Hello, same issue with Ubuntu 20.10 Gnome Wayland. But thanks to @Waddlen for the very efficient workaround ! (Close the "Friends & Chat" popup window)

**Comment by sonnyp** [comment]
Upgraded from Fedora 33 to Fedora 34 - I don't have this issue anymore.

**Comment by LeankitJSmith** [comment]
Fedora 34 beta + GNOME wayland, issue still present for me.

**Comment by syrofoam** [comment]
> After a few days, I noticed that the issue was happening intermittently. After some investigation, the issue seems to be related to the "Friends & Chat" popup window:
> ![Friends Window](https://camo.githubusercontent.com/6171e1731327a709f0643d17bbd880488483126da6845a7a39e14de4b5b65706/68747470733a2f2f692e696d6775722e636f6d2f67476c78644e612e706e67)
> Here are my findings:
> Main Steam Window Location 	Steam Friends Window Location 	Lag?
> Monitor 1 	N/A (closed) 	No lag
> Monitor 2 	N/A (closed) 	No lag
> Monitor 1 	Monitor 1 	Lag
> Monitor 1 	Monitor 2 	No lag
> Monitor 2 	Monitor 1 	No lag
> Monitor 2 	Monitor 2 	Lag
> 
> It seems **lag in a GNOME Wayland setting is caused by the friends window being open on the same monitor as the main steam window**. Closing the friends window by clicking the top-right x, or moving the friends window to a different monitor, or moving the main steam window to a different monitor, instantly makes the main steam window responsive and lag-free again.

Can someone PIN this as an workaround is to move the friends picture into another workspace.

**Comment by antonkurkin** [comment]
I found that turning off animated avatars in the friends list setting effectively fixes the problem for me
(gear on top-right of Friends List -> Friends List -> Enable Animated Avatars... -> set to OFF)

**Comment by Saroumane** [comment]
@antonkurkin Well played, that workaround works for me too, and it's more "permanent" that hiding the Friends window.

**Comment by torar9** [comment]
I can confirm workaround for friends list is working however it will start to lag again when you open chat window.

**Comment by AlexanderGlu** [comment]
I am Using an Radeon 5700 with mesa Driver on Manjaro. My Desktop is Gnome-Wayland (the only one where i encountered the error)

It is still there.

But i have one more Info:
- I use also an animated Profile Picture.
- when Steam is open and also the Friends Window
there are 2 Situations:
- The Friends Window is on Top of each other Window or at least some Pixels of it are visible → no Lag
- The Friends Windows is completely covered from any other Window → The Lag is there
The lag renders steam unusable :-) but at least now with the Information from this Thread i can still use everything and workaround the Issue.

(even covering the Friends Window completely with the own Main windows triggers the Lag (and in that Lag situation any Steam Window is only movable with the [Meta]+[Left mouseclick - Drag] ow with the activity view and dragging the Window to another Activity)

**Comment by taibhse** [comment]
Reporting that I experienced this issue today on Fedora 34 from the news and updates popup.
My guess it that it was due to an animation in the picture.
Closing it resolves the issue and steam UI performs normally.

--

I have already disabled animations on the friends list and had that closed. I have been aware of and dealing with the problem coming from there, but this is the first time I have seen it from a store update popup

**Comment by slavicd** [comment]
Issue present in Ubuntu 20 & Gnome 3.36 & Wayland with AMD GPU. The Friends window to another workspace workaround works.

**Comment by elmo667** [comment]
now that ubuntu 21.04 is out, which uses Wayland as default, this problem will now probably affect a much wider range of users (especially since Wayland now seems actually usable).    
    
Anyhow, can confirm the "put Friends on other monitor" works. Disabling animated avatars does NOT.

**Comment by MayeulC** [comment]
I've been having this issue on Sway/wayland for about a year now.

It seems that it happens when one of the steam windows is obscured.

Examples:
 * Friends window open on another workspace
 * Friends window tabbed with main steam window, hidden
 * Fullscreen video playing, obscuring the main store window (it used to cause it, but I could not reproduce today).

Disabling animated avatars and frames seems to help. I wonder if that is somehow related to [this](https://www.phoronix.com/scan.php?page=news_item&px=X.Org-fakescreenfps):

> Currently when any main hardware screen is powered off, the X.Org Server initializes the fake screen to a one second update interval

It certainly looks like the main window is updated at about 1 FPS. If the main window and other windows (such as friends list) share a timer for repaint events, it could be that an obscured window gets such events at a much lower framerate, thereby limiting that of other windows.

That's a theory anyway, I hope this helps somehow.

**Comment by frostworx** [comment]
To (partially) trigger this for me it is enough to 
open steam -> right click any game -> settings -> compatibility -> uncheck the checkbox
_(the unchecking /fading out alone already feels slow)_.
Then general navigation in the settings window, but also kind of in the main Steam window is extremely slow _(can re-initialize though after unknown time/function call or key/mouse combination)_
With some luck this gets auto resolved with the new _(Steam Deck)_ UI

**Comment by syrofoam** [comment]
Turing off animated avatars fixed the problem. Now I wont have to sign out and close the friends list to be able to use the steam client. Does not happen on x,org but wayland for me.

**Comment by Newbytee** [comment]
> Turing off animated avatars fixed the problem. Now I wont have to sign out and close the friends list to be able to use the steam client. Does not happen on x,org but wayland for me.

It doesn't fix it for me. It makes it less bad, but definitely not fixed.

**Comment by vladimir-novoseltsev** [comment]
I see this issue on Fedora 34 with AMD's RX480.
If I open any of top menu and then move mouse left and right it is visible stutter and main window loses shadow as if Mutter decide that it lost focus.

**Comment by vieruuuu** [comment]
still here same issue

**Comment by bjwest** [comment]
I can't even get the window to open.  When I right click on the icon in the system tray, it takes over 20 seconds for the menu to pop up, then when I click on any entry in it, nothing happens other than the menu going away, not even the exit Steam entry.  The only way I can end steam is to kill the process.  This is after it updated today, but I can't tell you that update's version because I CAN'T GET INTO THE THING!  I can't even get in to stop it from starting minimized to the System Tray to see if it may be responsive from the main window.  There needs to be a way to back out of updates that trash the program so bad we can't do anything but sit here and curse the devs for this update.  Now I'm stuck here until someone figures out what they did to screw it up so bad it won't do anything and fixes it, and I have no idea if leaving this broken thing running will even update itself, let alone notify me that it did.

Operating System: KDE neon 5.22
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.86.0
Qt Version: 5.15.3
Kernel Version: 5.11.0-37-generic (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 3800X 8-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: AMD Radeon RX 5600 XT

**Comment by bjwest** [comment]
Well, it seems to have sorted itself out somewhat.  After leaving it closed for a few hours and watching some Twitch streams instead of playing my own games, it's now responding properly after starting.  Also, ignore that opening to task bar in my previous comment (really wish there was a strikeout char in this editor), there is no setting to start minimized to tray, I'm not sure what I was thinking there.  I was probably getting things mixed up in my frustration.

**Comment by DomiStyle** [comment]
> It seems lag in a GNOME Wayland setting is caused by the friends window being open on the same monitor as the main steam window. Closing the friends window by clicking the top-right x, or moving the friends window to a different monitor, or moving the main steam window to a different monitor, instantly makes the main steam window responsive and lag-free again.

> I found that turning off animated avatars in the friends list settings effectively fixes the problem for me
(gear on top-right of Friends List -> Friends List -> Enable Animated Avatars... -> set to OFF)

I can confirm that both of these workarounds still work. I upgraded from Ubuntu 21.04 to 21.10 which set Wayland as default again without me noticing and I ran into this issue.

I switched back to X11 and everything works as expected again. Since Wayland has other issues on GNOME as well I'm fine with this workaround for now.

**Comment by Tsohndeq** [comment]
Issue is still persists on Gnome + Wayland. Disabling animated avatars does not solving problem, but closing friends window or moving it to the second screen does help.

OS: Manjaro Gnome Quonos 21.2.1
Gnome version: 41.2

**Comment by usrtrv** [comment]
Same issue/solution here when using XWayland. Disabling animated avatars does not fix, moving friends to a different screen does.

OS: Fedora 35
Kernel: 5.14.17-301.fc35.x86_64
GNOME: 41.3
GPU: 6900XT
Mesa: 21.3.3
CPU: 5900X

Displays: 
2560x1440@144Hz
2560x1440@120Hz
1920x1080@60Hz

**Comment by jcdickinson** [comment]
I am having this issue on NixOS + GNOME Wayland + 6900XT + 1080/240HZz.

My avatar has an animated border, closing or moving the friends panel to another screen works.

**Comment by Newbytee** [comment]
I think we have confirmed that this indeed is a problem, and what the reproducers are. It would be nice if we could stop posting more comments about that we have the issue and leave space for updates and such. I am personally staying subscribed to this just in case it gets fixed or there's some other interesting update, but all the "me too" comments create a lot of unnecessary noise.

**Comment by AlynxZhou** [comment]
Another interesting thing I found is that if focus is not on Steam main window, it can behave normal, for example I focus firefox, then move mouse to Steam window and scroll mouse wheel (but not press any button, just hover), it scrolls smoothly.

**Comment by iSaluki** [comment]
This issue is still very present in the latest Steam client release. Using Fedora 35 with Wayland. Usual workarounds are still working.

**Comment by Redemption198** [comment]
Fedora 36 + GNOME 42 + Wayland here, disabling Animated Avatars & Animated Avatar Frames on the friends window seems to fix the performance issues for me

**Comment by iSaluki** [comment]
Tried this on Fedora 35 with Wayland, seems to have fixed the issues for me too. Thanks for pointing this one out :)
------- Original Message -------

**Comment by HenryFBP** [comment]
I have the same issue -- Running Debian 11 on a Panasonic FZ-55, on Gnome 3.38.5. Running integrated graphics (Mesa Intel® UHD Graphics 620 (WHL GT2)). Haven't tried using my Radeon Pro WX 4150 (not sure how to switch to it).

**Comment by AerosolSP** [comment]
Well yea, that's what's been said for 2 years now.

Also: 2 Years?!!!?!!?! Valve I thought you loved Linux. What gives?

**Comment by carleeto** [comment]
Steam's really laggy on Ubuntu 22.04 (clean install). Used to be ok on Ubuntu 20.04 and Ubuntu 21.10.
Graphics card is AMD R9 290x - games run fine.
Disabling animations did not help. 
Closing the friends' window did not help.
Happy to try things out and report back if it help fix the issue.

**Comment by lawl** [comment]
> It seems lag in a GNOME Wayland setting is caused by the friends window being open on the same monitor as the main steam window. Closing the friends window by clicking the top-right x, or moving the friends window to a different monitor, or moving the main steam window to a different monitor, instantly makes the main steam window responsive and lag-free again.

Intestingly enough, for me it was the *opposite*. If I put them on separate monitors, focused other windows, and then switched back to steam, it was barely responsive. If I had them on the same monitor, this didn't happen.

Disabling animated avatars in steam friends did indeed seem to fix the issue. Very strange bug.

**Comment by Big-Brick** [comment]
> After a few days, I noticed that the issue was happening intermittently. After some investigation, the issue seems to be related to the "Friends & Chat" popup window: ![Friends Window](https://camo.githubusercontent.com/6171e1731327a709f0643d17bbd880488483126da6845a7a39e14de4b5b65706/68747470733a2f2f692e696d6775722e636f6d2f67476c78644e612e706e67) Here are my findings:
> Main Steam Window Location 	Steam Friends Window Location 	Lag?
> Monitor 1 	N/A (closed) 	No lag
> Monitor 2 	N/A (closed) 	No lag
> Monitor 1 	Monitor 1 	Lag
> Monitor 1 	Monitor 2 	No lag
> Monitor 2 	Monitor 1 	No lag
> Monitor 2 	Monitor 2 	Lag
> 
> It seems **lag in a GNOME Wayland setting is caused by the friends window being open on the same monitor as the main steam window**. Closing the friends window by clicking the top-right x, or moving the friends window to a different monitor, or moving the main steam window to a different monitor, instantly makes the main steam window responsive and lag-free again.

I have same issue.
Computer
********


Summary
-------

-Computer-
Processor		: AMD Ryzen 9 5900HX with Radeon Graphics
Memory		: 15769MB (3471MB used)
Machine Type		: Notebook
Operating System		: Ubuntu 21.10
User Name		: andrii (Andrii)
Date/Time		: вт, 10-тра-2022 14:12:58 +0300
-Display-
Resolution		: 2560x1440 pixels
OpenGL Renderer		: AMD RENOIR (LLVM 14.0.1, DRM 3.41, 5.13.0-40-generic)
X11 Vendor		: The X.Org Foundation
-Audio Devices-
Audio Adapter		: HDA-Intel - HDA ATI HDMI
Audio Adapter		: HDA-Intel - HD-Audio Generic
Audio Adapter		: HDA-Intel - HD-Audio Generic
-Input Devices-
 Lid Switch
 Power Button
 Sleep Button
 Video Bus
 KYE SYSTEMS CORP. Wired Mouse
 Asus Keyboard
 Asus Wireless Radio Control
 Asus WMI hotkeys
 HDA ATI HDMI HDMI/DP,pcm:3
 HD-Audio Generic HDMI/DP,pcm:3
 ASUE120A:00 04F3:319B Mouse
 ASUE120A:00 04F3:319B Touchpad
 HD-Audio Generic Headset Mic
 HD-Audio Generic Headphone
-Printers-
No printers found

Operating System
----------------

-Version-
Kernel		: Linux 5.13.0-40-generic (x86_64)
Version		: #45-Ubuntu SMP Tue Mar 29 14:48:14 UTC 2022
C Library		: GNU C Library / (Ubuntu GLIBC 2.34-0ubuntu3.2) 2.34
Distribution		: Ubuntu 21.10
-Current Session-
Computer Name		: Strix-G513QY
User Name		: andrii (Andrii)
Language		: LC_CTYPE=en_US.UTF-8;LC_NUMERIC=uk_UA.UTF-8;LC_TIME=uk_UA.UTF-8;LC_COLLATE=en_US.UTF-8;LC_MONETARY=uk_UA.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=uk_UA.UTF-8;LC_NAME=uk_UA.UTF-8;LC_ADDRESS=uk_UA.UTF-8;LC_TELEPHONE=uk_UA.UTF-8;LC_MEASUREMENT=uk_UA.UTF-8;LC_IDENTIFICATION=uk_UA.UTF-8 (en_US.UTF-8)
Home Directory		: /home/andrii
-Misc-
Uptime		: 27 minutes
Load Average		: 2,63, 1,36, 0,98
Available entropy in /dev/random		: 3625 bits (healthy)

**Comment by Bananaman** [comment]
- OS: Fedora 36 Workstation (GNOME 42)
- Desktop mode: Wayland
- Kernel: 5.17.11-300.fc36.x86_64
- NVIDIA driver: 510.68.02 (latest as of writing)
- Steam: "Build 28 May 2022".

It works fine on X11. It is awful on Wayland.

Here are the things I have noted:

- With default Steam settings, you get freezes of several seconds at a time if you try to chat with friends in Steam Chat. The chat input barely even registers. It's absolutely and utterly unusable.
- Putting the Main Steam window (store etc) on a different workspace on GNOME, or closing the window entirely, fixes the extreme sluggishness, but the Chat Window still flickers black occasionally.
- Going into friends list settings and disabling "Animated Avatars" reduced the amount of black flickering in the Chat Window.

Conclusion:

- Close or move main steam window to another screen than your chat window/friends list window.
- Disable animated avatars to further reduce the issues Steam has on Wayland.

This is the workaround for now.

**Comment by Bananaman** [comment]
Another issue I noticed on Wayland: Steam videos cannot play fullscreen anymore.

- Go into any product page, play the video, and try to fullscreen it: Black screen.
- Paste a youtube link into steam chat, play it and try to fullscreen it: Black screen.

Audio still continues playing. Cursor is still visible. And if you click the black screen, it pauses the video.

**Comment by Giga-Pudding** [comment]
I have the same issue. No progress since two years..?

**Comment by Bananaman** [comment]
I guess it's because Wayland was extremely unpopular until this year (2022). Now that NVIDIA has basically-perfect Wayland support, there's been a huge interest in it and it has finally become the default mode on several distros. And Steam Deck also uses Wayland. So I hope that valve will take this issue seriously since Wayland is finally being used by a lot more people.

**Comment by SpidFightFR** [comment]
> * OS: Fedora 36 Workstation (GNOME 42)
> 
>     * Desktop mode: Wayland
> 
>     * Kernel: 5.17.11-300.fc36.x86_64
> 
>     * NVIDIA driver: 510.68.02 (latest as of writing)
> 
>     * Steam: "Build 28 May 2022".
> 
> 
> It works fine on X11. It is awful on Wayland.
> 
> Here are the things I have noted:
> 
>     * With default Steam settings, you get freezes of several seconds at a time if you try to chat with friends in Steam Chat. The chat input barely even registers. It's absolutely and utterly unusable. The window constantly flickers into a big, black square instead of rendering itself.
> 
>     * Separating the Steam Chat from the rest of steam, by putting the Main Steam window (store etc) on a different workspace on GNOME, or closing the window entirely, fixes the extreme sluggishness, but the Chat Window still flickers black occasionally.
> 
>     * Going into friends list settings and disabling "Animated Avatars" reduced the amount of black flickering in the Chat Window.
> 
> 
> Conclusion:
> 
>     * Close or move main steam window to another screen than your chat window/friends list window.
> 
>     * Disable animated avatars to further reduce the issues Steam has on Wayland.
> 
> 
> This is the workaround for now.
> 
> It's sad that no progress has been made in 2 years on this ticket. But now that Steam Deck is out I hope for some development on fixing this. :)

i have the same issue on Plasma: works well on x11, but crashes almost all the time on Wayland.
The steam client usually crashes when i connect my xbox controller (a little notification happens but doesn't disapear like it should, and the client freezes after this). It also crashes randomly when processing vulkan shaders (i ticked "process shaders in background", so those freezes happen almost all the time).

I have no logs atm.

**Comment by SpidFightFR** [comment]
> A valve employee confirmed that SteamOS uses gamescope, a custom Wayland compositor in game mode."
> 
> So it isn't even using a Desktop :-) til you explicitly change to the Desktop mode. And what that is using is another story. at least that that is KDE is fact for now.

Isn't the Arch version of Steam package, programed in 32bit architecture ? 
i quote the Archwiki:
`multilib contains 32-bit software and libraries that can be used to run and build 32-bit applications on 64-bit installs (e.g. wine, steam, etc).`

I don't think it is linked to our problem, yet it's probably not helping...

**Comment by rtentser** [comment]
Get something like this on Plasma Wayland with RX 6600. After the launch steam window is completely unresponsive. If i right-click on steam icon in tray, menu pop-up after several seconds - much longer than usually. X11 works fine

Probably some regression from KDE 5.26. Or maybe mesa 22.2. I've recently updated to manjaro unstable and do not have this problem on laptop with manjaro stable and Vega 7

**Comment by gmod64bit** [comment]
Yep steam on GNU is dogsh!t, especially with tiling window managers.


Clicking Links = Freezing Entire Steam
Too many Steam windows = 1fps steam mode
Unfocused highlighted windows = spam annoying steam bell noise  

Much Cringe Such Fail

**Comment by formidabilus** [comment]
I had this laggy problem with steam on Ubuntu 22.04 using X11 with GTX660M as discrete GPU and now I have the same problem in Fedora37 with GPU 3070ti using Wayland. Using library or chat it's so annoyingly laggy, on Ubuntu I had to run it as steam -no-browser with small mode so it won't affect my games.

**Comment by ehiggs** [comment]
>I'm having similar issues as others. Though, this only happens on Wayland/XWayland.

The issue here seemed to have been fixed for me but came back. I wondered how it could have come back and indeed, I think it's because my Ubuntu box was updated to use Wayland as default.

**Comment by vincebel7** [comment]
Aside from disabling animated avatars, I was also able to fix the issue by unfriending everyone with an animated avatar. 

Ubuntu 22.04
Gnome 42.5

**Comment by dinckelman** [comment]
Disabling animated avatars, or turning off hardware acceleration did not help at all. More often than not, the client would freeze instantly, as it reaches the store frontpage

**Comment by Newbytee** [comment]
As I said previously, I think it is clear how this issue can be reproduced. It would be nice if we could stop posting "me-too" comments so that people subscribed to this issue for actual updates can get to see those without receiving email from people confirming that they too can reproduce this. Granted, if you have something new to add that's great, but most of the comments here only repeat what others already have said.

**Comment by InklingGirl** [comment]
This issue still isn't fixed. @Waddlen's observations make for a suitable workaround, but this has been an issue for over 2 years, & it's ridiculous this was marked as 'closed' when it persists.

**Comment by InklingGirl** [comment]
> As I said previously, I think it is clear how this issue can be reproduced. It would be nice if we could stop posting "me-too" comments so that people subscribed to this issue for actual updates can get to see those without receiving email from people confirming that they too can reproduce this. Granted, if you have something new to add that's great, but most of the comments here only repeat what others already have said.

Copium.

**Comment by formidabilus** [comment]
read the comments, deactivate the animation for the avatars from "Friends" settings, for me this solved it.

**Comment by lkendrickd** [comment]
> read the comments, deactivate the animation for the avatars from "Friends" settings, for me this solved it.

Thanks I missed that comment.  I performed the actions you suggested.  Sorry.

**Comment by joaocsf** [comment]
I have been having the same symptoms with an NVIDIA GPU on Xorg. 
**Disabling** the option `Enable smooth scrolling in web views` on the steam settings (under Interface) improved the overall responsiveness on my end.

**Comment by Munoida** [comment]
> > read the comments, deactivate the animation for the avatars from "Friends" settings, for me this solved it.
> 
> Thanks I missed that comment. I performed the actions you suggested. Sorry.

I did the same thing and it eliminated all of my lag on Steam (of course, I'm using Wayland on my Inspiron Laptop,) maybe its something about allocating everything to the animated picture and picture frames lol. Whatever it may be, I hope it gets fixed soon, such a funny issue.

**Comment by InklingGirl** [comment]
No wonder SteamOS' desktop mode / KDE session still uses X11 lol, w/ Wayland the Steam client can't run an expected & desirable feature (icon animations) w/o slowing to a crawl. Not really acceptable, especially years later. A workaround isn't a fix.

**Comment by coppercore** [comment]
I can also confirm this happened to me.

Manjaro Linux, Gnome 43.2 **Wayland** with Kernel 6.1.7-1-MANJARO #1 SMP PREEMPT_DYNAMIC running a Radeon 6700XT. I had to disable animated avatars in the friends list, and Steam instantly became responsive again.

Also, moving the friends list onto another monitor with the animations active also worked around the issue.

**Comment by twsmith85** [comment]
Same thing on a fresh install of Ubuntu 22.10 with 5.19.0-29-generic #30-Ubuntu SMP PREEMPT_DYNAMIC kernel. Also a Radeon 6700XT.

The only error I see in the logs directly is this, but it happens even with disabling animated avatars and closing the friends list completely. So I'm guessing its unrelated.

(steam:14081): GLib-CRITICAL **: 19:05:21.963: g_main_context_push_thread_default: assertion 'acquired_context' failed
(steam:14081): GLib-CRITICAL **: 19:05:21.963: g_main_context_pop_thread_default: assertion 'g_queue_peek_head (stack) == context' failed

**Comment by InklingGirl** [comment]
Glad to see this is open again at least…

**Comment by Newbytee** [comment]
> Glad to see this is open again at least…

When was it ever closed?

**Comment by InklingGirl** [comment]
> When was it ever closed?

Mistaken, my bad.

**Comment by formidabilus** [comment]
> No wonder SteamOS' desktop mode / KDE session still uses X11 lol, w/ Wayland the Steam client can't run an expected & desirable feature (icon animations) w/o slowing to a crawl. Not really acceptable, especially years later. A workaround isn't a fix.

I don't think it's a Wayland problem, I had before Ubuntu with X11 and I had the same problem I have now with Fedora and Wayland.

**Comment by InklingGirl** [comment]
> I had before Ubuntu with X11 and I had the same problem I have now with Fedora and Wayland.

Now that you mention it, my recollection says the same. Even worse.

**Comment by frostworx** [comment]
*unsubscribing*
doesn't make sense to watch a dead horse being beaten
good luck and hf, and sorry for another mail

**Comment by formidabilus** [comment]
> > I don't think it's a Wayland problem, I had before Ubuntu with X11 and I had the same problem I have now with Fedora and Wayland.
> 
> You probably have a different issue that had the same effect on X11. Using X11 makes Steam run fine, alas compared to Wayland makes Steam slow to a crawl unless if you turn off animated avatar borders/avatars icons, which is true on a fresh Ubuntu install (some distros vary, like pop!_OS which use X11 as default no matter what hardware you use as of now, which I've recently moved to because it's pretty good.) Probably something to do with how Steam utilizes itself on Wayland, most of Steam windows are a chromium process iirc, maybe an update to the chromium process software could fix it?

I don't know, I was using Ubuntu 22.04.. with X11 on a Lenovo laptop and now I'm using Fedora 37 with Wayland on another Lenovo laptop. On both I was using and am using the flatpak edition of Steam.

**Comment by Munoida** [comment]
> I don't know, I was using Ubuntu 22.04.. with X11 on a Lenovo laptop and now I'm using Fedora 37 with Wayland on another Lenovo laptop. On both I was using and am using the flatpak edition of Steam.

Did you give it any permissions, like GPU Acceleration? Because I'm using the normal package from Steam's website (deb) and it worked fine, of course with the Wayland issue.
Flatpak Steam is known to have some issues, alas like with the normal permissions for Flatpak Steam, Left 4 Dead 2 mods do not work correctly.

**Comment by formidabilus** [comment]
I didn't need to give it permissions, beside the animation problem I didin't have any.

**Comment by WhyNotHugo** [comment]
@Munoida Steam via flatpak keeps it's `$HOME` in `.var/app/com.valvesoftware.Steam/`, so paths must be relative to that location. Your issue is likely related to that.

Please open a separate issue however, that's not realy the topic at hand here. Generally, running via Flatpak is a bit more reliable since Steam assumes a lot of dependency versions which might vary with distribution packages.

**Comment by nikolaos-spyratos** [comment]
Interestingly I only had this occur once I downgraded from a CPU & GPU to a 5700G - perhaps ordinary cards can pave over the issue with "brute force"?

**Comment by InklingGirl** [comment]
I too am using a laptop APU.

**Comment by fennecinspace** [comment]
The issue is so annoying, The lag is also present when a Steam library in another SSD is present.

I'm on Linux Mint 21, RTX3070 Max-Q (driver 525.85.12), I7-11850H

**Comment by Nuxmin** [comment]
I've tried this on Ubuntu 22.04, Pop 22.04, Arch Linux KDE. All Wayland and x11. On wayland I encountered this issue on every single distro. On x11 I had none.

However, as stated before on this issue, closing the friends list fixed every single freeze on the app. That's sus!

**Comment by Lexden12** [comment]
Issue still reproducible on Intel Arc A750 on Ubuntu 23.04 (default 6.2 kernel and Mesa 23.0.2 and Wayland). Closing the friends list still fixes it.

**Comment by Newbytee** [comment]
I can't reproduce this any more with the new beta client: https://store.steampowered.com/news/app/593110/view/3686801719529689367

Fingers crossed it's not just a fluke.

**Comment by InklingGirl** [comment]
Can corroborate w/ @Newbytee that the latest beta client seems to be performing perfectly w/o disabling any animations & under the Wayland window server (on Ubuntu 22.04.2, in my case).

**Comment by Munoida** [comment]
> I can't reproduce this any more with the new beta client: https://store.steampowered.com/news/app/593110/view/3686801719529689367
> 
> 
> 
> Fingers crossed it's not just a fluke.

I don't think it is, look at the update notes!

> The technical work in this update also makes it possible to enable hardware acceleration for the Mac & Linux versions of Steam, bringing them up to par with Windows.

**Comment by GabeChiarelli** [comment]
Just ran into this as well. In my case Steam overall was behaving normally, but the "Friends & Chat" and chat windows bogged down to where it was taking 1-2 seconds for any interactions to have an effect. Opted into beta channel and the both windows seems to be working, except for activating the dropdown next to a friend's name - this still takes 1-2 seconds.

System info:
Arch, kernel 6.2.12-arch1-1
Gnome 43.4
Wayland
AMD 5950X
NVIDIA RTX 3080

**Comment by Newbytee** [comment]
> Just ran into this as well. In my case Steam overall was behaving normally, but the "Friends & Chat" and chat windows bogged down to where it was taking 1-2 seconds for any interactions to have an effect. Opted into beta channel and the both windows seems to be working, except for activating the dropdown next to a friend's name - this still takes 1-2 seconds.
> 
> System info: Arch, kernel 6.2.12-arch1-1 Gnome 43.4 Wayland AMD 5950X NVIDIA RTX 3080

Can you test the Steam client beta and see if that fixes the issue?

**Comment by GabeChiarelli** [comment]
> > Just ran into this as well. In my case Steam overall was behaving normally, but the "Friends & Chat" and chat windows bogged down to where it was taking 1-2 seconds for any interactions to have an effect. Opted into beta channel and the both windows seems to be working, except for activating the dropdown next to a friend's name - this still takes 1-2 seconds.
> > System info: Arch, kernel 6.2.12-arch1-1 Gnome 43.4 Wayland AMD 5950X NVIDIA RTX 3080
> 
> Can you test the Steam client beta and see if that fixes the issue?

I mentioned that in my comment - the beta did seem to fix (or mostly fix) the bulk of it except for expanding the friend dropdown, which still took 1-2 seconds.

**Comment by Redemption198** [comment]
I've tested the beta and overall it runs better than before. However the news/offer window arrows (to cycle through the offers) aren't clickable, the in-game overlay runs very laggy and I also have the drop-down issues.

**Comment by Newbytee** [comment]
> I mentioned that in my comment - the beta did seem to fix (or mostly fix) the bulk of it except for expanding the friend dropdown, which still took 1-2 seconds.

Sorry, I missed that somehow.

> I've tested the beta and overall it runs better than before. However the news/offer window arrows (to cycle through the offers) aren't clickable, the in-game overlay runs very laggy and I also have the drop-down issues.

Those sound like different issues though, right?

**Comment by kisak-valve** [comment]
Closing per the last several comments.

**Comment by PaddyMac** [comment]
I hate to comment on a closed issue, but this is still a problem. System is Gentoo on an i7-3770s with an AMD Radeon R7 240. Mouse input is extremely laggy and stuttery even if a game is not running. Just having the client running causes the problem -- even if the friends window is closed and even if the client window is closed and the client is just running in the system tray. Disabling GPU acceleration in settings does not help. The problem only occurs under Wayland. It is not present if I switch to Xorg. I guess that's a viable workaround for the time being, but it's annoying to have to use Xorg just for one problematic piece of software. And it certainly isn't a viable long-term solution. Wayland is eventually going to displace Xorg. So Steam will eventually need to have proper, native support for Wayland.

**Comment by PaddyMac** [comment]
I hate to comment on a closed issue, but this is still a problem. System is Gentoo on an i7-3770s with an AMD Radeon R7 240. Mouse input is extremely laggy and stuttery even if a game is not running. Just having the client running causes the problem -- even if the friends window is closed and even if the client window is closed and the client is just running in the system tray. Disabling GPU acceleration in settings does not help. The problem only occurs under Wayland. It is not present if I switch to Xorg.

Update. I run Gentoo stable which currently defaults to Mesa 23.0.3-r1. But I unmasked (the currently marked unstable) 23.1.3, updated Mesa, and restarted Plasma in Wayland. I can still notice a *very slight* slowness/stutteriness in mouse input. So it is still present, but it is improved enough that it doesn't appear that it will be significantly problematic. It wouldn't hurt for Steam to improve Wayland support, but perhaps updating Mesa will be enough for others also.
