### ISSUE TITLE
unable to access game properties

### ISSUE THREAD

**Issue by mathew2214** [ValveSoftware/steam-for-linux#7564]
#### Your system information: https://gist.github.com/mathew2214/729fc6d2bb0becc52dbf545d55269197

* Steam client version (build number or date): dec 20 2020 23:07:25
* Distribution (e.g. Ubuntu): Debian 11
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] yes

Steps to reproduce: right click on a game in steam library, and click on "Properties"

expected result: properties window opens

observed bugged result: nothing happens, no errors or anything. 

this was certainly a bug introduced in the most recent update. as the previous build had no issues.

**Comment by kisak-valve** [comment]
Hello @mathew2214, just to confirm, does this happen with all games or some games?

**Comment by mathew2214** [comment]
@kisak-valve this happens with every game in my library.

**Comment by mathew2214** [comment]
is there a way to revert to the previous beta as a means to access my game's properties until a proper fix is made?
is there maybe a steam browser protocol to force the properties window to open?

**Comment by TTimo** [comment]
I suspect this is specific to @mathew2214's setup in some way. Unless we see other folks able to reproduce on Debian.

**Comment by mathew2214** [comment]
update: several steam beta updates have passed. and this bug has yet to be fixed by valve. 
its getting rather annoying to have to open big picture, navigate to my game, change a setting, and then close big picture, any time i want to change something.

**Comment by mathew2214** [comment]
UPDATE:
i have discovered that removing the "--no-browser" from steam's switches allows me to access the game properties without the use of big picture. 
however, doing this also completely ruins the performance, stability, and aesthetics of the steam client. so it looks like im stuck using big picture to change my games' properties.

**Comment by TTimo** [comment]
Passing `-no-browser` is unsupported and will likely disable more and more essential functionality moving forward. The Steam client UI is progressively migrating to using "web" tech exclusively.

**Comment by UFeindschiff** [comment]
Could this be reconsidered? CEF is a massive ressource hog which often causes multiple gigabytes of memory usage by the steamwebhelper alone and therefore the Steam client to have a larger memory footprint than many games launched through it.

CPU usage is also through the roof with 10-15% CPU usage with web rendering functionalities enabled and 0.2% with them disabled. Could at least something like a launch argument to get the legacy UI back or a proper Steam minimal client (which offers just installing/launching games as well as the legacy chat) be considered?

**Comment by mathew2214** [comment]
@UFeindschiff passing "-no-browser +open steam://open/minigameslist" almost works for that. the only things that dont work are uninstalling a game, and changing properties.

**Comment by mathew2214** [comment]
still not fixed as of July 2021. 
given how much performance will need to be squeezed from the Steam Deck's advertised specs, i hope the browserless mode gets fixed by then.

**Comment by mwweissmann** [comment]
I do have the exact same problem on Ubuntu 20.04. Big Picture mode lets me do the properties, everything else is partially broken/not showing -- including the **store**! This bug makes Valve lose money as I cannot buy anything on steam.

**Comment by kisak-valve** [comment]
Hello @mwweissmann, you've described a general issue with libcef (Steam's web component) failing to start. Please open a new issue report.

**Comment by Cat-Lady** [comment]
As of today's update, I am experiencing same issue (no properties) without the no-browser. Also on Debian Bookworm.

**Comment by EluWriter** [comment]
Same issue, started after the update. Reinstalling Steam did not help.

**Comment by nrdufour** [comment]
Same exact issue on archlinux with the latest update.

**Comment by aranc23** [comment]
I cannot use the context menus of various kinds in the steam client under Fedora 38, Gnome, with nvidia drivers.
Basically I can open context menus but can't (usually) click anything in them.  The click tends to "fall through" the menu and hit whatever is underneath.  I cannot for instance enable the steam beta, because that's in a context menu of sorts in the settings.  

I can access these menus by using the big picture mode, however.

**Comment by kisak-valve** [comment]
Hello @aranc23, you're looking for #9273 instead of this issue report.

**Comment by centove** [comment]
This also affects me, unable to access any game's properties in my library.

**Comment by evilphish** [comment]
same here on Linux Mint 21.1

**Comment by brucethemuce** [comment]
same issue on Ubuntu 22.04.2

**Comment by Sugarteeth** [comment]
I also have this issue; only able to use the laggy & inconvenient big picture mode to access any game properties menu.

**Comment by jcstier** [comment]
Also seeing this.  Right click on game in my lib, click properties....and nothing pops up.  Running Ubuntu 23.04 on Wayland.

**Comment by Cat-Lady** [comment]
It seems that the issue is quite common-spread. I would like very much to see it resolved - is there something specific that can be done from our side, to help the debugging?

**Comment by TTimo** [comment]
@Cat-Lady we (Valve devs) are more likely to look at an issue if it's a fresh report instead of a necro bump of an old `-no-browser` problem. I see Wayland mentioned .. is this Wayland specific?

**Comment by brucethemuce** [comment]
> same issue on Ubuntu 22.04.2

Im using x11 and the latest beta update of steam. To clarify, the properties popup menu cannot be accessed for any game (or anything from the gear icon menu) unless using big picture mode

**Comment by Cat-Lady** [comment]
> @Cat-Lady we (Valve devs) are more likely to look at an issue if it's a fresh report instead of a necro bump of an old `-no-browser` problem.

I would post it as a fresh issue, but it is, already, choke-full of fresh reports. I guess someone with proper rights can split/rename/whatever the issue.

> I see Wayland mentioned .. is this Wayland specific?

All details are in the reports - it affects both X and wayland, and is encountered by people using wide range of distributions.

**Comment by TTimo** [comment]
There is a new setting `Enable context menu focus compatibility mode` in Settings -> Interface with latest beta client. Does this have any impact on your issue?

**Comment by evilphish** [comment]
@TTimo that setting solved it for me on mint 21.1 (Ubuntu 22.04)

**Comment by evilphish** [comment]
**Update:**

@TTimo See issue here: https://github.com/ValveSoftware/steam-for-linux/issues/9273#issuecomment-1627703608

Second-level menus are not fixed by the compatibility mode.

**Comment by andyczerwonka** [comment]
Sam problem, latest stable client. I'll try the beta client.

**Comment by Owliae** [comment]
I had the same problem on my Fedora 38, but i figured out that changing option "Enable context menu focus compatibility mode" fixes the problem for me. Maybe give a try?
![Zrzut ekranu z 2023-08-04 22-56-08](https://github.com/ValveSoftware/steam-for-linux/assets/59620338/01cd2556-ff61-441a-bd70-fc985c126713)
(Option on the most end of list)

**Comment by BlackMage2** [comment]
> I had the same problem on my Fedora 38, but i figured out that changing option "Enable context menu focus compatibility mode" fixes the problem for me. Maybe give a try? ![Zrzut ekranu z 2023-08-04 22-56-08](https://user-images.githubusercontent.com/59620338/258530320-01cd2556-ff61-441a-bd70-fc985c126713.png) (Option on the most end of list)

thanks, that helped me :D

**Comment by Cat-Lady** [comment]
As mentioned by many, "Second-level menus are not fixed by the compatibility mode."

**Comment by pythoninthegrass** [comment]
> There is a new setting `Enable context menu focus compatibility mode` in Settings -> Interface with latest beta client. Does this have any impact on your issue?

This fixed it for me on Fedora 38, Flatpak Steam client 1694466342. Thanks @TTimo!

**Comment by Kenny-Dave** [comment]
Steam client version (build number or date): 23 09 06
Distribution (e.g. Ubuntu): Linux Mint 19.1 Victoria
Opted into Steam client beta?: [Yes/No] Tried on both
Have you checked for system updates?: [Yes/No] yes

Properties windows, and other secondary windows, start with just maybe 50 pixels height. Some widows I can maximise, so I can see those. The ones I cannot, I cannot use. Steam seems to function normally otherwise. I didn't have the issue with Ubuntu and gnome.

**Comment by rubinlinux** [comment]
> There is a new setting `Enable context menu focus compatibility mode` in Settings -> Interface with latest beta client. Does this have any impact on your issue?

This fixed it for me. Mint 21.2 cinnamon w/ nvidia

**Comment by Kenny-Dave** [comment]
> > There is a new setting `Enable context menu focus compatibility mode` in Settings -> Interface with latest beta client. Does this have any impact on your issue?
> 
> This fixed it for me. Mint 21.2 cinnamon w/ nvidia

I have all this in place and still have the issue. I think it might (although probably not) be due to monitor geometry, due to the position of the windows. I have 2x2, the borked windows are flat to the bottom of the top screens. I've just done a test on the settings window (which is rescalable now fortunately), when Steam is open on bottom right, then on top right. Top right is borked, bottom right is not.

**Comment by Draconicrose** [comment]
For a time the 'Enable context menu focus compatibility mode' setting worked, but now it doesn't anymore. Steam version 1701825895. It's the beta, but the problem is present in the stable release as well. Mint 21.2, NVIDIA 545.29.06.

**Comment by Cat-Lady** [comment]
It never worked fully (always failed for the second-level context entries) - but, the "workaround" of holding ctrl while clicking works for me. You can try if it is the same for you.

**Comment by Draconicrose** [comment]
No, the Ctrl workaround doesn't work either. Only changing the windows focus mode on the OS to click works.

**Comment by LucasiTR** [comment]
I have the same issue as well. I click on the button, but nothing happens. I'm running Steam on Garuda Linux cinnamon with the latest kernel.

**Comment by Kenny-Dave** [comment]
OK so I'm sure it's monitor geometry, at least for me. Having the steam window on the bottom two windows works fine, on the top two it produces this error. 

Furthermore, another program, GTK has just encountered the same error, solved by moving the main GTK window to one of the bottom monitors. 

What geometry do others have? What linux distro? 

I am Mint Cinnamon, I have 2x2 monitors.

**Comment by Cat-Lady** [comment]
Just single monitor, the issue is persistent on all machines. The "hold ctrl trick" bypasses it for me, since... Looong time.

**Comment by Augusto7743** [comment]
"Enable context menu focus compatibility mode" has fixed in my system Ubuntu 20.04.6.
Thanks !!!

**Comment by centove** [comment]
Looks like this is being triggered by the focus mode of the window manager, if it's set to anything other than click to focus, the context menus are unpredictable.

**Comment by KanuX-14** [comment]
> I had the same problem on my Fedora 38, but i figured out that changing option "Enable context menu focus compatibility mode" fixes the problem for me. Maybe give a try?

This essentially fixed my problem on LXDE. I have only this option enabled now.

**Comment by feer9** [comment]
So, August 2024 and this issue still persist. Valve are you there?

**Comment by Zargess** [comment]
Encountered the same issue today on Debian 12 with a Gnome 43 Wayland session. The "Enable context menu focus compatibility mode" fixed the first level of options, but couldn't click on second level options. Everything works fine on a X11 session.

**Comment by crysman** [comment]
Still an issue in 2026-03 :(

I have to activate the `small mode` or `big picture` to have Properties actually opened.

"Enable context menu focus compatibility mode" does NOT help.

Debug info:
Pop!_OS 22.04 LTS on X11

About Steam
Steam Beta Branch:  Stable Client
Steam Version:  1769025840
Steam Client Build Date:  Wed, Jan 21 18:12 UTC -08:00
Steam Web Build Date:  Wed, Jan 21 20:41 UTC -08:00
Steam API Version:  SteamClient023

**Comment by SimplyCEO** [comment]
Use `Shift` or `Ctrl` to open the bugged context menus. The cause may be CEF. The framework is "forced" to create a new window on another "tab" but since the launcher has a single "tab" only it may try to create another "tab" ending up opening the window.

**Comment by crysman** [comment]
FYI, holding SHIFT or CTRL has no effect
