### ISSUE TITLE
steamwebhelper consuming cpu even if minimized

### ISSUE THREAD

**Issue by kokoko3k** [ValveSoftware/steam-for-linux#8258]
#### Your system information

* Steam client version: Nov 22 2021 at 22:12:42 ; Steam package version 1637624439
* Distribution: Archlinux
* Opted into Steam client beta?: NO
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
steamwebhelper uses cpu even when it is not necessary and uselessly.

#### Steps for reproducing this issue:

1. From the steam client store tab, have a video playing
2. note that the cpu is higher, it is due to steamwebhelper cpu usage, note it.
3. minimize steam client
4. Notice that the cpu usage remains the same

Imho, steamwebhelper has no use if nobody is watching it, so the process should be stopped, or at least paused, when minimized.
If someone has some interest in just "listening" what it is playing in background, then he can keep it unminimized or at very last, an option like "low performance mode" should control even this behaviour.

**Comment by ishitatsuyuki** [comment]
Bump. From my testing, it's not only consuming ~25% single core CPU but also some amount of GPU, potentially lowering gaming performance. This can be quite a dealbreaker and should be fixed.

I did not observe this behavior on Windows. Not sure about past Linux versions but this could be a Beta regression for Linux.

**Comment by ishitatsuyuki** [comment]
Huh, reporter does not use Beta. So either the situation on Beta is worse or it's a issue that has existed for a while.

**Comment by coozoo** [comment]
I can confirm that steam cpu usage really high especially with latest versions stemwebhelper few processes consuming in total about 130-150%, just one process about 70-80% and never gets low no matter is it minimized or not. It's 4 cored laptop with hyperthreading so basically almost half of CPU resources are busy with steam client it is additionally to high memory usage... I haven't played any video just simply launched steam client and sometimes I can play some games...

**Comment by kokoko3k** [comment]
> Huh, reporter does not use Beta. So either the situation on Beta is worse or it's a issue that has existed for a while.

Probably long standing issue, but can't be 100% sure

**Comment by ishitatsuyuki** [comment]
Here's a recap after some investigations:

**Problem**: steamwebhelper (CEF) does not detect whether it's occluded/minimized and constantly continues rendering in the background.
**Workaround**: Switch Steam to a page that does not have videos or animations. In the case of library pages, you need to enable "Low Performance Mode" from "Settings->Library" or the glowing achievements frames would ruin the performance.

**Comment by tukoz** [comment]
To add another feedback on Steam Beta for Linux, here on Arch:  
- Steamwebhelper uses a full cpu thread from the moment I launch it on the 'Store' page till I change to eg the 'Library' page.  
- Steamwebhelper's CPU use while playing a game goes up to 37.5% of my 4 threads 2 cores Intel CPU @3.3GHz (more CPU than the game I play...). That was after hours playing with Steam minimized before starting this game.
- observations above all are with "Low Performance Mode" activated.
- High CPU usage isn't new here. *staying high* is.

**Comment by ianvm** [comment]
Ate all my CPU too, indeed even with "low performance mode"
Workaround ~ load steam without the browser function : 

steam steam://open/minigameslist -console -no-browser


Steam looks really dated like that, but I can at least play my games without the 50% FPS decrease.

**Comment by kokoko3k** [comment]
> Ate all my CPU too, indeed even with "low performance mode" Workaround ~ load steam without the browser function :
> 
> steam steam://open/minigameslist -console -no-browser
> 
> Steam looks really dated like that, but I can at least play my games without the 50% FPS decrease.

Doesn't switching to Library tab work for you instead of opening the whole thing with no-browser parameter?

**Comment by ianvm** [comment]
> > Ate all my CPU too, indeed even with "low performance mode" Workaround ~ load steam without the browser function :
> > steam steam://open/minigameslist -console -no-browser
> > Steam looks really dated like that, but I can at least play my games without the 50% FPS decrease.
> 
> Doesn't switching to Library tab work for you instead of opening the whole thing with no-browser parameter?

Nope!! eats my CPU no matter what I do

**Comment by Saroumane** [comment]
I wonder if the high CPU / high RAM usage is correlated with the number of games in library ?
With around ~2000 games, my steam/steamwebhelper processes uses more than **1.45 GB**, just after launch. (Despite that I have all "low performance" boxes checked) + **10-40% CPU** (on a 12-cores Ryzen). Minimizing steam windows does not change anything.

If I launch steam with  `-no-browser` (what a lifesaver !), steam uses only **261 MB** + 0/1 % CPU

**Comment by coozoo** [comment]
> I wonder if the high CPU / high RAM usage is correlated with the number of games in library ? With around ~2000 games, my steam/steamwebhelper processes uses more than **1.45 GB**, just after launch. (Despite that I have all "low performance" boxes checked) + **10-40% CPU** (on a 12-cores Ryzen). Minimizing steam windows does not change anything.
> 
> If I launch steam with `-no-browser` (what a lifesaver !), steam uses only **261 MB** + 0/1 % CPU

It's absolutely unrelated. It's related to bad programming style and worse technologies. I have just about 40 games and it's usually from start more than 1 GB....

nobrowser option it's saving some RAM for me it's about 50MB in RAM till the moment when I want to maximize steam window.

high cpu usage usually related that steam making some sale and hot it's cool to make falling snow or some another crap and yahoo CPU loaded with this crap even when you minimizing changing tabs it is still loads you cpu with that sh*t. But it is just one case...

**Comment by kaphula** [comment]
> steam steam://open/minigameslist -console -no-browser

This seems to be the only working solution for me. Otherwise 1 cpu core of my laptop is 25% utilized and the fans scream when ever steam just idles in the background.

**Comment by brianstamper** [comment]
Curious if there is correlation here with DE. I'm using Arch with KDE/Plasma and lately have been having occasional bog downs that I'd get out of with a `killall plasma_session`. Just today I'm realizing I have this same issue with Steam, so I wonder if that is behind it all, because killing the session also closes the Steam client. So far the "switch to library tab" solution seems to be working for me.

**Comment by kriss-s** [comment]
Have had CPU issues with steamwebhelper for at least a year or so, LInux Mint, CInnamon. Don't think there is a correlation to DE used.
For me keeping the Library tab open was the only solution that worked most of the time, until I now ticked the low-performance mode which seemed to have helped. The CPU usage would be fairly low on the library page with full effects, but as soon as it was minimized the CPU would go to 100% and stay there till the Library page was opened again.

**Comment by RodoMa92** [comment]
> Curious if there is correlation here with DE. I'm using Arch with KDE/Plasma and lately have been having occasional bog downs that I'd get out of with a `killall plasma_session`. Just today I'm realizing I have this same issue with Steam, so I wonder if that is behind it all, because killing the session also closes the Steam client. So far the "switch to library tab" solution seems to be working for me.

Same here, steamwebhelper is always active even in background (KDE/Arch/X11). Only when switching to the library tab and minimizing that steamwebhelper stop using any meaningful CPU cycles. This is especially an issue on systems on a constrained power budgets like laptops. Hope to see it fixed soon.

**Comment by sabian2008** [comment]
In my case, I only get high idle `steamwebhelper` usage if I have the friends menu opened. With that menu closed, even if I still have chat windows opened, I don't have abnormal CPU usage.

Can't remember this happening years ago, it must have started sometime in the last year or so. Is it possible a bug introduced with the animated avatars and frames?

**Comment by degasus** [comment]
I can confirm that `-no-browser` is the only way to stop the steamwebhelper to waste a lot of power. Archlinux, gnome, wayland here.

**Comment by Tricky12321** [comment]
> I can confirm that `-no-browser` is the only way to stop the steamwebhelper to waste a lot of power. Archlinux, gnome, wayland here.
> 
> This is a serious issue, so Valve, please fix it.

I have the same problem Archlinux, gnome, xorg.

Same fix with `-no-browser` worked.

**Comment by 1player** [comment]
Same issue with Wayland. Still broken on the Beta branch.

**Comment by sabian2008** [comment]
> This bug is really annoying. While `-no-browser`, it breaks a lot of other functions like chats, stuff in the overlay etc.

Try, as I suggested, closing the Friends panel. I know it's non-optimal, but if I keep it closed, even with the Library and chat windows opened, I get an acceptable 7% of CPU core usage. That way I can keep the steam browser enabled, which it doesn't break functionality. Perhaps this workaround can help you too.

**Comment by jhenninger** [comment]
> Try, as I suggested, closing the Friends panel. I know it's non-optimal, but if I keep it closed, even with the Library and chat windows opened, I get an acceptable 7% of CPU core usage. That way I can keep the steam browser enabled, which it doesn't break functionality. Perhaps this workaround can help you too.

Unfortunately this doesn't seem to work. Just had steamwebhelper using >80% CPU again with no Steam windows open at all. Opening and closing the friends panel didn't helper either.

**Comment by havit1** [comment]
+1. What's interesting, in my case hight cpu usage only occurs when "downloads" page has some entities, after clearing them (clicking close button) cpu usage goes back to normal. (no beta, version 1.0.0.74)

**Comment by ishitatsuyuki** [comment]
> **macOS/Linux**
> 
>    Fixed resource usage of chat and browsers when Steam client is minimized/closed

*https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3350130288813963246*

**Comment by RodoMa92** [comment]
I do not see the same behaviour now, AFAICS.

It could be finally fixed. Let's hope that it will stay that way.

Marco

**Comment by n0nuser** [comment]
Using Ubuntu 20.04 on an Intel i5-7200U with 8GB. of RAM.

Output of uname: `Linux n0nuser 5.13.0-52-generic #59~20.04.1-Ubuntu SMP Thu Jun 16 21:21:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

Steam version:

```
Built: 7 Jun 2022 at 03:18:43
Steam API: v020
Steam package versions: 1654574690
```

Attaching a filtered `htop` image for reference as of today.

![Screenshot from 2022-07-05 13-27-59](https://user-images.githubusercontent.com/32982175/177318546-22442a6c-e6e3-44f3-bcd1-29f0a92cd0ed.png)


<details>
<summary>cef_log.txt</summary>
<pre>
[0705/132428.688698:INFO:crash_reporting.cc(246)] Crash reporting enabled for process: browser
[0705/132428.815690:INFO:crash_reporting.cc(269)] Crash reporting enabled for process: gpu-process
[0705/132428.901316:INFO:crash_reporting.cc(246)] Crash reporting enabled for process: utility
[0705/132432.430183:INFO:crash_reporting.cc(269)] Crash reporting enabled for process: renderer
[0705/132432.508422:INFO:crash_reporting.cc(269)] Crash reporting enabled for process: renderer
[0705/132432.535912:INFO:crash_reporting.cc(269)] Crash reporting enabled for process: renderer
[0705/132433.603496:INFO:crash_reporting.cc(269)] Crash reporting enabled for process: renderer
[0705/132433.606771:INFO:crash_reporting.cc(269)] Crash reporting enabled for process: renderer
[0705/132433.652074:INFO:crash_reporting.cc(269)] Crash reporting enabled for process: renderer
[0705/132433.760858:ERROR:x11_software_bitmap_presenter.cc(132)] XGetWindowAttributes failed for window 0
[0705/132433.764585:WARNING:xproto_util.cc(49)] X error received: serial 166, error_code 9 (BadDrawable), request_code 55, minor_code 0 (Unknown)
[0705/132433.768590:WARNING:xproto_util.cc(49)] X error received: serial 167, error_code 3 (BadWindow), request_code 3, minor_code 0 (Unknown)
[0705/132433.772769:WARNING:xproto_util.cc(49)] X error received: serial 169, error_code 13 (BadGC), request_code 60, minor_code 0 (Unknown)
[0705/132438.270012:INFO:CONSOLE(15)] "FriendStore.ForceReadyToRender() - Initial Persona States not ready: 0 received, friends list: 27 users", source: https://community.cloudflare.steamstatic.com/public/javascript/webui/friends.js?v=6Pm6N3h_MhIP&l=english&_cdn=cloudflare (15)
[0705/132438.270315:INFO:CONSOLE(15)] "FriendStore.ForceReadyToRender() - Initial app info not ready", source: https://community.cloudflare.steamstatic.com/public/javascript/webui/friends.js?v=6Pm6N3h_MhIP&l=english&_cdn=cloudflare (15)
[0705/132438.270558:INFO:CONSOLE(15)] "FriendStore.ForceReadyToRender() - Per-friend preferences not ready", source: https://community.cloudflare.steamstatic.com/public/javascript/webui/friends.js?v=6Pm6N3h_MhIP&l=english&_cdn=cloudflare (15)
</pre>
</details>

**Comment by ishitatsuyuki** [comment]
@n0nuser Have you see the Steam beta client changelog above and try updating to the Jun 27 beta?

**Comment by n0nuser** [comment]
@ishitatsuyuki Nope, sorry.

Updating the info. to be a comparison reference between the stable and the beta versions.

Steam version:

```
Built: Jun 27 2022 at 21:00:03
Steam API: v020
Steam package versions: 1656367348
```

![Screenshot from 2022-07-05 13-53-31](https://user-images.githubusercontent.com/32982175/177322439-5e21d6ed-4381-4807-b19f-ccc0b6b1e1a3.png)

<details>
<summary>cef_log.txt</summary>
<pre>
[0705/135112.271796:INFO:crash_reporting.cc(246)] Crash reporting enabled for process: browser
[0705/135112.334335:INFO:crash_reporting.cc(269)] Crash reporting enabled for process: gpu-process
[0705/135112.381861:INFO:crash_reporting.cc(246)] Crash reporting enabled for process: utility
[0705/135114.330971:INFO:crash_reporting.cc(269)] Crash reporting enabled for process: renderer
[0705/135114.455312:INFO:crash_reporting.cc(269)] Crash reporting enabled for process: renderer
[0705/135114.503021:INFO:crash_reporting.cc(269)] Crash reporting enabled for process: renderer
[0705/135115.932812:INFO:crash_reporting.cc(269)] Crash reporting enabled for process: renderer
[0705/135115.943303:INFO:crash_reporting.cc(269)] Crash reporting enabled for process: renderer
[0705/135115.994848:INFO:crash_reporting.cc(269)] Crash reporting enabled for process: renderer
[0705/135248.876012:INFO:crash_reporting.cc(269)] Crash reporting enabled for process: renderer
</pre>
</details>

**Comment by kisak-valve** [comment]
Thanks for retesting, closing as fixed in the [2022-07-27](https://store.steampowered.com/oldnews/141152) Steam client update.

**Comment by kokoko3k** [comment]
I think this needs to be opened.
For me the issue is present right now,  and it is even worse, because not only steam client is minimized, but it is literally not showing anything "moving", just my static library:
![immagine](https://user-images.githubusercontent.com/1230726/215750760-fcc6fc7b-4368-4c9b-8326-3109d8300a43.png)

I request this issue to be reopened, sob...

**Comment by serprex** [comment]
I'm also seeing steamwebhelper hogging cpu

**Comment by janek-git** [comment]
i can confirm the Issue still exists, i was wondering why i got 50 more FPS in Nobara then in my normal Fedora (170fps vs 120fps), and i find out its because my CPU bottlenecked and this was because steamwebhelper is grabbing a full 4,7GHz Core of my 4 Core CPU (7600k).

minimizing Group Chat Channel Window and Friends Panel solve the cpu hook, but this is really annoying :(

**Comment by hbede** [comment]
I have the same issues, I tried the suggestions above (launching with -no-browser flag, switching to library, putting steam to background, enabling low-performance mode, disabling gpu acceleration...), but nothing works! I am using a laptop with switchable graphics (AMD Ryzen CPU + iGPU and Nvidia dGPU), and in both integrated and dedicated mode the issue persists. At least 4 out of 16 threads are running on 100%, and the laptop runs very hot. I am using Fedora with gnome and wayland.

**Comment by jkrasna** [comment]
I have noticed that this only happens when I have __Limit Download Speed__ (Steam -> Settings -> Downloads) setting enabled and am downloading a game or update. As soon as I switch this setting off the CPU consumption of all `steamwebhelper` processes reduce considerably.

**Comment by fiechr** [comment]
I'm having the same issue on Manjaro Linux. "steamwebhelper" usually consumes different amounts of CPU time, even if minimized or if I'm using another desktop. More than any other app in idle.

Disabling the download speed limit didn't change anything, unfortunately.

It can't be that hard for the devs to find out what exactly is causing the issue, can it?

**Comment by ryannathans** [comment]
yeah I'm seeing this issue with steam running on boot **(silent/minimized)**

the process uses about ~10% of a core (CPU: 5950X) indefinitely **until I open my steam library and close the window again**

**Comment by academo** [comment]
I'm having this issue. Steamwebhelper consuming 100% of a single core of my CPU while minimised.

**Comment by joshgiesbrecht** [comment]
Same as academo. 50%-100% CPU usage on one core, seems to be more likely to happen after a game is run and then closed.

**Comment by skookie** [comment]
Yeah this needs to be reopened. This process is consuming all my cpu. This is madness.

**Comment by skookie** [comment]
> Thanks for retesting, closing as fixed in the [2022-07-27](https://store.steampowered.com/oldnews/141152) Steam client update.

So you just close it? This is total madness; it is eating 35-40% of my cpu: This kind of non-provisioned system resource domination is more closely associated with a virus than with computing. 
  16464 skookie   20   0 9485588 713852 258884 S  39.3   0.3  42:27.81 steamwebhelper

**Comment by vbichkovsky** [comment]
Just googled 'ubuntu steamwebhelper' and this was my first result. Experiencing the same problem and it's October 2023.

**Comment by heyryanw** [comment]
Same, but as others have noted, disabled GPU rendering and background work does help a bit.

**Comment by daveemu** [comment]
can confirm, please re-open

**Comment by coozoo** [comment]
exactly the same, I'm thinking why my laptop fan so mad, checked minimized steam and find out that the process over 1GB and  and all the time making something with cpu....

**Comment by kuzetsa** [comment]
> exactly the same, I'm thinking why my laptop fan so mad, checked minimized steam and find out that the process over 1GB and and all the time making something with cpu....

this is only happening for me with the new steam client for linux.

looks like an old, previously documented issue which got closed for some reason, and is back with the current version of the steam client for linux.

specifically:

```steamwebhelper is using more CPU than games or other system / background processes```

**Comment by fintonk** [comment]
I'm seeing this issue on my Steam Deck. I've tried a full factory reinstall but it's still happening. Only started a few days ago, it was fine until then.
Will be forced to return the Deck if it's not resolved.

**Comment by Kangaroux** [comment]
Still happening for me. Steam becomes unusable with the renderer maxing a single core and the window becoming unresponsive. Closing and relaunching the client doesn't fix the issue. Force killing the `steamwebhelper` process temporarily resolves the freezing (though CPU still sits at 30% when idling on the library screen).

![image](https://github.com/user-attachments/assets/bd0fad58-270e-4a34-959c-3320ed04ec33)
![image](https://github.com/user-attachments/assets/3bf26c1e-9f89-4df6-8940-75aa16736ade)

**Comment by alexzk1** [comment]
Still happens for me. 9% CPU usage when I left PC ON over night with minimized to tray steam, constant 80C degree heat because of this. Setting in OFFLINE relaxes to 0.8% CPU use.

**Comment by irfanhakim-as** [comment]
In my case on EndeavourOS (Arch Linux), CPU consumption of having Steam at the forefront vs closed to tray are exactly the same i.e. high, which drives up my CPU temps.

Having it minimised to dock (taskbar) reduces the CPU consumption to 0%.

**Comment by TorutheRedFox** [comment]
I am also facing the same issue on Windows 10, with steamwebhelper singlehandedly consuming 12-13% of the CPU

**Comment by jthistle** [comment]
I am experiencing this issue again. Getting 20% usage on Ubuntu 24.04.1 (i3wm on X11) with all Steam windows closed.

**Comment by BigC4** [comment]
Having the same issue: steam becomes unresponsive after idling minimized after a while, killing steamwebhelper makes steam responsive again. This wasn't a problem a month or so ago.

**Comment by adam-tj** [comment]
I am still having this issue. Steam is using too much CPU when it is idling. Running on openSUSE Leap 15.6

**Comment by CarpeNecopinum** [comment]
I also have this issue and I am a huge fan of the things Valve has done for Linux gaming, but honestly, it's a complete deal-breaker to me. I will not purchase anything from Steam until this issue is resolved, I'll rather use GOG or "other sources" than being unable to start my legally purchased games without losing 20% of my GPU to `steamwebhelper`.

**Comment by LethalManBoob** [comment]
this is still an issue ...

Although reopening from minimised seems to fix it.

**Comment by joshgiesbrecht** [comment]
honestly, it's ridiculous how much CPU this uses up even when it's in focus. why is this churning 100% of one CPU core just to display eg. a static game library page. it's a mess.

reopen - minimize again does seem to fix usage for me as well. (for now)

**Comment by alexzk1** [comment]
> honestly, it's ridiculous how much CPU this uses up even when it's in focus. why is this churning 100% of one CPU core just to display eg. a static game library page. it's a mess.
> 
> reopen - minimize again does seem to fix usage for me as well. (for now)

I have this setting, looks like ok with CPU (but I still quit it when not used, got a habit):

![Image](https://github.com/user-attachments/assets/66793465-e8f5-43c1-8c7a-838bca8fb678)

Also I enforce it to run on iGPU and banned access to detection of NVIDIA via /dev/ they do.
Games are launched via prime-run each.
I had to install `apparmor` just for steam, here it's file (change paths):
```
cat /etc/apparmor.d/steamwebhelper 

/home/alex/.local/share/Steam/ubuntu12_64/steamwebhelper {
    deny /dev/nvidia0 rw,
    deny /dev/nvidiactl rw,
    deny /dev/nvidia-modeset rw,
    deny /dev/nvidia-uvm rw,
    deny /dev/nvidia-uvm-tools rw,
    deny /dev/nvidia-caps/* rw,

    file,
    network,
    capability,
    signal peer=steam,
    signal peer=unconfined,
    signal peer=/home/alex/.local/share/Steam/ubuntu12_64/steamwebhelper,
}
```

**Comment by MehYam** [comment]
Still an issue on Ubuntu 24.04.2, steamwebhelper.exe in the background sits there and consumes 15-20% of a core, just enough to make my notebook run a fan.

There's no config setting, tool, or workaround worth putting thought into IMO, other than closing Steam when it's not in use.  

The other annoying piece of this is how that web control will contend for resources against the actual game you're playing.

**Comment by alexzk1** [comment]
@MehYam Check if app armor actually blocks it. I had `dmesg` spammed with until i disabled log of it. And steam looks ok, but I still exit it for the night.

**Comment by awsms** [comment]
this is still a thing lol. can't wait for https://github.com/OpenSteamClient/OpenSteamClient to be worked on again at some point

**Comment by logan1o1** [comment]
> steam steam://open/minigameslist -console -no-browser

Thanks dude this worked for me perfectly
