### ISSUE TITLE
Recent update introduced random stutter in Remote Play to Steam Link 

### ISSUE THREAD

**Issue by eligt** [ValveSoftware/steam-for-linux#8424]
#### Your system information

* Steam client version (build number or date): 18 Feb 2022
* Distribution (e.g. Ubuntu): Lubuntu 20.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
My Steam Link streaming setup was working perfectly up until 1-2 weeks ago when it started stuttering frequently (*many* times per hour) but randomly (sometimes no stutter for minutes, sometimes multiple stutters in a single minute).

I'm using a wired setup, everything is wired through fast CAT-7/8 cables. I used a wire tester to confirm there is no problem with the wires, also bought a new router and placed just my PC and steam link on the network with the same results. I've also tried setting the steam process to the highest priority.

None of the above attempts did anything to fix the issue. I've opted in/out of betas on both Steam and the Steam Link, with the same result.

The performance overlay details show <1ms (direct) and 0% packet loss/frame loss, but the graph shows peaks and stutters occur around those peaks:
![Screenshot](https://user-images.githubusercontent.com/2043211/154846101-27c073c4-c5df-4dc2-ab28-625617bd6e54.png)

The streaming_log.txt doesn't contain any errors or helpful messages, it's only lines like the following and nothing else:

```
[2022-02-20 12:28:01] CLIENT: Got control packet k_EStreamControlSetTitle
[2022-02-20 12:28:01] CLIENT: Got control packet k_EStreamControlSetIcon
[2022-02-20 12:28:01] SynchronizeClientState(): setting cursor to 212
[2022-02-20 12:28:01] CLIENT: Got control packet k_EStreamControlSetCursor
[2022-02-20 12:28:01] SynchronizeClientState(): setting cursor to 178
[2022-02-20 12:28:01] CLIENT: Got control packet k_EStreamControlSetCursor
[2022-02-20 12:28:01] SynchronizeClientState(): setting cursor to 62
[2022-02-20 12:28:02] CLIENT: Got control packet k_EStreamControlSetCursor
[2022-02-20 12:28:27] Window title set to Sublime Text - Sublime Text
[2022-02-20 12:28:27] Changing record window: 0x9200032
[2022-02-20 12:28:27] SynchronizeClientState(): setting title to [...]
```

**Comment by tnbp** [comment]
I am using the Steam Link App on Android TV and for me, too, a recent update has introduced random stutter to Remote Play.
I, too, am using Gigabit Ethernet everywhere, and I have tried replacing every part of my setup--host, client, and *all* cables and networking equipment--to no avail. Instead, downgrading to [Steam Link 1.1.87](https://www.apkmirror.com/apk/valve-corporation/steam-link-beta/steam-link-beta-1-1-87-release/) seems to have fixed the problem entirely. I am not sure if .88 or .89 introduced it.

**Comment by 77boaz** [comment]
I believe I'm having the same kinds of issues.  At the Linux box it's working fine but using the steam link  there seems to be major frame drops no matter the game.  I actually had this problem on the last steam beta so I had to switch to stable to fix it but now it seems it carried over to the stable release.

**Comment by tnbp** [comment]
> I believe I'm having the same kinds of issues. At the Linux box it's working fine but using the steam link there seems to be major frame drops no matter the game. I actually had this problem on the last steam beta so I had to switch to stable to fix it but now it seems it carried over to the stable release.

Have you tried using an older version of the Android app?

**Comment by eligt** [comment]
I personally reverted to an older version of the steam link hardware firmware, I think 729, and the stutter was a lot better: still present but a lot less frequent. Unfortunately, my new Bluetooth keyboard wasn't working well so I had to go back to the recent firmware.

**Comment by 77boaz** [comment]
I don't even know how to revert on the steam link.. It's either beta or public..

**Comment by 77boaz** [comment]
> 

For me I'm actually using the hardware steam link attached to the TV.. The old box :)

**Comment by Mohandevir** [comment]
Similar for me but it's a regular stutter like in every second or so. It's like if the stream was getting resynched. Jump back in time and then brought back to where it should be. Tried in-home streaming with Steam Link hardware and Steam Link Nvidia shield with a Pop_OS!, Kubuntu or ChimeraOS host.  The best experience was on the latter which gave me that "resync" phenomenon. Gnome and KDE stuttered all over the place (unplayable). 

On ChimeraOS, the overlay shows a solid 58.75fps and 15 to 30 ms streaming latency. 

On Pop-OS! and Kubuntu it shows 30 to 35fps and 70-85 ms stream latency.

The host is a ryzen 5 3600 coupled with a GTX 1600 super.

Thanks!

**Comment by Rippsblack** [comment]
having the same (i think) issue

**Comment by 77boaz** [comment]
> having the same (i think) issue
> 
> so opting out of the beta build steam client on my host PC fixed the problem, I also opted out of the beta builds for the hardware link.
> 
> I don't think hardware link beta software was the problem as it occurred when using factory defaults too.
> 
> I'm using windows10.

When I was in the beta build months back I first noticed this, and it was having the stutter issues.  I went back to the stable build at the time and the issues were resolved.  I believe whatever broke the beta at the time then moved onto the stable build because the issues returned even with the new stable build.  When I have some time, I will try once again the new stable builds on both the steamlink (hardware) and steam itself.  Maybe it has since been remedied in the stable build :)

**Comment by 77boaz** [comment]
So I switched to stable build and at it seems hit or miss with games.. some side scrollers such as Huntdown still seem jerky.  More graphic intense games such as Horizon Zero Dawn or Sekiro still seem to drop frames.  It's interesting because a few months back everything ran smoothly.  Anyways here's hoping for a fix.  Thanks Valve! :-)

**Comment by 77boaz** [comment]
I don't know what was released, but I had a recent update on the steam link.. and am running most recent steam beta build, and ALL of the lag is gone for me now.. it's like playing it from the PC now.. Smooth on the TV.. Thanks! whatever was done...

**Comment by eligt** [comment]
I can confirm the stutter (and performance icon popping for a second) **was** more or less gone, but has now come back as a few days maybe a week. Tested both 848 and 850 and getting stutter + performance icon every 2-3 minutes.

**Comment by tnbp** [comment]
This is still broken in *all* versions since 1.1.85, which was released 3.5 years ago.
