### ISSUE TITLE
Steam Glitches out after suspend after 12th update 

### ISSUE THREAD

**Issue by Redbatman89** [ValveSoftware/steam-for-linux#8584]
After suspend upon resume the store and client looks glitched out and can't be fixed unless I restart the application.

![Screenshot from 2022-05-13 19-25-53](https://user-images.githubusercontent.com/71661989/168402850-e77fdbde-5d51-411e-97d3-9288975a1ee5.png)

**Comment by Redbatman89** [comment]
I Updated to POP OS 22.04 and it still does it.

**Comment by RockafellaJaz** [comment]
I can confirm that this was happening to me in the Steam Beta so I had to switch back to the regular client. I'm Surprised it wasn't caught before they pushed out the updates.
I am on Manjaro Linux XFCE.

**Comment by nikolaos-spyratos** [comment]
I have this with a different look on Manjaro GNOME (pre-42 and now post-42)

![Screenshot from 2022-05-15 13-15-11](https://user-images.githubusercontent.com/17888779/168533910-46214254-424f-48d8-a629-047ea9bbba79.png)

![Screenshot from 2022-05-15 13-15-11](https://user-images.githubusercontent.com/17888779/168533900-d94ed801-adf2-4366-9825-6d65df71eca6.jpg)
.

**Comment by desht** [comment]
Also seeing this on Linux Mint 19.3, Nvidia 470.103.01-0ubuntu0.18.04.1 drivers, GTX 1660 card.  My Steam version reports "Built May 14 2022, at 00:03:20"

After resuming, image rendering in any Steam window (including friends list) is partially broken, and requires a Steam restart to work again.  I'd agree that this started after a recent update to Steam; it was working fine a couple of weeks ago.

**Comment by ivanpu** [comment]
Similar issue here, but in my case it's triggered by turning on/off the Steam Controller.
Each on/off causes the different pattern of the glitches, but most of the time the "store" and "community" sections are unusable once the issue was triggered.
Restart of the client fixes it temporary, until I turn on the controller again.
Started happening right after the latest steam client update.

Probably relevant specs:
ArchLinux, kernel 5.17.5
NVIDIA RTX 3070, official drivers 510.60.02
Steam client: May 14 2022, at 00:03:20, package 1652488014

**Comment by ivanpu** [comment]
The controller triggered glitching was fixed for me after today's client update: May 21 2022, at 02:23:45, package 1653101165

**Comment by sysms** [comment]
Experiencing the same glitch on Debian 11, using latest NVidia drivers and the latest steam stable client (28 May 2022). 

After I unlock my screen on LXDE using lxlock, it looks like this:

![steam_client_glitch](https://user-images.githubusercontent.com/4120422/172036351-ff43deb0-f223-4f9a-8c81-b4a9ee4196a1.png)


My system info: https://gist.github.com/sysms/ec35ee4ea1849b62a1189ed713aacc79

**Comment by rykugur** [comment]
Can also confirm. I snagged some logs, system info also attached [on this gist](https://gist.github.com/rykugur/830c9f445098be4acedce3f8dd61fa79).

![steam1](https://user-images.githubusercontent.com/2609898/172626306-39543d20-eece-4555-a647-83834d60cec2.png)
![steam2](https://user-images.githubusercontent.com/2609898/172626313-65bebae7-eaf4-475b-830b-4f3126958436.png)

**Comment by simonced** [comment]
Having same problems on Fedora 36 (gnome with X org).
Always happens after computer wakes up from sleep (desktop)

Neofetch:

```
            .',;::::;,'.                ced@fedora 
         .';:cccccccccccc:;,.            ---------- 
      .;cccccccccccccccccccccc;.         OS: Fedora Linux 36 (Workstation Edition) x86_64 
    .:cccccccccccccccccccccccccc:.       Host: XPS 8920 1.0.23 
  .;ccccccccccccc;.:dddl:.;ccccccc;.     Kernel: 5.17.11-300.fc36.x86_64 
 .:ccccccccccccc;OWMKOOXMWd;ccccccc:.    Uptime: 6 days, 13 hours, 31 mins 
.:ccccccccccccc;KMMc;cc;xMMc:ccccccc:.   Packages: 2313 (rpm), 4 (flatpak) 
,cccccccccccccc;MMM.;cc;;WW::cccccccc,   Shell: zsh 5.8.1 
:cccccccccccccc;MMM.;cccccccccccccccc:   Resolution: 2560x1080 
:ccccccc;oxOOOo;MMM0OOk.;cccccccccccc:   DE: GNOME 42.2 
cccccc:0MMKxdd:;MMMkddc.;cccccccccccc;   WM: Mutter 
ccccc:XM0';cccc;MMM.;cccccccccccccccc'   WM Theme: Adwaita 
ccccc;MMo;ccccc;MMW.;ccccccccccccccc;    Theme: Nordic [GTK2/3] 
ccccc;0MNc.ccc.xMMd:ccccccccccccccc;     Icons: Nordzy [GTK2/3] 
cccccc;dNMWXXXWM0::cccccccccccccc:,      Terminal: gnome-terminal 
cccccccc;.:odl:.;cccccccccccccc:,.       CPU: Intel i7-7700 (8) @ 4.200GHz 
:cccccccccccccccccccccccccccc:'.         GPU: NVIDIA GeForce GTX 1650 
.:cccccccccccccccccccccc:;,..            GPU: Intel HD Graphics 630 
  '::cccccccccccccc::;,.                 Memory: 5035MiB / 23938MiB
```

Also a screen shot of the main shop screen attached
![Screenshot from 2022-06-12 12-57-27](https://user-images.githubusercontent.com/5772359/173213798-a2c6b564-9894-4f20-aac2-047a8975c8da.png)

Issue happens on roll overs usually, but sometimes the window is empty.
I have to resize the window to see some content.

Really weird...

**Comment by RockafellaJaz** [comment]
I have resorted to running `pkill steamwebhelper` when I resume from suspend.
Once steamwebhelper auto restarts everything works again.
It leaves an extra blank window titled 'about:blank' but selecting it then Alt+F4 removes it.

**Comment by Ryder17z** [comment]
> I have this with a different look on Manjaro GNOME (pre-42 and now post-42). Both native and runtime versions. I'm not on the beta client.

It's the same on Manjaro XFCE.

**Comment by rado84-github** [comment]
> > Replying to [#8584 (comment)](https://github.com/ValveSoftware/steam-for-linux/issues/8584#issuecomment-1127282338)
> 
> Could you tell me your Nvidia Card and driver too. I have a GTX 1080 with driver version 470.103.01
> 
> I'm wondering if there is a possible driver connection too.

That's a beta driver you mentioned. I'm on a stable NVIDIA driver (currently 515.76) and it's still happening. The driver itself seems to be waking up just fine after suspend, otherwise I'd be having a black screen instead of a desktop, which is why I have my doubts about the driver being connected to the issue.

**Comment by meixiexun** [comment]
this is happening to me on pop 22.04 with the 515.65.01 driver. for testing, I tried both flatpak and .deb installation and get the same behavior.

**Comment by RockafellaJaz** [comment]
I just found that disabling 'GPU accelerated rendering' under Interface in the Settings seems to be a workaround for me.

I am using the current beta client.

**Comment by corvusd** [comment]
This issue still here.

**Comment by rado84-github** [comment]
> 

I've disabled that as well and now it's working fine. Looks like it's an Xorg problem, not a Steam problem.

**Comment by corvusd** [comment]
In last beta update the issue was fixed!! :)

**Comment by RockafellaJaz** [comment]
Yep. Tested with GPU accelerated rendering on and everything seems to be working properly for me now.

**Comment by sysms** [comment]
The latest stable client (as of 17.03.23) also fixes this for me.

Too bad, that it has other issues (like eg. https://github.com/ValveSoftware/steam-for-linux/issues/9273).

**Comment by sysms** [comment]
Too bad - I spoke to soon. :( Still having this problem with latest stable steam client.

![steamclient_tosoon](https://user-images.githubusercontent.com/4120422/226424943-687b7c54-f1ab-43d0-91ff-1b391e2bd6cb.png)
![steamclient170323](https://user-images.githubusercontent.com/4120422/226425237-194b2deb-5647-427d-a11e-40640fedb35d.png)

**Comment by corvusd** [comment]
Yes, me too. It is like the in the next beta update it broken again. But now sometimes work well, another no... strange.

**Comment by RockafellaJaz** [comment]
Yep, seems to have broken again for me in Beta Client (Mar 18 2023). Disabling GPU accelerated rendering fixed it again. Guess I will just have to leave it turned off.

**Comment by howels** [comment]
My library is blank and disabling GPU acceleration doesn't seem to help.
March 18 22:30:17 build

Store page is a blank white screen

**Comment by RockafellaJaz** [comment]
@howels I have the white issue in my Store Page also when I resume from suspend but if I resize the window the white disappears and everything is displayed correctly.

**Comment by rado84-github** [comment]
The problem seems to be fixed for me, so yours are probably special cases.
