### ISSUE TITLE
after update steam client to version 1676680477 scaling being broken on pages (game library and chat)

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/steam-for-linux#9209]
#### Your system information

* Steam client version (build number or date): 1676680477
* Distribution (e.g. Ubuntu): Fedora Rawhide
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
![Screenshot from 2023-02-18 12-25-49](https://user-images.githubusercontent.com/200750/219847730-2c1ae85c-4ab7-46c8-9cfb-f6b4926b2145.png)
![Screenshot from 2023-02-18 12-26-06](https://user-images.githubusercontent.com/200750/219847733-84c9a76f-bfda-42a3-9491-a3dedfe35643.png)

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by CoelacanthusHex** [comment]
An Off-topic question: How do you downgrade steam to the previous beta version?

**Comment by cprn** [comment]
Same issue on up-to-date Manjaro with updated Steam client and beta opt-in (NVIDIA proprietary driver). Can't read game titles in 4K without scaling and with Deck UI running at about 3fps it's very cumbersome to start a game.

Workarounds:

1. opting out of beta fixes the main window scaling (Deck UI is still a slideshow)
2. alt+enter starts good-old Big Picture mode that works flawlessly (for now)

**Comment by TheGhostHybrid** [comment]
Chiming in to say I have the same issue. The window is fine, but the content within the viewport no longer scales properly. In addition, I have this issue that happens whenever I view a non-Library page:
![image](https://user-images.githubusercontent.com/5500727/221316799-74c3062c-e3a2-45a9-93d6-63f73c8b73df.png)
It seems to resolve itself when I close the window and re-open from the system tray. However, when freshly started, the issue comes back.

**Comment by Anarch157a** [comment]
> Chiming in to say I have the same issue. The window is fine, but the content within the viewport no longer scales properly. In addition, I have this issue that happens whenever I view a non-Library page: (...) It seems to resolve itself when I close the window and re-open from the system tray. However, when freshly started, the issue comes back.

I have this issue too, I don't need to close the window and re-open from the tray icon, changing the page to Library, then back to the previous one makes it render properly. This is much quicker than re-opening

**Comment by NTMan** [comment]
version 1678845529 fixes scaling in library, but scaling still not working in game properties and steam library folders

![Screenshot from 2023-03-15 10-21-22](https://user-images.githubusercontent.com/200750/225216550-a051c318-dc8a-457e-ba0f-cd25fa95c84b.png)

**Comment by frikisama** [comment]
Is it just me, or does the newly enabled scaling look like actual high DPI rendering instead of simple 2x scaling? It looks very crisp now, where it was a bit blurry before, IIRC.

Thanks to whoever was involved! :)

**Comment by Lastique** [comment]
@kisak-valve Is there a workaround? The game properties window is barely readable.

**Comment by friedc** [comment]
> scaling still not working in "game properties" and "steam library folders"

> Also scaling didn't work in windows "big picture configuration", "desktop configuration" and "guide button chord configuration"

I can confirm that for me the mentioned windows are also too small (not scaled to 2x size). I do not participate in the Beta.

```
About Steam

Steam client application:
Built: Mar 24 2023, at 17:20:43
Steam API: v020
Steam package versions: 1679680416
```

**Comment by NTMan** [comment]
And again scaling is broken since 1679950905 version.
Is it really not one developer at Valve not having 4K monitor with scaling?

![Screenshot from 2023-03-28 12-07-16](https://user-images.githubusercontent.com/200750/228155896-7495be2a-d695-4bcc-ba83-0e991edd6996.png)

**Comment by yhojann-cl** [comment]
This problem has not been assigned to anyone for more than two months. Is there any news?, this problem also happens in the latest stable version 1679680416

**Comment by Grauiton** [comment]
FYI for Valve:

GTK4 dropped usage of `GDK_DPI_SCALE`.

KDE Plasma followed this by dropping the use of `GDK_SCALE` / `GDK_DPI_SCALE` starting with Plasma version 5.27. KDE Plasma instead recommends using `xsettingsd` to communicate scaling settings to GTK applications in X11 sessions.

**Comment by arazilsongweaver** [comment]
Wayland DPI scaling is completely broken as of the "big" Steam beta update released on 2023-04-27. Everything appears very tiny on a 4K screen and it is extremely difficult to use.

Example screenshot from the 2023-04-27 update:

![image](https://user-images.githubusercontent.com/4644619/235007432-a4837cc0-b5a2-4f61-bf37-28c38a06588e.png)

**Comment by NTMan** [comment]
With update 1682634349 in addition to library broken scaling on store pages.

![image](https://user-images.githubusercontent.com/200750/235012224-0397595e-f204-42f4-b955-f5fb554a79d5.png)

**Comment by TheGhostHybrid** [comment]
The Steam window over top of a properly-scaled window (Quod Libet) to show the stark scaling difference.
![image](https://user-images.githubusercontent.com/5500727/235015113-7d1fd2ac-c43a-4029-ad6b-d0f1afa3efa5.png)

**Comment by anyoneyun** [comment]
Same issue here on Manjaro KDE, it has been a problem for months now, as a comment stated earlier, kde changed the way scaling works and now it doesn't use GDK scale anymore. This has been true since kde 5.27

**Comment by Grauiton** [comment]
The solution for Valve is really simple:

1. Stop using the `GDK_SCALE` environment variable.
2. Instead, use the value for `Gdk/WindowScalingFactor` in `~/.config/xsettingsd/xsettingsd.conf`.

That's it.

**Comment by yhojann-cl** [comment]
Why not use the same window to render all the others instead of doing it separately? In this way the scaling would depend on a single window instead of fighting with the rest. For example, I use two monitors and when a window opens like the update window, news, launcher, etc., they open on a different monitor than the one where steam is running. They could solve all those problems including the scaling thing if they integrated all the other windows inside of steam and not outside of it.

**Comment by Bananaman** [comment]
What is this? A GUI for ANTS?!

# :ant:

Tried the latest beta today. Totally unusable. Switched back immediately.

**Comment by NTMan** [comment]
I just install update 1683314987 which promised in change logs "Re-introduced GDK_SCALE as a fallback mechanism to compute the window scaling factor."
But the miracle didn't happen. End result you can see on screen below:
![Screenshot from 2023-05-06 03-00-54](https://user-images.githubusercontent.com/200750/236576254-57f3d07c-0e9b-419d-8185-661e6b583133.png)

**Comment by dafzor** [comment]
The scaling is working again, however newer desktop environments no longer set `GDK_SCALE`.

You need to launch steam with something like this `GDK_SCALE=2 /usr/bin/steam`

**Comment by oldkentuckymark** [comment]
Please, for the love of God, stop implementing command line switches and and requiring users pollute thier app shortcuts menus and environments with debug variables for toolkits you don't even use, and give us a simple slider inside the app to change the scaling. This is all we need.

**Comment by dafzor** [comment]
When using `GTK_SCALE=2` the window can only be dragged by using the top left of the window.

Right side, bottom of the window will not allow dragging. In the areas dragging still works it's inconsistent not working 100% of the time.

**Comment by Bananaman** [comment]
> But the miracle didn't happen. End result you can see on screen below:

Because they're using the wrong variable.

Here's a ticket about it:

https://github.com/ValveSoftware/steam-for-linux/issues/9466

**Comment by lionking102** [comment]
Steam really needs fractional scaling support and that wasn't working before the beta as well (I'm not talking about integer scaling, 1x, 2x etc, but about 150%)...
It was maybe fine for people with 4k Monitors, but everyone that uses WQHD or has bad eyes (as me) never had a chance to use steam well under linux. 
On Gnome you had it scaling blurry, but on KDE with "Apps scale by themself" (which is the only great experience for linux scaling right now) it is not even possible to have a blurry UI, people streight up can't read it and can do nothing about it, because steam doesn't support fractional scaling. By that point steam should at least support X11 fractional scaling or add real wayland support.

**Comment by GrzegorzKozub** [comment]
My `text-scaling-factor` is set but Steam seems to ignore it. 

<img width="361" alt="image" src="https://user-images.githubusercontent.com/154056/236660047-348aeaa3-e005-4a96-806f-bf844c06b226.png">

When I use either `GDK_SCALE` or `-forcedesktopscaling`, Steam core-dumps (crashes) with the following:

```
> GDK_SCALE=2 /usr/bin/steam
steam.sh[29015]: Running Steam on arch rolling 64-bit
steam.sh[29015]: STEAM_RUNTIME is enabled automatically
setup.sh[29089]: Steam runtime environment up-to-date!
steam.sh[29015]: Steam client's requirements are satisfied
[2023-05-07 07:43:17] Startup - updater built May  5 2023 18:02:32
[2023-05-07 07:43:17] Startup - Steam Client launched with: '/run/media/greg/games/Steam/ubuntu12_32/steam'
[2023-05-07 07:43:17] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
05/07 07:43:17 Init: Installing breakpad exception handler for appid(steam)/version(1683314987)/tid(29146)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2023-05-07 07:43:17] Loading cached metrics from disk (/run/media/greg/games/Steam/package/steam_client_metrics.bin)
[2023-05-07 07:43:17] Using the following download hosts for Public, Realm steamglobal
[2023-05-07 07:43:17] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2023-05-07 07:43:17] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2023-05-07 07:43:17] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-05-07 07:43:17] Checking for update on startup
[2023-05-07 07:43:17] Checking for available updates...
[2023-05-07 07:43:17] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_publicbeta_ubuntu12
[2023-05-07 07:43:17] Manifest download: send request
[2023-05-07 07:43:17] Manifest download: waiting for download to finish
[2023-05-07 07:43:18] Manifest download: finished
[2023-05-07 07:43:18] Download skipped: /steam_client_publicbeta_ubuntu12 version 1683314987, installed version 1683314987, existing pending version 0
[2023-05-07 07:43:18] Nothing to do
[2023-05-07 07:43:18] Verifying installation...
[2023-05-07 07:43:18] Performing checksum verification of executable files
[2023-05-07 07:43:18] Verification complete
Loaded SDL version 3.0.0-1471-gb6ca36022
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf29d6db0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf29d5500
GetWin32Stats: display was not open yet, good
steamwebhelper.sh[29284]: Runtime for steamwebhelper: defaulting to /run/media/greg/games/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[29284]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
Could not connect to X session manager: None of the authentication protocols specified are supported
CAppInfoCacheReadFromDiskThread took 63 milliseconds to initialize
Failed to init SteamVR because it isn't installed

(steam:29146): Gtk-WARNING **: 07:43:19.001: gtk_disable_setlocale() must be called before gtk_init()
local (potentially out of sync) copy of roaming config loaded - 1498 bytes.
src/vstdlib/coroutine.cpp (817) : GCoroutineMgr().IsValidCoroutine(hCoroutine)
src/vstdlib/coroutine.cpp (817) : GCoroutineMgr().IsValidCoroutine(hCoroutine)
05/07 07:43:28 Init: Installing breakpad exception handler for appid(steam)/version(1683314987)/tid(29146)
assert_20230507074328_28.dmp[29893]: Uploading dump (out-of-process)
/tmp/dumps/assert_20230507074328_28.dmp
crash_20230507074328_29.dmp[29897]: Uploading dump (out-of-process)
/tmp/dumps/crash_20230507074328_29.dmp
/run/media/greg/games/Steam/steam.sh: line 798: 29146 Segmentation fault      (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20230507074328_28.dmp[29893]: Finished uploading minidump (out-of-process): success = yes
assert_20230507074328_28.dmp[29893]: response: CrashID=bp-9594c616-305a-435d-9c99-114542230506
assert_20230507074328_28.dmp[29893]: file ''/tmp/dumps/assert_20230507074328_28.dmp'', upload yes: ''CrashID=bp-9594c616-305a-435d-9c99-114542230506''
crash_20230507074328_29.dmp[29897]: Finished uploading minidump (out-of-process): success = yes
crash_20230507074328_29.dmp[29897]: response: CrashID=bp-30c045e0-cf95-48f6-a06e-b53752230506
crash_20230507074328_29.dmp[29897]: file ''/tmp/dumps/crash_20230507074328_29.dmp'', upload yes: ''CrashID=bp-30c045e0-cf95-48f
```

I'm on Gnome 43 under Xorg.

**Comment by NTMan** [comment]
Just rechecked for my system (gnome 44.1) only `~/.config/monitors.xml` has matter.

```
❯ cat ~/.config/monitors.xml
<monitors version="2">
  <configuration>
    <logicalmonitor>
      <x>0</x>
      <y>0</y>
      <scale>2</scale>
      <primary>yes</primary>
      <monitor>
        <monitorspec>
          <connector>DP-3</connector>
          <vendor>PHL</vendor>
          <product>PHL 436M6VBP</product>
          <serial>0x000018d4</serial>
        </monitorspec>
        <mode>
          <width>3840</width>
          <height>2160</height>
          <rate>59.997</rate>
        </mode>
      </monitor>
    </logicalmonitor>
  </configuration>
</monitors>
❯ gsettings get org.gnome.desktop.interface text-scaling-factor
1.0
❯ gsettings get org.gnome.desktop.interface scaling-factor
uint32 0
```

**Comment by puxplaying** [comment]
Steam beta update 1683859267:
> Linux
> Dynamically update the UI's scaling factor when the system scaling setting changes.

- Scaling is back to a broken state on X11 Gnome for me and  `GTK_SCALE=2` does not work any more.

**Comment by ReillyBrogan** [comment]
Yeah is this working for anyone now? It was working on Plasma 5.27 Wayland by using `GDK_SCALE=2` but it was broken by the update that @puxplaying mentioned and hasn't worked since. I've tried removing the env variable in case it was conflicting somehow but removing it didn't help. `-forcedesktopscaling=2.0` does work but that seems like a poor solution especially considering that I have a different scaling factor set when I'm connected to my big 4k screen vs when that display is off.

**Comment by dafzor** [comment]
@ReillyBrogan I have scaling visually working with `-forcedesktopscaling 2 %U` on my shortcut, however with forced scaling it breaks in other ways, such as not being able to drag the window from most places.

Usable but occasionality annoying.

**Comment by ar-lex** [comment]
I am also using Plasma 5.27 Wayland and it seems that I now have worked around all HiDPI issues that I had with Steam beta. 

@dafzor only having both  `-forcedesktopscaling`  and `GDK_SCALE` fixes the window drag issue that you mentioned.

@ReillyBrogan I created [the wrapper script](https://gist.github.com/ar-lex/bb9dabdda4ebe8a376d2e1e2b754dd2f) to run Steam with correct scaling on different monitors. It can be placed in any directory of `$PATH` variable such as `$HOME/.local/bin` (without `.sh` extension). I only had to remove `/usr/bin/` from `Exec=` line of `steam.desktop`.

This wrapper uses `wayland-info` command to set the highest scaling factor of all enabled monitors, which KWin expects to have for Xwayland application such as Steam, scaling it down for monitors with lower DPI. For example, when I connect my 100% scale monitor to my laptop with HiDPI display and enable both of them, I always get correct scaling for Steam window.

The downsides:
- Incorrect scaling after disabling HiDPI output. Looks like it can't be fixed without having native Wayland Steam client.
- No fractional scaling. Steam seems to support it, but `wayland-info` only shows integer scaling factors. Didn't find any other simple utility that can report fractional scaling factors.

**Comment by dafzor** [comment]
@ar-lex tried setting both environment var and argument at the same time with no change in behaviour.

Only the part above the community and username options are draggable and sometimes doesn't register drag events with the switches.

**Comment by yhojann-cl** [comment]
Now in the last update you can see all the small windows, now none have scale, everything is already broken!

**Comment by arazilsongweaver** [comment]
The broken (KDE Plasma) Wayland scaling has made its way to the stable branch. All text on my 4K system is now extremely tiny. KDE Plasma is set to 200% scaling on both 4K monitors and 100% scaling on the one 1080P screen that mirrors one of the 4K monitors. I am not using any Steam command line parameters or other environmental trickery. Steam Version: 1686779606

**Comment by Mangoes** [comment]
Same problem here.

With the new stable update, Steam is now completely UNUSABLE due to the tiny ui in 4k (on x11 & wayland, kde 5.27). I use 150% scaling.

So they have released this completely broken without even testing it on kde 5.27 ?

Is there anyway to go back to the previous stable version, or do we have to understand that we just can't use Steam anymore?

**Comment by ro-kue** [comment]
I changed my Desktop file from Exec=sh -c 'GDK_SCALE=2 /usr/bin/steam %U' to Exec=sh -c '/usr/bin/steam -forcedesktopscaling=1.5 %U' and it works flawlessly. Not even blurry. I had to mess with the Desktop file before as well so this is still an improvement for me since now fractional scaling works.

HiDPI is a mess in Linux.

I'm on KDE and Wayland with Fedora.

**Comment by Sunspark-007** [comment]
Text scaling on latest update in the desktop mode client remains broken on the Steam Deck.

Surprised to see some of you say text rendering was correct in the past. It has never been correct here. Always tiny. Windows scales properly.

I'm honestly surprised by this. Is it really that hard to just query "xrdb -query | grep dpi" to see what the logical dpi is set for, e.g. 144, and simply scale based on that result returned? 96 is 100%, 144 is 150%, 192 is 200%, etc.

**Comment by akdean** [comment]
The `-forcedesktopscaling` entry works on the main UI for me, but makes the overlay comically large and unusable, which is a shame because I really like the new notes feature.

**Comment by Amic72** [comment]
https://steamcommunity.com/discussions/forum/0/6516193260165168475/

**Comment by oldkentuckymark** [comment]
New update, here we go again.
Valve, stop this insanity. You keep getting this wrong. Please stop trying.
Environment variables are wrong. GDK_SCALE triply so, being a debug variable that non GTK apps have no business reading, and is no longer set by desktop enviroments.

Command line arguments are wrong, stop doing this, your application should work out of the box for God's sake.

And if you do Insist on trying to figure out a scaling factor from the system some other way (which you WILL get wrong) you MUST round UP, as being too large but readable is strictly and objectively better and more correct than being too small. If the scale factor is 1.00001, and you insist on making an application in 2023 that does not do fractional scaling, you must scale 2x, or thing will by definition, be too small.

But stop this. Just stop it.

Give us a slider IN THE APP, to set the scale manually. That is all anyone has ever wanted or asked for.
We never wanted you to read our environment variables, or force us to manually edit .desktop files. We never wanted to be forced to launch steam from the command line.

WE. JUST. WANT. A. SLIDER. IN. THE. APP.

**Comment by tesfabpel** [comment]
> Give us a slider IN THE APP, to set the scale manually. That is all anyone has ever wanted or asked for. We never wanted you to read our environment variables, or force us to manually edit .desktop files. We never wanted to be forced to launch steam from the command line.

Technically, reading the env variable is wrong but having a slider is also not completely correct (but better): it won't work with multiple screens that have different DPIs. I believe only on Wayland this scenario can be supported, though...

Anyway, with the latest stable version (I'm on stable) it also happens to me on:
* my main PC: ArchLinux, GNOME / Wayland / AMDGPU 
* my other PC: Fedora 38, KDE / Wayland / AMDGPU

**Comment by NTMan** [comment]
It was enough just copy-paste ready solution from the Chromium browser codebase. It works in all desktop environments and dynamically and support changing scaling on the fly when changes DE setting.

**Comment by Lastique** [comment]
The UI is completely broken now. @kisak-valve Please revert this update until the UI is fixed. The current version is unusable.

**Comment by cprn** [comment]
> The UI is completely broken now.

@Lastique What are you talking about? Stop whining, the UI works fine. There are workarounds for scaling described in this thread. If you're too lazy to read it just open `/usr/bin/steam` as `root` and change the `exec` line to the one below, then save and restart Steam as usual:

```sh
exec /usr/lib/steam/steam -forcedesktopscaling 2 "$@"
```

**Comment by nekonosukeno** [comment]
Just wanted to point out that -forcedesktopscaling should only be a temporary workaround because it still fails to properly display some elements of the UI such as the log in prompts. The image attached is not cutoff, this is actually the whole window.
![Steam_login](https://github.com/ValveSoftware/steam-for-linux/assets/106162468/4a9bc0d3-39dc-4aed-a8bf-f273957f2d0d)

**Comment by Lastique** [comment]
> add `-forcedesktopscaling 2` as showed below

This breaks all notifications and popup windows - the text no longer fits in windows and is unreadable.

This isn't me whining, this is a valid user complaint. The UI is unusable for me, and apparently for many other users. If you think this is fine then stop posting in this thread - you're not helping by offending other users.

**Comment by cprn** [comment]
@Lastique Again, what are you talking about? Steam client run in 4K with `-forcedesktopscaling 2`:

* games library: 
![2023-06-15-173325_3840x2160_escrotum](https://github.com/ValveSoftware/steam-for-linux/assets/6132708/383943c2-e762-45c3-9e25-f77d563112fc)

* various windows:
![2023-06-15-173223_3840x2160_escrotum](https://github.com/ValveSoftware/steam-for-linux/assets/6132708/b949f05c-f9b5-41cf-b46e-87d895ff2ff4)

What's unusable? AFAIK the only window that's broken is login prompt as mentioned by @nekonosukeno

**Comment by Lastique** [comment]
@cprn Besides the login window, Friends & Chat window is also cropped. As well as error popup windows such as this:

![Screenshot_20230615_184548](https://github.com/ValveSoftware/steam-for-linux/assets/1589747/9438dfc4-b806-4b91-ac94-895aebf79d42)

That's Steam telling me of an error during uninstallation, something I reported in a separate bug. Note that the button to close the window is completely off the visible area. Then there are notifications that appear in bottom right corner of the screen - those are also not readable. I don't have time or will to test other places of the UI, maybe there's more.

My main point is I should not have to work around broken Steam UI. The current state of the UI is unacceptable. Valve should test it themselves before releasing to public. For god's sake, the UI scaling bug is on the surface, visible *immediately* as you start the client. Which means they probably didn't even start it.

**Comment by cprn** [comment]
@Lastique I added more screenshots - store, menus, chat window, uninstall prompt (don't know how to get that error, I have no option to uninstall Proton 8 but I'm pretty sure it'd work fine as well). I didn't happen to get any notifications while taking screenshots but notifications work for me as well - I'll add to that post if I happen to catch one.

IDK what's going on at your end but it looks to me like you've got scaling set twice. If I were you, I'd try to run Steam with `-forcedesktopscaling 2` on a clean user account before changing any other setting regarding DPI in your environment, window manager, etc.

**Comment by gtsiam** [comment]
@cprn 
> I'm pretty sure Valve tests Steam on dozens of Linux machines and in various resolutions before releasing both beta and final client version.

Given that this issue exists, They either don't test HiDPI at all or they just didn't think it was a high enough priority for some reason.

@spacemanspliff024 
> I just ran into this issue today, kde plasma scaling broken.

Please refrain from commenting "me too" on issue threads. It makes it more difficult for people to filter through the useful information on the thread. Instead, Click on the "Subscribe" button on the right if you're interested in receiving updates.

@kisak-valve 
I'm gonna do the unthinkable, and bug the maintainer (?). This should probably be high priority now, or at least on the radar. Is anyone even looking into this?

---

For everyone else, you can launch steam with `steam -forcedesktopscaling=2` (make sure to `killall steam` first). This seems to work for most of us.

**Comment by heftig** [comment]
Just got a beta update that fixed the scaling for me on GNOME 44 Wayland.

**Comment by 914the914** [comment]
![image](https://github.com/ValveSoftware/steam-for-linux/assets/136795559/b64da32d-534a-4366-8ce8-973942123ba7)
I have no idea why people are complaining about "smallness," but the UI is way too big on my end. Please reduce it to 50% or at least provide an option to reduce it to 50%. Steam is just throwing huge text in my fucking face.

Gnome Wayland AMD GPU

**Comment by sillyotter** [comment]
For those interested, [phoronix](https://www.phoronix.com/news/Steam-Force-Desktop-UI-Scaling) pointed out this morning that in addition to the `-forcedesktopscaling=2.0`command line option, there is a new `STEAM_FORCE_DESKTOPUI_SCALING=2.0` environment variable that can set this as well.

**Comment by oldkentuckymark** [comment]
Another client update, another miserible  failure on Valve's part.

Dear Valve, if you spent half as much time implementing a selectable scaling option in the application itself, as you do closing bug reports about scaling being broken, there would be no more bug reports.

This is not a feature request, this is an accessibility issue.
Having to pass arcane command line arguments, or polluting your environment with bespoke variables is not an acceptable solution for Americans with disabilities to access your store. These accommodations must be accessible inside the store (aka the application itself)

Please just add a slider to force scaling in the app so people can actually see (and maybe spend money).

**Comment by arazilsongweaver** [comment]
The new beta update (Steam Version: 1686880776) did not fix the issue on KDE Wayland with 2X scaling. The command line workaround was verified to still be functional.

**Comment by 914the914** [comment]
"STEAM_FORCE_DESKTOPUI_SCALING=2.0" or "STEAM_FORCE_DESKTOPUI_SCALING=0.5" changed nothing for me.  the UI is still way too big on my side.

**Comment by Saroumane** [comment]
@nekonosukeno @914the914 
`-forcedesktopscaling 2`  still working here, even if it does not solve all UI problems. (**without** `=` )

**Comment by 914the914** [comment]
> -forcedesktopscaling

None of `-forcedesktopscaling 0.5` or `-forcedesktopscaling 2` works for me, still massive UI

**Comment by yhojann-cl** [comment]
The issue is solved on Gnome for Steam client 1686880776. Tested on Ubuntu 22.04 LTS.

**Comment by cprn** [comment]
> None of `-forcedesktopscaling 0.5` or `-forcedesktopscaling 2` works for me (they has exactly same size), still massive UI.

Try `-forcedesktopscaling 1`. The current issue is Steam client sees 4K resolution and applies 2x scale factor regardless of any other settings so in your case you want to force a 1x scale factor.

**Comment by 914the914** [comment]
> > None of `-forcedesktopscaling 0.5` or `-forcedesktopscaling 2` works for me (they has exactly same size), still massive UI.
> 
> @914the914 Try `-forcedesktopscaling 1`. The current issue is Steam client sees 4K resolution and applies 2x scale factor regardless of any other settings so in your case you want to force a 1x scale factor.

This works. Thank you. Finally my eyes saved

**Comment by emko** [comment]
> Just updated to the June 21st update and functionality has actually regressed further. Now dropdown menus are improperly scaled, meaning most of the options are completely inaccessible. ![Screenshot depicting improperly scaled menus](https://user-images.githubusercontent.com/23667741/248132116-5ce50809-65d2-4370-a67d-4f4bcb6c3a5f.png) I haven't changed any settings before or since applying this patch, meaning this behavior occurs with automatic scaling _disabled_ and no scaling override options set! Really hoping this gets fixed soon.

yes same, any idea where the flatpak saves the settings ? i had mine checked to use system scaling and i thought that was causing the large UI but now i can't get into settings to turn it back on

**Comment by debevv** [comment]
> Just updated to the June 21st update and functionality has actually regressed further. Now dropdown menus are improperly scaled, meaning most of the options are completely inaccessible. ![Screenshot depicting improperly scaled menus](https://user-images.githubusercontent.com/23667741/248132116-5ce50809-65d2-4370-a67d-4f4bcb6c3a5f.png) I haven't changed any settings before or since applying this patch, meaning this behavior occurs with automatic scaling _disabled_ and no scaling override options set! Really hoping this gets fixed soon.

I have this problem too. I don't use monitor scaling (set to 100%) but this happens also with the "Scaling factor" option in the "Fonts" tab of gnome-tweaks set to 1.25.  
`-forcedesktopscaling 1` works but then content becomes too small.

My system:
Ubuntu 22.04
Steam 1687386907
Default gnome-shell desktop on Xorg
NVIDIA 2080 TI with nvidia-driver-530
4K monitor

**Comment by jarrard** [comment]
> Just updated to the June 21st update and functionality has actually regressed further. Now dropdown menus are improperly scaled, meaning most of the options are completely inaccessible. ![Screenshot depicting improperly scaled menus](https://user-images.githubusercontent.com/23667741/248132116-5ce50809-65d2-4370-a67d-4f4bcb6c3a5f.png) I haven't changed any settings before or since applying this patch, meaning this behavior occurs with automatic scaling _disabled_ and no scaling override options set! Really hoping this gets fixed soon.

Yeah this is a issue for me under XFCE that I'm now using.

**Comment by dafzor** [comment]
Latest version fixes drag area bug and overlay scaling bug. Still need `STEAM_FORCE_DESKTOPUI_SCALING=2.0` however else scaling is not respected.

**Comment by ShenMian** [comment]
Same issue with 2K resolution monitor.

**Comment by Fancy2209** [comment]
For me setting on Fedora KDE under Wayland, to fix it go to the screen options and set "Old Apps (X11)" to System Defined Scale

**Comment by DonQuiProgger** [comment]
For everyone experiencing the same issue on flatpak + 4k monitor can use the following command:

`flatpak override --env=STEAM_FORCE_DESKTOPUI_SCALING=2.0 com.valvesoftware.Steam`

**Comment by dafzor** [comment]
While forcing the scaling mostly works when leaving Big Picture mode the scaling gets applied again, so 2.0 seems to become 4.0.

**Comment by MartinVonReichenberg** [comment]
Confirming it here too:
Seems like Ubuntu and Arch Linux are not aware of **fractional** (150%) **scaling** on X-org **X11** GNOME session:
On SUSE it works _out-of-the-box_.

```
martin@Kingston-USB-Flash-Drive--Ubuntu-23-10 ~> inxi -F
System:
  Host: Kingston-USB-Flash-Drive--Ubuntu-23-10 Kernel: 6.5.0-9-generic
    arch: x86_64 bits: 64 Desktop: GNOME v: 45.0 Distro: Ubuntu 23.10 (Mantic
    Minotaur)
Machine:
  Type: Laptop System: LENOVO product: 82JQ v: Legion 5 Pro 16ACH6H
    serial: <superuser required>
  Mobo: LENOVO model: LNVNB161216 v: NO DPK serial: <superuser required>
    UEFI: LENOVO v: GKCN60WW date: 03/07/2023
Battery:
  ID-1: BAT0 charge: 83.7 Wh (100.0%) condition: 83.7/80.0 Wh (104.6%)
CPU:
  Info: 6-core model: AMD Ryzen 5 5600H with Radeon Graphics bits: 64
    type: MT MCP cache: L2: 3 MiB
  Speed (MHz): avg: 1881 min/max: 400/4280 cores: 1: 2716 2: 2633 3: 2229
    4: 400 5: 2205 6: 2516 7: 2128 8: 400 9: 400 10: 2396 11: 2530 12: 2020
Graphics:
  Device-1: NVIDIA GA106M [GeForce RTX 3060 Mobile / Max-Q] driver: nvidia
    v: 535.113.01
  Display: x11 server: X.Org v: 1.21.1.7 with: Xwayland v: 23.2.0 driver: X:
    loaded: nvidia unloaded: fbdev,modesetting,nouveau,vesa
    gpu: nvidia,nvidia-nvswitch resolution: 3408x2130
  API: OpenGL v: 4.6.0 NVIDIA 535.113.01 renderer: NVIDIA GeForce RTX 3060
    Laptop GPU/PCIe/SSE2
Audio:
  Device-1: NVIDIA GA106 High Definition Audio driver: snd_hda_intel
  Device-2: AMD ACP/ACP3X/ACP6x Audio Coprocessor driver: N/A
  Device-3: AMD Family 17h/19h HD Audio driver: snd_hda_intel
  API: ALSA v: k6.5.0-9-generic status: kernel-api
  Server-1: PipeWire v: 0.3.79 status: active
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
    driver: r8169
  IF: eno1 state: up speed: 1000 Mbps duplex: full mac: 9c:2d:cd:c9:f6:9b
  Device-2: MEDIATEK MT7921 802.11ax PCI Express Wireless Network Adapter
    driver: mt7921e
  IF: wlp4s0 state: down mac: f0:a6:54:33:f4:2d
  Device-3: Realtek RTL8153 Gigabit Ethernet Adapter driver: r8152 type: USB
  IF: enx9405bb1970c2 state: down mac: 94:05:bb:19:70:c2
Bluetooth:
  Device-1: Foxconn / Hon Hai MediaTek Bluetooth Adapter driver: btusb
    type: USB
  Report: hciconfig ID: hci0 rfk-id: 2 state: down
    bt-service: enabled,running rfk-block: hardware: no software: yes
    address: F0:A6:54:33:F4:2E
Drives:
  Local Storage: total: 505.77 GiB used: 22.83 GiB (4.5%)
  ID-1: /dev/nvme0n1 vendor: Samsung model: MZVLB512HBJQ-000L2
    size: 476.94 GiB
  ID-2: /dev/sda vendor: Kingston model: DataTraveler 3.0 size: 28.83 GiB
    type: USB
Partition:
  ID-1: / size: 27.17 GiB used: 22.82 GiB (84.0%) fs: ext4 dev: /dev/sda2
  ID-2: /boot/efi size: 1.05 GiB used: 6.1 MiB (0.6%) fs: vfat
    dev: /dev/sda1
Swap:
  ID-1: swap-1 type: file size: 4 GiB used: 0 KiB (0.0%) file: /swap.img
Sensors:
  System Temperatures: cpu: 42.2 C mobo: N/A gpu: nvidia temp: 39 C
  Fan Speeds (rpm): N/A
Info:
  Processes: 362 Uptime: 1h 0m Memory: total: 16 GiB available: 15.46 GiB
  used: 3.62 GiB (23.4%) Shell: fish inxi: 3.3.29
```

#### More shown in Pictures:
![Screenshot from 2023-10-24 16-24-26](https://github.com/canonical/steam-snap/assets/110736521/15ab5595-f4d6-4984-8d13-6a83434da358)
![Screenshot from 2023-10-24 16-32-09](https://github.com/canonical/steam-snap/assets/110736521/01fa0f84-a30f-406a-87e7-69eeb42a84a1)
![Screenshot from 2023-10-24 16-33-12](https://github.com/canonical/steam-snap/assets/110736521/c0cecbef-2d29-4610-91d6-50a907e11789)
![Screenshot from 2023-10-24 16-46-54](https://github.com/canonical/steam-snap/assets/110736521/64481076-62b3-4beb-b5e9-b5a6eda03eb3)

TL;DR:
**_There only two ways of enabling the Steam's fractional scaling along with the rest of the system:
Using `steam -forcedesktopscaling 1.5 %U` ARGUMENT
or
`env GDK_SCALE=2 steam` / `export GDK_SCALE=2 & steam`_**

**_They can be added to their respective application launchers in:
`/var/lib/snapd/desktop/applications/steam_steam.desktop` for the Snap version
`/usr/share/applications/steam.desktop` for the .DEBian version
`~/.local/share/applications/com.valvesoftware.Steam.desktop` for the Flatpak version_**

**Comment by ShalokShalom** [comment]
Same happens to me. 

![Screenshot_20231029_110430](https://github.com/ValveSoftware/steam-for-linux/assets/6344099/053e0d5d-0a99-44b5-bd39-f35628860676)

```
inxi -Fxz
System:    Kernel: 6.1.57 x86_64 bits: 64 compiler: gcc v: 12.2.0 Desktop: KDE Plasma 5 Distro: NixOS 23.05 (Stoat) 
Machine:   Type: Laptop System: LENOVO product: 82L0 v: Yoga Slim 7 Carbon 14ACN6 serial: <filter> 
           Mobo: LENOVO model: LNVNB161216 v: NO DPK serial: <filter> UEFI: LENOVO v: H5CN39WW date: 03/03/2023 
Battery:   ID-1: BAT0 charge: 29.9 Wh (55.7%) condition: 53.7/61.0 Wh (88.1%) volts: 7.7 min: 7.7 model: Celxpert L20C4PF2 
           status: Discharging 
CPU:       Info: 8-Core model: AMD Ryzen 7 5800U with Radeon Graphics bits: 64 type: MT MCP arch: Zen 3 rev: 0 cache: 
           L2: 4 MiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 60683 
           Speed: 1900 MHz min/max: 1600/1900 MHz boost: enabled Core speeds (MHz): 1: 1900 2: 4441 3: 1900 4: 1900 5: 1397 
           6: 1900 7: 1523 8: 1900 9: 1900 10: 1900 11: 1900 12: 1900 13: 1900 14: 1900 15: 1900 16: 1900 
Graphics:  Message: No device data found. 
           Display: x11 server: X.org 1.21.1.8 driver: loaded: N/A resolution: <missing: xdpyinfo> 
           Message: Unable to show advanced data. Required tool glxinfo missing. 
Audio:     Device-1: HD-Audio Generic driver: HDA-Intel message: bus/chip ids unavailable 
           Device-2: HD-Audio Generic driver: HDA-Intel message: bus/chip ids unavailable 
           Device-3: acp driver: acp message: bus/chip ids unavailable 
           Sound Server-1: ALSA v: k6.1.57 running: yes 
           Sound Server-2: PipeWire v: 0.3.71 running: yes 
Network:   Message: No device data found. 
           IF-ID-1: wlp1s0 state: up mac: <filter> 
Bluetooth: Device-1: Realtek Bluetooth Radio type: USB driver: btusb v: 0.8 bus-ID: 3-4:3 
           Report: hciconfig ID: hci0 rfk-id: 4 state: up address: <filter> bt-v: 3.0 lmp-v: 5.2 
Drives:    Local Storage: total: 476.94 GiB used: 19.43 GiB (4.1%) 
           ID-1: /dev/nvme0n1 vendor: SK Hynix model: HFS512GDE9X084N size: 476.94 GiB 
Partition: ID-1: / size: 453.25 GiB used: 19.39 GiB (4.3%) fs: ext4 dev: /dev/nvme0n1p2 
           ID-2: /boot size: 511 MiB used: 35.9 MiB (7.0%) fs: vfat dev: /dev/nvme0n1p1 
Swap:      ID-1: swap-1 type: partition size: 14.87 GiB used: 6.2 MiB (0.0%) dev: /dev/nvme0n1p3 
Sensors:   Missing: Required tool sensors not installed. Check --recommends 
Info:      Processes: 295 Uptime: 11h 43m Memory: 13.52 GiB used: 4.36 GiB (32.2%) Init: systemd Compilers: gcc: N/A 
           Packages: 1488 Shell: Bash v: 5.2.15 inxi: 3.3.04 
```

**Comment by Sunspark-007** [comment]
@kisak-valve What I find ironic about this issue, is that it exists on the Steam Deck (a Valve retail product) in Desktop Mode.

To see for yourself, plug it into a dock or monitor, set the scaling to say 150%. Note that the text in the Steam app remains microscopic.

No issue with Windows at 150% scaling, fonts are correctly scaled.

**Comment by ShalokShalom** [comment]
I think it makes sense, to consider using the "High Priority" label for this one, what do you think?

**Comment by ShalokShalom** [comment]
@kisak-valve Is this deliberately ignored?

**Comment by oldkentuckymark** [comment]
Can we just get a slider or dropdown box to set the scale ourselves in steam, instead of morass of nonstandard environment variables and launch arguments?

**Comment by Cifer9516** [comment]
Just allow to set scale manually ffs

**Comment by TDuffinNTU** [comment]
Woo! First bump of this thread in 2024! But seriously though, This shouldn't be an issue after nearly a whole year. I'm on Wayland and 99% of the user interface scales perfectly fine, but for some reason the Steam client seems adamant on forcing its own absurdly small UI scale!

**Comment by ShalokShalom** [comment]
> Woo! First bump of this thread in 2024! But seriously though, This shouldn't be an issue after nearly a whole year. I'm on Wayland and 99% of the user interface scales perfectly fine, but for some reason the Steam client seems adamant on forcing its own absurdly small UI scale!
> 
> FWIW, I tried the fixes above but the only one that worked was executing
> 
> `sudo flatpak override --env=STEAM_FORCE_DESKTOPUI_SCALING=2.0 com.valvesoftware.Steam`
> 
> in any console. You dont need to modify your .desktop file which is a nice touch! I'm using the flatpak version on KDE Plasma (Wayland session)

I am absolutely pissed. Not only, because its still an issue after a year and not even because its such a glaring issue for so many people. 

No, but because the literally pinging of the responsible employee of this organisation simply ignores the issue. 

Its just offending at this point.

**Comment by Casuallynoted** [comment]
It's.... very special that a year after encountering this issue on Linux, I've come back to Linux and it's still a problem. Wow.

**Comment by jarrard** [comment]
Well its now fixable but not in a intuitive way.  Valve just needs to add scaling percentile to Steams settings, in 25% jumps perhaps.

**Comment by MartinVonReichenberg** [comment]
> > Replying to https://github.com/ValveSoftware/steam-for-linux/issues/9209#issuecomment-1902097884
> 
> I am absolutely pissed. Not only, because its still an issue after a year and not even because its such a glaring issue for so many people. 
> 
> No, but because the literally pinging of the responsible employee of this organisation simply ignores the issue. 
> 
> Its just offending at this point.  



One guy from the Steam support wrote to me that they do not have an exact ETA on whether it is going to be fixed or not so it still might be a matter of months/years from now on . . .

So, good luck & have fun.

**Comment by arazilsongweaver** [comment]
> > > Replying to [#9209 (comment)](https://github.com/ValveSoftware/steam-for-linux/issues/9209#issuecomment-1902097884)
> One guy from the Steam support wrote to me that they do not have an exact ETA on whether it is going to be fixed or not so it still might be a matter of months/years from now on . . .

They better start actively working on fixing this soon as this is becoming hard to ignore. High DPI devices are becoming more popular, mainline distributions are moving to a Wayland only format, next month's KDE 6 is mainlining support for Wayland, and the last remaining Wayland bugs are being worked out of the NVIDIA drivers. The X11 session support that Valve seems to be relying here on is not long for this world.

**Comment by TDuffinNTU** [comment]
> XWayland will be supported for years if not decades to come. There is no incentive for Valve to spend engineering resources fixing a bug that affects < 1% of their users.

This issue affects ALL high DPI displays, regardless of the desktop's choice of display backend. I get the same problem (and same solution, at least!) on X11 proper.

(Aside from the point, most users in 2024 are Wayland. If you consider that every Steamdeck runs Wayland (in game mode) and almost all modern distros ship Wayland as the default backend, I can't imagine most people notice enough of a change to know they've migrated).

***

As for others with high DPI displays -- Just don't use the .deb and use the flatpak where you can enforce scaling as a launch argument via flatseal. If you're stuck with the .deb, you can add the argument there too but you'll have to modify the .desktop file IIRC. One of the benefits of flatpak is being able to manage this like CLI args in one utility.

**Comment by tesfabpel** [comment]
BTW, a point that it seems no one has still touched is mixed-DPI setups. This makes the slider just a workaround because it won't work in those situations because it depends on what monitor the Steam's windows are (and there could be multiple Steam windows open at the same time and on different monitors). 
Anyway, until Valve fixes the issue in the correct way, the slider may be a good option (in the future, it could work as a global scale multiplier by the Steam client, like if you want bigger UI elements to see them better).

**Comment by jfroy** [comment]
Steamdeck, which is not affected by this issue at least in gamescope, represents 40% of Linux users (https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam?platform=linux). Combined with Linux's global 1.97% share (https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam?platform=combined), that means desktop Linux has a 1.182% share. So OK, slightly above 1%.

Of course, this ignores the share of Linux desktop users who have displays with a resolution above 1080p (19.08%). If you factor that in, you're down to 0.23% of users who may be affected by HiDPI issues on desktop Linux. I grant that primary screen resolution is not a direct signal for display DPI, but it is a good estimate.

**Comment by jfroy** [comment]
> > Of course, this ignores the share of Linux desktop users who have displays with a resolution above 1080p (19.08%). If you factor that in, you're down to 0.23% of users who may be affected by HiDPI issues on desktop Linux. I grant that primary screen resolution is not a direct signal for display DPI, but it is a good estimate.
> 
> Again, not everything is about hiDPI. In my case, yes. Others such as visually-impaired, no. Others that just want to change size, no. Assumptions regarding data..*sigh*.
> 
> Not to mention you think those surveys represent all Steam users. Those represent the ones that allow the survey to run and report data afterwards (if submitted). Assumptions regarding data..*sigh*.

I did mention accessibility, and I tried to state my assumptions. No data set is perfect, but making decisions informed by imperfect data, knowing the assumptions you're making, is better than making decisions based on gut feeling or ideology. I don't know if Valve has ever stated whether or not the Steam hardware survey is statistically significant (e.g. how many users get prompted, how many users agree to send the data). But if it is statistically significant, then we can make conclusions about the overall Steam user population from it. They (Valve) certainly suggest that it is and that game developers and publishers can use it to make addressable market decisions.

**Comment by TDuffinNTU** [comment]
The simple solution to people who dont think this feature is worth developing: dont bother commenting on this issue which doesnr affect you!

I can't imagine some here would have the audacity to comment on an issue for, say a Windows application and complain because it doesnt affect them as a Linux user!

If this issue truly isn't on Valve's roadmap then at this will serve as a reminder to them of the users who will benefit! I wonder if the flatpak repackage can show an alert like it does regarding udev rules.

**Comment by DDR0** [comment]
Issue is still affecting me here on KDE Neon 5.72; Steam is very, very tiny on my high-dpi screen.
![image](https://github.com/ValveSoftware/steam-for-linux/assets/862627/4e69f9d3-6438-4ff5-a54d-1ec81b2ec20f)

**Comment by kakra** [comment]
> There only two ways of enabling the Steam's fractional scaling along with the rest of the system:
> Using `steam -forcedesktopscaling 1.5 %U` ARGUMENT

Works for me, wow, thanks @MartinVonReichenberg - using KDE Plasma with fractional scaling of 1.5. Finally, I don't need to move my nose 5cm in front of the screen to read the Steam client.

For some unknown reason, very rarely (I mean "extreme rarely"), the Steam Client actually used 1.5 scaling even without this setting - but in only lasted until the client restartet, and it always only affected Steam when autostarting with the session *if* it worked.

Interestingly, with `-forcedesktopscaling 1.5` the client renders much faster (at least it feels much snappier, scrolling is still sluggish on those fancy overlay community news).

I used the KDE menu editor to change the parameters, and also adjusted the autostart entry the same way.

**Comment by arazilsongweaver** [comment]
Steam shipped a major client update on 27 February 2024 that updated the Chromium runtime and was described as "clearing [the] path for further updates soon." Any chance that this glitch will get resolved in the near future?

**Comment by jarrard** [comment]
I noticed for a long time now that steam UI has been flickering under Wayland, mostly in the top section.

**Comment by Seegras** [comment]
scaling now works for me. Except in steam overlay mode. There I have tiny windows...

**Comment by pohmelie** [comment]
@Seegras 
Nah, scaling is not fixed
![image](https://github.com/ValveSoftware/steam-for-linux/assets/2385765/e21918a4-85c4-41ee-83bc-69c9d35c2bb2)

**Comment by ivanich** [comment]
Under Wayland in the kde plasma 6.0.1 scaling doesn't work for steam.

**Comment by jarrard** [comment]
pretty sure I got it working with nvidia 4090 of all things.

**Comment by ShalokShalom** [comment]
The recent update has fixed it for me.

**Comment by ShalokShalom** [comment]
> Under Wayland in the kde plasma 6.0.1 scaling doesn't work for steam.

I am on Wayland with Plasma 6.0.1 and it works for me. 2.8K screen on a laptop:

![Screenshot_20240310_200342-1](https://github.com/ValveSoftware/steam-for-linux/assets/6344099/f85a7b6f-6b39-4b03-9beb-afd26ed3ba1d)

**Comment by ivanich** [comment]
> > Under Wayland in the kde plasma 6.0.1 scaling doesn't work for steam.
> 
> I am on Wayland with Plasma 6.0.1 and it works for me. 2.8K screen on a laptop:
> 
> ![Screenshot_20240310_200342-1](https://private-user-images.githubusercontent.com/6344099/311537635-f85a7b6f-6b39-4b03-9beb-afd26ed3ba1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMDk2NDEsIm5iZiI6MTcxMDEwOTM0MSwicGF0aCI6Ii82MzQ0MDk5LzMxMTUzNzYzNS1mODVhN2I2Zi02YjM5LTRiMDMtOWJlYi1hZmQyNmVkM2JhMWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTBUMjIyMjIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmIyODE0MmE0MzNmOGUzY2UyNDk0Y2VjZjViMGY5NzVmM2Q5MzFiYjMyOTk3NjZhMDIwZjc0NTlkNjMxOTYzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.z4U4ZguFT5GnpQmHZJN-i0Gqk6MvsSFt_msblMOxkvo)

No luck here
![Знімок_20240310_232211](https://github.com/ValveSoftware/steam-for-linux/assets/1647196/85284ae7-e94d-4221-9d58-89eb798e1a04)

**Comment by ShalokShalom** [comment]
I had already forgotten, that I had that setting in and it does not work without it as well. 

But I had already at the point for the past weeks that even that setting wouldn't change anything.

**Comment by kakra** [comment]
> So we are back to square one and still no signal from Valve employees.

It is probably very hard to maintain due to the various components which do things differently (e.g., the UI toolkit does not support fractional scaling), and we have a mix of different technologies (some of the UI renders with gtk/gdk, some renders with Chromium/webkit), and we have a mix of different rendering targets (sometimes the UI renders to desktop surfaces, sometimes it renders to overlay surfaces), plus Steam seems to do some window management by itself because it doesn't use server-side decorations. In my case, it messes up its position and size while scaling is forced if monitors turn off or on, or if I just minimize/restore the client. On the top, we now have Xorg and Wayland to care about, they should probably focus on Wayland because Xorg is going away within the next few years (I'm still using Xorg and will do so for a while, so it's probably not going to work well for me if they focus on Wayland).

> So we are back to square one and still no signal from Valve employees.

I would at least appreciate some more testing of the known corner cases with and without forced scaling before they release a new client. Currently, it's a mess.

**Comment by ShalokShalom** [comment]
They could at least answer, for starters.

**Comment by D-Code** [comment]
Curious - entering Big Picture Mode and then exiting Big Picture Mode gives a correctly scaled interface.

**Comment by Lucretia** [comment]
Still a problem, still can't read the tiny arsed text that is literally 2 mm tall on this 4K screen. I've tried with and without beta, going into big picture mode and exiting like someone else said with and without interface scaling selected, I've tried changing ```DPIScaling``` inside ~/.steam/ to 2.0, ```Gdk/WindowScalingFactor``` inside ~/.config/xsettingsd/xsettingsd.conf to 2.0 and NOTHING works.

**Comment by Lucretia** [comment]
I just found [```STEAM_FORCE_DESKTOPUI_SCALING=1.5 steam```](https://forum.manjaro.org/t/steam-fontsize-to-small-the-solution/142572/9) which WORKS!

**Comment by MartinVonReichenberg** [comment]
> I just found [```STEAM_FORCE_DESKTOPUI_SCALING=1.5 steam```](https://forum.manjaro.org/t/steam-fontsize-to-small-the-solution/142572/9) which WORKS!

You looked far:
[It is mentioned here](https://github.com/ValveSoftware/steam-for-linux/issues/9209#issuecomment-1777462702), _but lost in thread . . ._

**Comment by Lucretia** [comment]
> > I just found [`STEAM_FORCE_DESKTOPUI_SCALING=1.5 steam`](https://forum.manjaro.org/t/steam-fontsize-to-small-the-solution/142572/9) which WORKS!
> 
> You looked far: [It is mentioned here](https://github.com/ValveSoftware/steam-for-linux/issues/9209#issuecomment-1777462702), _but lost in thread . . ._

That variable is not mentioned in that post.

**Comment by MartinVonReichenberg** [comment]
> > > I just found [`STEAM_FORCE_DESKTOPUI_SCALING=1.5 steam`](https://forum.manjaro.org/t/steam-fontsize-to-small-the-solution/142572/9) which WORKS!
> > 
> > You looked far: [It is mentioned here](https://github.com/ValveSoftware/steam-for-linux/issues/9209#issuecomment-1777462702), _but lost in thread . . ._
> 
> That variable is not mentioned in that post.

No it is not - my bad.

The issue, however, can vary from distro to distro as Arch+ uses Steam Native and Stream Runtime in which `-forcedesktopscale` might work only for one of those. Also, there have been changes to libraries after several months which potentially affected this issue and its 'temporary solution(s)'. _So it is easy to 'get lost'._ 😵

**Comment by Lucretia** [comment]
> > > > I just found [`STEAM_FORCE_DESKTOPUI_SCALING=1.5 steam`](https://forum.manjaro.org/t/steam-fontsize-to-small-the-solution/142572/9) which WORKS!
> > > 
> > > 
> > > You looked far: [It is mentioned here](https://github.com/ValveSoftware/steam-for-linux/issues/9209#issuecomment-1777462702), _but lost in thread . . ._
> > 
> > 
> > That variable is not mentioned in that post.
> 
> No it is not - my bad.
> 
> The issue, however, can vary from distro to distro as Arch+ uses Steam Native and Stream Runtime in which `-forcedesktopscale` might work only for one of those. Also, there have been changes to libraries after several months which potentially affected this issue and its 'temporary solution(s)'. _So it is easy to 'get lost'._ 😵

As I said, that option does not work here (Gentoo).

**Comment by Woovie** [comment]
Using Arch, flatpak Steam. In order to use the env var, I had to copy the generated .desktop and modify the Exec.

In `~/.local/share/applications/` there is this symlink:

```
com.valvesoftware.Steam.desktop -> /var/lib/flatpak/app/com.valvesoftware.Steam/current/active/export/share/applications/com.valvesoftware.Steam.desktop
```

I copied the file into the same directory, named it something else, and made these changes:

```
❯ diff com.valvesoftware.Steam.desktop steam-fixed.desktop
30c30
< Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/steam --file-forwarding com.valvesoftware.Steam @@u %U @@
---
> Exec=/usr/bin/flatpak run --env=STEAM_FORCE_DESKTOPUI_SCALING=1.5 --branch=stable --arch=x86_64 --command="/app/bin/steam" --file-forwarding com.valvesoftware.Steam @@u %U @@
```

Note the usage of `--env`, you cannot simply quote the command and add it to that flag.

**Comment by vmatare** [comment]
Runnig with the env var `STEAM_FORCE_DESKTOPUI_SCALING=1.5` **and** enabling "Scale Text ..." in the Interface settings finally fixed it for me.

**Comment by escape0707** [comment]
One-liner to edit and add  `STEAM_FORCE_DESKTOPUI_SCALING=2` to your `.desktop` file (for Arch users):

```shell
desktop-file-install --dir=$HOME/.local/share/applications --set-key=Exec --set-value="env STEAM_FORCE_DESKTOPUI_SCALING=2 /usr/bin/steam-runtime %U" /usr/share/applications/steam.desktop
```

**Comment by BinaryShrub** [comment]
> One-liner to edit and add `STEAM_FORCE_DESKTOPUI_SCALING=2` to your `.desktop` file (for Arch users):
> 
> ```shell
> desktop-file-install --dir=$HOME/.local/share/applications --set-key=Exec --set-value="env STEAM_FORCE_DESKTOPUI_SCALING=2 /usr/bin/steam-runtime %U" /usr/share/applications/steam.desktop
> ```

You should copy into your own home before making modifications so it doesnt get overwritten on update:

```
cp /usr/share/applications/steam.desktop ~/.local/share/applications/steam.desktop
```

then update your `.local` copy

**Comment by perroboc** [comment]
> ```shell
> --dir=$HOME/.local/share/applications
> ```

Isn't that what the `--dir=$HOME/.local/share/applications` argument does?

**Comment by BinaryShrub** [comment]
> > You should copy into your own home before making modifications so it doesnt get overwritten on update
> 
> Isn't that what the `--dir=$HOME/.local/share/applications` argument does?

I'm a noob, thank you.

**Comment by REDxMisfit** [comment]
I am having the problem today.

I saw this bug mostly on the contact window before. My steam main window was alright, and the contact window had the text not scaled for 4K display, all i had to do was switch it to fullscreen, then to back to window and the UI scaled back to what it should have display on first opening.
But today it is happening to the main window, i am not on a beta branch and using Windows 11 up-to-date with 200% scaling set.

You can see that the menu "drop down" is not affected by the scale problem (albeit not being displayed below the profile name "RED.MISFIT" and still rendering at the correct size. All the other text is smaller than it should be, and the shop page is somehow bigger and out of the window completely.

![image](https://github.com/user-attachments/assets/06c48de8-66e7-4efe-9359-f6a582264a3c)

**Comment by REDxMisfit** [comment]
I know, but there is no "Steam-for-Windows" repositery. And at least the problem can affect way more players if it shows on Windows now. So maybe Valve would wake up to do something about it.

**Comment by kakra** [comment]
> I know, but there is no "Steam-for-Windows" repositery. And at least the problem can affect way more players if it shows on Windows now. So maybe Valve would wake up to do something about it.

I think the way to go is using their support forums inside Steam. Knowing that this about Linux and still using it for Windows issues, is going to help no one: I even don't run Windows, probably many others don't, too. No one will be able to help you here. It just noise for a lot of people subscribed here.

**Comment by D-Code** [comment]
Finally, scaling behaves correct for me now after a recent Steam client update:
```
Steam Beta Branch:  Stable Client
Steam Version:  1726088054
Steam Client Build Date:  Wed, Sep 11 22:40 UTC -08:00
Steam Web Build Date:  Wed, Sep 11 20:53 UTC -08:00
Steam API Version:  SteamClient021
```

**Comment by dafzor** [comment]
Same, on KDE Plasma 6.1.5 no longer need to set variables for Steam to s scale correctly on boot. However it still doubles the scaling after exiting Big picture so still not fully issue free.

**Comment by pohmelie** [comment]
@D-Code @dafzor 
Nah, still broken for me.
![image](https://github.com/user-attachments/assets/fb82991b-d371-4c51-872a-02a276661d17)

**Comment by hypertxtc** [comment]
Still has the same behaviour for me. I'm running Fedora Kinoite, Steam Flatpak, AMD GPU.

What is interesting is that if I run the same OS in a VM using Boxes, Steam scales correctly if hardware acceleration on the VM is turned off (you can tell with llvmpipe)
![Screenshot_20240916_220234](https://github.com/user-attachments/assets/8156b141-0fe5-4554-8639-ebc5d57b5273)
but if I enable hardware acceleration on the VM, Steam continues to scale incorrectly, as shown in the following screenshot.
![Screenshot_20240916_220752](https://github.com/user-attachments/assets/2e1b9ad1-9555-439a-b42d-123f1dcf4420)

**Comment by ninja-** [comment]
adding `STEAM_FORCE_DESKTOPUI_SCALING=1.75` to flatseal env worked for me too.
but I am surprised that even at non-fractional 200%, it's not detected from Xwayland settings on KDE and it just renders at 100% in all cases without the env

**Comment by Mshmaitelly** [comment]
It is not working on my machine using the latest update client in Beta mode. Running on EOS with latest official packs. Scaling does not work on the 4K Ultra wide next to the main display in 1080p in portrait mode.

**Comment by polluxau** [comment]
i also need to use STEAM_FORCE_DESKTOPUI_SCALING= for this to work on kde plasma, i thought this was solved but guess not as the option in settings doesnt do anything

**Comment by hypertxtc** [comment]
> i also need to use STEAM_FORCE_DESKTOPUI_SCALING= for this to work on kde plasma, i thought this was solved but guess not as the option in settings doesnt do anything

What distro are you using. Fedora KDE here and scaling works fine now.

**Comment by Mshmaitelly** [comment]
@polluxau 
You need to edit the local file of the desktop app in the following path
/home/<username>/.local/share/applications

**Comment by polluxau** [comment]
> @polluxau You need to edit the local file of the desktop app in the following path /home/username/.local/share/applications



> > i also need to use STEAM_FORCE_DESKTOPUI_SCALING= for this to work on kde plasma, i thought this was solved but guess not as the option in settings doesnt do anything
> 
> What distro are you using. Fedora KDE here and scaling works fine now.

endeavour os, kde plasma 6.2.4

**Comment by polluxau** [comment]
> @polluxau You need to edit the local file of the desktop app in the following path /home/username/.local/share/applications

wdym edit the local file of the desktop app in the following path?

if i need to edit a shortcut or add a environment variable the issue isnt fixed as it should do it automatically for you, but as i said i need to use that environment variable for steam to upscale properly

**Comment by Mshmaitelly** [comment]
Yes, I agree. Steam cannot detect the monitor resolution and adjusted the scaling automatically when launched on the current HiDPI screen. 
The only solution is either set do the fix as sated above by  perroboc

**Comment by drguildo** [comment]
I recently did a clean install of Fedora 43. I installed the Steam Flatpak and it worked well. Today when starting Steam, it updated itself, and scaling in the overlay is now broken. I'm using a 32" 4K monitor and everything is extremely small.

I tried adding `STEAM_FORCE_DESKTOPUI_SCALING=1.75` to the environment variables in Flatseal, but it made no difference.

**Comment by Lucretia** [comment]
> > i also need to use STEAM_FORCE_DESKTOPUI_SCALING= for this to work on kde plasma, i thought this was solved but guess not as the option in settings doesnt do anything
> 
> What distro are you using. Fedora KDE here and scaling works fine now.

I wouldn't call the font size "fine," unless you mean the size, then it's fine (as in tiny). It's readable, but it's small. I'm on KDE on gentoo.

Seriously, how hard is it to add a font size slider and have someone who has bad eyesight actually test the thing.

**Comment by OdinVex** [comment]
> Replying to https://github.com/ValveSoftware/steam-for-linux/issues/9209#issuecomment-3560536689

I asked for a textbox with a float/decimal multiplier as sliders aren't as fine-grain, but Valve's basically told us to \*\*\*\* off and take whatever they give.
