### ISSUE TITLE
Notifications render in the wrong place with multiple monitors

### ISSUE THREAD

**Issue by tatokis** [ValveSoftware/steam-for-linux#9374]
#### Your system information

* Steam client version (build number or date): 1682634349
* Distribution (e.g. Ubuntu): Ubuntu 20.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Notification coordinates are handled incorrectly. This started with the latest beta update which overhauls the UI and notifications. It seems to calculate the coordinates based on the primary monitor, but then proceeds to render using absolute coordinates.

This is a standard xrandr multiple monitor setup.

Apologies for the massive screenshot, but it's the only way to showcase the issue.

![steam_notification](https://user-images.githubusercontent.com/6003656/235034338-fbdce202-2894-4af9-aa23-25811513dfe0.jpg)

#### Steps for reproducing this issue:

1. Have a multiple monitor setup
2. Start Steam
3. Trigger a notification

**Comment by rKsanu2MMYvypWePtQWM** [comment]
Same for me.

**Comment by JacobSvenningsen** [comment]
Yep, seems it.
After taking a screenshot of the issue as well, I tried just adjusting the position of the primary monitor in an image-editing tool. By only adjusting the Y-coordinate, the position of the notification ended up being exactly where you expect it to.
Is position calculated from the top-left position?

before/after image-manipulation screenshots;
![1](https://user-images.githubusercontent.com/5268510/235288924-79037ea6-772f-44da-ac6e-6083224e7dfb.png)
![2](https://user-images.githubusercontent.com/5268510/235288925-60c0a496-4d31-4f7e-a983-7e6f0c98864a.png)

**Comment by caseif** [comment]
This issue occurs in a Plasma 5.27 Wayland session as well.

**Comment by Metal-spoon** [comment]
Can confirm.
Plasma 5.27 wayland on fedora 37.
Running steam beta.

**Comment by lucasreis1** [comment]
Can confirm it's happening here too.

I'm on Arch, kernel 6.2.9, using i3 4.22 as the WM.

Here's my monitor setup:

```
Screen 0: minimum 8 x 8, current 4480 x 1440, maximum 32767 x 32767
DP-2 connected 1920x1080+0+180 (normal left inverted right x axis y axis) 543mm x 302mm
   1920x1080     60.00 + 165.00*  143.98   119.98    84.90    59.94    50.00  
DP-4 connected primary 2560x1440+1920+0 (normal left inverted right x axis y axis) 597mm x 336mm
   2560x1440    165.00*+ 144.01   120.00    99.95    59.95  
```

**Comment by hasezoey** [comment]
can also confirm that it happens for me

for me the notifications appear slightly off-center to the left on my middle (primary) screen (directly above the task-bar instead of like other users somewhere in the middle of the screen) and not the bottom right corner like the old client did

steam version: 1683253302

<details>
<summary>Display Layout Screenshot & System Information</summary>

![display_layout](https://user-images.githubusercontent.com/10911626/236613211-9e4120a2-5d4b-43ec-9650-e1cf6feb692d.png)

Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.2.12-1-MANJARO (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5800X 8-Core Processor
Memory: 15.5 GiB of RAM
Graphics Processor: AMD Radeon RX Vega
Manufacturer: ASUS

</details>

**Comment by nuggs** [comment]
> 

Can confirm this happens to me as well on X11 using i3 with the same monitor setup(1080p,1440p,1080p).

Notification renders like it's trying to render for one of my 1080p monitors which causes it to be to the left of center on my main monitor(1440p).

steam version: 1683314987

**Comment by DeedleFake** [comment]
Also happening under GNOME 44 Wayland on Manjaro. Seems to be rendering on my 4K monitor in the location it should be if it was rendering on my main 1440p monitor.

**Comment by joan31** [comment]
Hi,

Same here with sway and arch linux.

I have three monitors, and notifications appear to my left monitor.

xrandr is configured with my middle screen as primary.

```
DP-1 connected primary 1920x1080+1920+0 (normal left inverted right x axis y axis) 530mm x 300mm
   1920x1080     59.96*+
   1440x1080     59.99  
   1400x1050     59.98  
   1280x1024     59.89  
   1280x960      59.94  
   1152x864      59.96  
   1024x768      59.92  
   800x600       59.86  
   640x480       59.38  
   320x240       59.52  
   1680x1050     59.95  
   1440x900      59.89  
   1280x800      59.81  
   1152x720      59.97  
   960x600       59.63  
   928x580       59.88  
   800x500       59.50  
   768x480       59.90  
   720x480       59.71  
   640x400       59.95  
   320x200       58.96  
   1600x900      59.95  
   1368x768      59.88  
   1280x720      59.86  
   1024x576      59.90  
   864x486       59.92  
   720x400       59.55  
   640x350       59.77  
DP-2 connected 1920x1080+3840+0 (normal left inverted right x axis y axis) 530mm x 300mm
   1920x1080     59.96*+
   1440x1080     59.99  
   1400x1050     59.98  
   1280x1024     59.89  
   1280x960      59.94  
   1152x864      59.96  
   1024x768      59.92  
   800x600       59.86  
   640x480       59.38  
   320x240       59.52  
   1680x1050     59.95  
   1440x900      59.89  
   1280x800      59.81  
   1152x720      59.97  
   960x600       59.63  
   928x580       59.88  
   800x500       59.50  
   768x480       59.90  
   720x480       59.71  
   640x400       59.95  
   320x200       58.96  
   1600x900      59.95  
   1368x768      59.88  
   1280x720      59.86  
   1024x576      59.90  
   864x486       59.92  
   720x400       59.55  
   640x350       59.77  
HDMI-A-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 530mm x 300mm
   1920x1080     59.96*+
   1440x1080     59.99  
   1400x1050     59.98  
   1280x1024     59.89  
   1280x960      59.94  
   1152x864      59.96  
   1024x768      59.92  
   800x600       59.86  
   640x480       59.38  
   320x240       59.52  
   1680x1050     59.95  
   1440x900      59.89  
   1280x800      59.81  
   1152x720      59.97  
   960x600       59.63  
   928x580       59.88  
   800x500       59.50  
   768x480       59.90  
   720x480       59.71  
   640x400       59.95  
   320x200       58.96  
   1600x900      59.95  
   1368x768      59.88  
   1280x720      59.86  
   1024x576      59.90  
   864x486       59.92  
   720x400       59.55  
   640x350       59.77
```

**Comment by pointydev** [comment]
Same here, on `Steam Version: 1684372665`
```
OS: Fedora release 38 (Thirty Eight) x86_64
Kernel: 6.2.15-100.fc36.x86_64 
Resolution: 1920x1080, 1920x1080, 1920x1080
DE: Plasma 5.27.4 
WM: KWin 
```
```
[pointy@pointy ~]$ xrandr --listactivemonitors
Monitors: 3
 0: +*DP-0 1920/521x1080/293+1920+0  DP-0
 1: +DP-2 1920/521x1080/293+0+0  DP-2
 2: +DP-4 1920/521x1080/293+3840+0  DP-4
```

![example](https://the.yog.zone/3n7Rafg.png)

**Comment by NoXPhasma** [comment]
Same for me, they are always shown on the bottom right of the left monitor, instead of the primary right monitor. `Steam Version:  1684535786`

**Comment by JacobSvenningsen** [comment]
Latest beta seems to have fixed this on my end:
![image](https://github.com/ValveSoftware/steam-for-linux/assets/5268510/b97c2753-e51e-4804-9795-e3c66b1ca25c)

Despite this bulletpoint, it seems it wasn't actually only fixing it for Windows 10:
* Fixed toasts positioning correctly on windows when the task bar is moved to the top of the screen (Windows 10).

**Comment by pointydev** [comment]
Can also confirm that the [behaviour I previously experienced](https://github.com/ValveSoftware/steam-for-linux/issues/9374#issuecomment-1552962821) is fixed, tested on Steam `1686630523` using a virtually identical system configuration.

**Comment by NoXPhasma** [comment]
Same for me, fixed.

**Comment by d07434b2c08f** [comment]
Not sure if this should be a separate issue, but my notifications are still misplaced. I assume it's because I'm using 2.0x scaling and the notifications' dimensions are being scaled, but not the position. My client is version 1686779606 (Wed, Jun 14 14:18 UTC -08:00)

![image](https://github.com/ValveSoftware/steam-for-linux/assets/55886206/9ad681fb-3797-4c8d-90c2-c1aed000828e)

**Comment by hasezoey** [comment]
can confirm that for me it is also fixed (Manjaro KDE Plasma Wayland) (same display config as in https://github.com/ValveSoftware/steam-for-linux/issues/9374#issuecomment-1537092220)

<details>
<summary>KDE Versions</summary>

Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.106.0
Qt Version: 5.15.9
Kernel Version: 6.3.5-2-MANJARO (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5800X 8-Core Processor
Memory: 15.5 GiB of RAM
Graphics Processor: AMD Radeon RX Vega
Manufacturer: ASUS

</details>

**Comment by Kastor16** [comment]
I just opted into the beta since I've been having this problem for ages. But I'm still getting the same problem with this setup:
![image](https://github.com/ValveSoftware/steam-for-linux/assets/117348913/b7a101f3-a8ba-41b0-8c56-caa63fc75c33)

Notifications still appear on my primary screen roughly at height the second screen is offset. If I change the offset the placement of the notification changes.

```

Operating System: EndeavourOS 
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.107.0
Qt Version: 5.15.10
Kernel Version: 6.4.1-arch2-1 (64-bit)
Graphics Platform: Wayland
Processors: 32 × AMD Ryzen 9 5950X 16-Core Processor
Memory: 31.2 GiB of RAM
Graphics Processor: AMD Radeon RX 7900 XT
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: X570S AORUS MASTER
System Version: -CF
```

**Comment by DeedleFake** [comment]
After some more time has passed, this doesn't seem to be completely fixed. Notifications seem to work about 90% of the time, but every once in a while a notification just shows up in the middle of one of my monitors somewhere. It doesn't seem to be related to differing monitor resolutions anymore, but I'm not entirely sure as it doesn't happen consistently and the location seems to change a bit.

**Comment by kisak-valve** [comment]
Hello @DeedleFake, please open a new issue report so that your follow up issue can be tracked properly.
