### ISSUE TITLE
[Regression] Dual Sense controller recently stopped working properly with Steam on Steam Deck - production and beta

### ISSUE THREAD

**Issue by Philomorph** [ValveSoftware/steam-for-linux#9739]
#### Your system information

* Steam client version (build number or date): **1687563636** (build date June 23 16:19)
* Distribution (e.g. Ubuntu): **Steam Deck**
* Opted into Steam client beta?: [Yes/No] **Yes, but the problem started before I opted into Beta**
* Have you checked for system updates?: [Yes/No] **Yes**
* GPU: **AMD**
* [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11886546/steam-logs.tar.gz)

#### Please describe your issue in as much detail as possible:

**The Dual Sense controller (PS5) has stopped working properly through Steam, but works from the desktop without Steam.**

I've confirmed this with two other people so far seeing the same behavior.

About nine days ago I was playing on my Steam Deck in the morning and it was fine. After a break for lunch, during which I think Steam may have updated, the gyro on my Dual Sense controller stopped working in emulated games, which I believe use the SDL API for full compatibility.

I checked all the configs and everything seemed fine, so I booted to Desktop to check the settings.

Long story short, emulation works normally when run straight from the desktop, without Steam being involved.

Even though it's connected via BT and it works in the Steam menus, if I launch emulators or emulated games from Steam, in desktop or game mode, and use the previously working profile/configs, emulators won't "connect" to or detect the Dual Sense and nothing at all works.

If I try re-adding the controller with a new config, when I select SDL, the only controller detected is "Xbox 360", or "Steam Virtual Gamepad", depending on the emulator, and these don’t support motion controls, so it can’t be enabled.

Weirdly, in both Desktop and Game mode, if I run Steam and go into "controller > calibration & advanced settings > gyro calibration" - motion works and all axis are correctly detected. Steam just isn’t passing it on to other apps run from it.

I updated all my emulators and profiles, redownloaded fresh versions, and even tried switching to the Steam beta channel - nothing helps.

#### Steps for reproducing this issue:

1) Run an emulated game that was previously working with the Dual Sense controller - it no longer works.
2) Try re-adding the controller to a config profile in an emulator, like Cemu, it's not detected, or detected as the wrong device.

**Comment by Philomorph** [comment]
In case this helps illustrate the issue. The first pic is from Cemu, showing the config I'd been using fine for weeks. The problem is the "connect" button won't do anything, which is the behavior you get if the controller isn't connected via BT, or if Steam can't see it as it was when originally added.

The second and third pics are when I try to add a new controller to the profile - Instead of only listing the Dual Shock, it lists these options. One is from the same install of Cemu as the first pic. The second option is after I tried installing the Flatpack version.

![image](https://github.com/ValveSoftware/steam-for-linux/assets/13068591/38c39886-6df8-419f-a91d-11dff6f06182)

**Comment by TEEZEROEIGHT** [comment]
Would like to add that this issue is not limited to emulated games.
I have been experiencing this issue proton-run titles as well.
https://steamcommunity.com/app/1675200/discussions/1/5570437336435502346/

**Comment by Philomorph** [comment]
I wonder if these notes from the new patch mean they fixed this:

- DualSense Wireless Controllers will now remain in DirectInput compatible mode over Bluetooth when Steam Input is disabled.
- Fixed changing effects on PS4 and PS5 controllers when Steam Input is not enabled. 

I've finished the game I was playing that was affected by this issue, so it may not affect me, but I figured I'd mention it here in case anyone else is still being affected, or if a future game is affected.

**Comment by zerocoregithub** [comment]
Is this patch from the beta? The stable release still has this issue. (Been going on for months now)

**Comment by Philomorph** [comment]
From patch notes just released for stable. Don't know if it's rolling out today or soon.

**Comment by iawhd** [comment]
Still Seeing this behaviour on my end - so guessing the issue persists?

**Comment by zerocoregithub** [comment]
Yeah, it still persists. Another thing I noticed that when using the Gaming Mode > Desktop Mode > Gaming Mode work-around, when playing over Bluetooth the Gyro input is laggy and inconsistent. This is not an issue in Desktop Mode.

**Comment by FrogTheFrog** [comment]
I have posted this more permanent workaround (until SteamOS is updated and needs to be reapplied again) in https://github.com/ValveSoftware/steam-for-linux/issues/9597#issuecomment-1821578433 

Thought I would cross-post as it's a very annoying issue for me :/

**Comment by Philomorph** [comment]
Thanks for the workaround! I finished the one game where this was an issue for me, but if it comes up again I'll have this to fall back on.

**Comment by FrogTheFrog** [comment]
As of 3.6.19, the hid driver is being loaded be default, so I have closed my issue. I wonder if you should do the same @kisak-valve

**Comment by FrogTheFrog** [comment]
Agh, sorry! Meant to tag @Philomorph
