### ISSUE TITLE
Steam does not start on Fedora 38

### ISSUE THREAD

**Issue by nickonegen** [ValveSoftware/steam-for-linux#9780]
#### System information

- Steam client version: 1687386907
- Distribution: Fedora 38 (Workstation)
- Opted into Steam client beta?: No
- Have you checked for system updates?: Yes
- Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11931423/steam-logs.tar.gz)
- GPU: NVIDIA GeForce GTX 1050 (driver v535.54.03)
- DE: GNOME 44, X.Org 1.20.14 (no wayland)

<details>

<summary><code>$ dnf list installed "*steam*"</code></summary>

```sh
Installed Packages
steam.i686                                     1.0.0.78-1.fc38           @rpmfusion-nonfree-updates
steam-devices.i686                             1.0.0.78-1.fc38           @rpmfusion-nonfree-steam
```

</details><details>

<summary><code>$ dnf list installed "*nvidia*"</code></summary>

```sh
Installed Packages
akmod-nvidia.x86_64                            3:535.54.03-1.fc38        @rpmfusion-nonfree-nvidia-driver
kmod-nvidia-6.3.8-200.fc38.x86_64.x86_64       3:535.54.03-1.fc38        @@commandline
nvidia-settings.x86_64                         3:535.54.03-1.fc38        @rpmfusion-nonfree-nvidia-driver
xorg-x11-drv-nvidia.x86_64                     3:535.54.03-2.fc38        @rpmfusion-nonfree-nvidia-driver
xorg-x11-drv-nvidia-cuda-libs.x86_64           3:535.54.03-2.fc38        @rpmfusion-nonfree-nvidia-driver
xorg-x11-drv-nvidia-kmodsrc.x86_64             3:535.54.03-2.fc38        @rpmfusion-nonfree-nvidia-driver
xorg-x11-drv-nvidia-libs.i686                  3:535.54.03-2.fc38        @rpmfusion-nonfree-nvidia-driver
xorg-x11-drv-nvidia-libs.x86_64                3:535.54.03-2.fc38        @rpmfusion-nonfree-nvidia-driver
xorg-x11-drv-nvidia-power.x86_64               3:535.54.03-2.fc38        @rpmfusion-nonfree-nvidia-driver
```

</details>

#### Description ####

When I try to start Steam either from the terminal or from the application launcher, the process just hangs and doesn't open the Steam client (has to be killed using `kill` or just `killall steam`).

The issue started appeared one day ago–Steam was working perfectly fine before that. I made no changes to the system, settings or anything in that time (auto-update might have happened though).

Executing `steam` in the terminal didn't print any errors or any lines that would differ from a successful launch. After "RegisterForAppOverview", it appears that `steamwebhelper` was repeatedly executed:

```text
steamwebhelper.sh[330664]: Runtime for steamwebhelper: defaulting to /home/onegen/.steam/debian-installation/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[330664]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
```

The longer I let it run, the more `steamwebhelper`s were spawned (seen in `htop` and `ps aux | grep 'steam'`, no window ever appeared. At this point, the program didn't respond to even SIGINTs and had to be forcibly killed.

\
By some miracle, I was able to start Steam in offline mode (`steam -offline`) once after running `steam --reset`. Games, incl. online ones, ran as expected. But sadly, after I restarted the computer again, not even the offline option helped (I tried resetting again, no change).

#### What I tried so far ####

- `steam -offline`
- `steam --reset`
- `steam --flushconfig`
- Resetting the network & wiping the DNS cache
- `sudo dnf reinstall steam`

#### Steps for reproducing this issue: ####

1. <span title="wow really?">Run Steam</span>

**Comment by LuNeder** [comment]
This problem also happens on OpenSUSE Tumbleweed.

Steam opens and the tray icon appears and all, but no UI. This started to happen the day a mesa downgrade happened on Tumbleweed, 7 days ago. Back then running zypper dup with --allow-vendor-change used to fix it, but now it's broken again and that does not fix it anymore. Systemd journal also seems to briefly mention a problem with libcef.so:
`jul 02 19:22:19│script[3096]          │-> checking /home/luana/.local/share/Steam/ubuntu12_32/steam-runtime                                                                                                                            │
 │jul 02 19:22:22│dbus-daemon[2514]     │[session uid=1000 pid=2514] Activating service name='org.gnome.ScreenSaver' requested by ':1.135' (uid=1000 pid=4073 comm="/home/luana/.local/share/Steam/ubuntu12_32/steam -")                 │
 │jul 02 19:22:22│script[3096]          │waiting for steam to start...done                                                                                                                                                               │
 │jul 02 19:22:24│dbus-daemon[2514]     │[session uid=1000 pid=2514] Activating service name='org.gnome.ScreenSaver' requested by ':1.140' (uid=1000 pid=4252 comm="/home/luana/.local/share/Steam/ubuntu12_32/../ubun")                 │
 │jul 02 19:22:24│dbus-daemon[2514]     │[session uid=1000 pid=2514] Activating service name='org.gnome.ScreenSaver' requested by ':1.140' (uid=1000 pid=4252 comm="/home/luana/.local/share/Steam/ubuntu12_32/../ubun")                 ┬
 │jul 02 19:22:25│dbus-daemon[2514]     │[session uid=1000 pid=2514] Activating service name='org.gnome.ScreenSaver' requested by ':1.144' (uid=1000 pid=4341 comm="/home/luana/.local/share/Steam/ubuntu12_32/../ubun")                 │
 │jul 02 19:22:25│dbus-daemon[2514]     │[session uid=1000 pid=2514] Activating service name='org.gnome.ScreenSaver' requested by ':1.144' (uid=1000 pid=4341 comm="/home/luana/.local/share/Steam/ubuntu12_32/../ubun")                 │
 │jul 02 19:22:28│kernel                │traps: steamwebhelper[4138] trap invalid opcode ip:7f86113db794 sp:7fff9f5686a0 error:0 in libcef.so[7f860eaef000+7770000]                                                                      ┴
 │jul 02 19:22:29│systemd-coredum[4435] │Process 4138 (steamwebhelper) of user 1000 dumped core.                                                                                                                                         │
 │jul 02 19:22:29│drkonqi-coredum[4436] │"/home/luana/.local/share/Steam/ubuntu12_64/steamwebhelper" 4138 "/var/lib/systemd/coredump/core.steamwebhelper.1000.73defe08011544b8a54fa9222e25b4df.4138.1688336548000000.zst"                │
 │jul 02 19:22:39│systemd-coredum[4807] │Process 4482 (steamwebhelper) of user 1000 dumped core.                                                                                                                                         │
 │jul 02 19:22:39│drkonqi-coredum[4808] │"/home/luana/.local/share/Steam/ubuntu12_64/steamwebhelper" 4482 "/var/lib/systemd/coredump/core.steamwebhelper.1000.73defe08011544b8a54fa9222e25b4df.4482.1688336559000000.zst"                │
 │jul 02 19:22:49│systemd-coredum[4955] │Process 4820 (steamwebhelper) of user 1000 dumped core.                                                                                                                                         │
 │jul 02 19:22:50│drkonqi-coredum[4957] │"/home/luana/.local/share/Steam/ubuntu12_64/steamwebhelper" 4820 "/var/lib/systemd/coredump/core.steamwebhelper.1000.73defe08011544b8a54fa9222e25b4df.4820.1688336569000000.zst"`

Trying to run the steamwebhelper also errors on libcef.so: 
`/home/luana/.local/share/Steam/ubuntu12_64/steamwebhelper: error while loading shared libraries: libcef.so: cannot open shared object file: No such file or directory
`

Running with -bigpicture I get the same result as you do too.

However, one thing seems to work: if I open Steam's old UI instead of the new one with `steam -vgui`, it launches fine and the UI works! Can you try that? (Tho I'm sure the old UI won't stay forever so we do need a fix lol)

**Comment by nickonegen** [comment]
> However, one thing seems to work: if I open Steam's old UI instead of the new one with `steam -vgui`, it launches fine and the UI works! Can you try that? (Tho I'm sure the old UI won't stay forever so we do need a fix lol)

Thanks, running `steam -vgui` got at least the old GUI to open!

However, it felt slow and attempting to change "Steam Library Folders" setting reloaded the entire GUI. As my games are installed in a non-default location and my settings were reset, I cannot run anything.

(( More possibly related issues: #9383 (diff: Flatpak, opt) and #9706 (diff: KDE) ))

**Comment by LuNeder** [comment]
Okay yeah we surely have the same problem then!

For me, the friends window on -vgui tells me I'm offline (I'm clearly not, even updating games in Steam itself work witgh -vgui). Tho I did not try to actually launch any games yet lol.

Leaving my logs here too since we do have the same problem: [logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11931685/logs.tar.gz)

I'm on OpenSUSE Tumbleweed, XFCE and NVidia 1070Ti

**Comment by grillo-delmal** [comment]
I'm having the same issues as @nickonegen , I think the only differ in our hardware

<details>
<summary> <code>inxi -F</code> </summary>

```
System:
  Host: rivaia Kernel: 6.3.8-200.fc38.x86_64 arch: x86_64 bits: 64
    Desktop: GNOME v: 44.2 Distro: Fedora release 38 (Thirty Eight)
Machine:
  Type: Desktop Mobo: MSI model: Z97 GAMING 7 (MS-7916) v: 1.0
    serial: <superuser required> UEFI-[Legacy]: American Megatrends v: 1.12
    date: 02/16/2016
CPU:
  Info: quad core model: Intel Core i7-4790K bits: 64 type: MT MCP cache:
    L2: 1024 KiB
  Speed (MHz): avg: 1666 min/max: 800/4400 cores: 1: 4399 2: 800 3: 800
    4: 861 5: 800 6: 800 7: 800 8: 4068
Graphics:
  Device-1: NVIDIA TU106 [GeForce RTX 2060 Rev. A] driver: nvidia v: 535.54.03
  Display: x11 server: X.Org v: 1.20.14 with: Xwayland v: 22.1.9 driver: X:
    loaded: nvidia gpu: nvidia,nvidia-nvswitch resolution: 1: 1920x1080~60Hz
    2: 1920x1080~60Hz
  API: OpenGL v: 4.6.0 NVIDIA 535.54.03 renderer: NVIDIA GeForce RTX
    2060/PCIe/SSE2
Audio:
  Device-1: Intel 9 Series Family HD Audio driver: snd_hda_intel
  Device-2: NVIDIA TU106 High Definition Audio driver: snd_hda_intel
  Device-3: Jieli USBAudio2.0
    driver: hid-generic,snd-usb-audio,usb-storage,usbhid type: USB
  Device-4: Razer USA Seiren Mini driver: hid-generic,snd-usb-audio,usbhid
    type: USB
  API: ALSA v: k6.3.8-200.fc38.x86_64 status: kernel-api
  Server-1: PipeWire v: 0.3.72 status: active
Network:
  Device-1: Qualcomm Atheros Killer E220x Gigabit Ethernet driver: alx
  IF: enp5s0 state: up speed: 1000 Mbps duplex: full mac: 44:8a:5b:d5:f1:a2
Drives:
  Local Storage: total: 3.17 TiB used: 203.74 GiB (6.3%)
  ID-1: /dev/sda vendor: Western Digital model: WD Green 2.5 480GB
    size: 447.13 GiB
  ID-2: /dev/sdb vendor: Western Digital model: WD10EZEX-08M2NA0
    size: 931.51 GiB
  ID-3: /dev/sdc vendor: Western Digital model: WD20EZAZ-00L9GB0
    size: 1.82 TiB
Partition:
  ID-1: / size: 446.11 GiB used: 12.52 GiB (2.8%) fs: btrfs dev: /dev/dm-0
  ID-2: /boot size: 973.4 MiB used: 668 MiB (68.6%) fs: ext4 dev: /dev/sda2
  ID-3: /home size: 1.82 TiB used: 190.57 GiB (10.2%) fs: btrfs
    dev: /dev/dm-1
  ID-4: /opt size: 1.82 TiB used: 190.57 GiB (10.2%) fs: btrfs
    dev: /dev/dm-1
  ID-5: /var size: 1.82 TiB used: 190.57 GiB (10.2%) fs: btrfs
    dev: /dev/dm-1
Swap:
  ID-1: swap-1 type: zram size: 8 GiB used: 0 KiB (0.0%) dev: /dev/zram0
Sensors:
  System Temperatures: cpu: 43.0 C mobo: N/A gpu: nvidia temp: 54 C
  Fan Speeds (RPM): N/A gpu: nvidia fan: 0%
Info:
  Processes: 362 Uptime: 48m Memory: available: 31.27 GiB
  used: 4.07 GiB (13.0%) Shell: Bash inxi: 3.3.27
```
</details>

**Comment by fr33zing** [comment]
I was able to get Steam to launch normally without `-vgui` by deleting `~/.local/share/Steam`

**Comment by nickonegen** [comment]
> I'm having the same issues as nickonegen, I think we only differ in our hardware – @grillo-delmal

Right, so far this (or similar) issue was see on various DEs (GNOME<sup>[1] [3]</sup>, KDE<sup>[4] [6]</sup>, XFCE<sup>[2]</sup>) and distros, (Fedora<sup>[1] [3] [4]</sup>, Ubuntu<sup>[5]</sup>, openSUSE<sup>[2]</sup>, Arch<sup>[7]</sup>), even on the Flatpak<sup>[8]</sup> release – but all affected systems have a NVIDIA GPU of generation GeForce 900 or younger. I haven't seen a report of someone with older GPU or a non-NVIDIA GPU have this problem.

Perhaps the [label:NVIDIA drivers](https://github.com/ValveSoftware/steam-for-linux/labels/NVIDIA%20drivers) could be applied to this issue?

Can't speak for all distros (GPU driver version isn't shown in most issues) but at least for Fedora, I can safely say that all these GPUs use the `akmod-nvidia` driver from RPMFusion (v535.54.03). I looked for an alike Fedora issue that would have a different version, but found none. If I get desperate, I will meddle with that as well, but I'd prefer not doing that… 😓

Now, I am by no means an expert in this field, but if they \[can\] use the same driver, they can't be all that different, and might be possibly the same in eyes of apps like Steam. A wild guess for sure, but it paints a picture in where the issue may hide.

[1]: https://github.com/ValveSoftware/steam-for-linux/issues/9780#op-sys "@onegen"
[2]: https://github.com/ValveSoftware/steam-for-linux/issues/9780#issuecomment-1616954238 "@LuNeder"
[3]: https://github.com/ValveSoftware/steam-for-linux/issues/9780#issuecomment-1617149583 "@grillo-delmal"
[4]: https://github.com/ValveSoftware/steam-for-linux/issues/9706 "@salarua"
[5]: https://github.com/ValveSoftware/steam-for-linux/issues/9706#issuecomment-1605992509 "@Villaton"
[6]: https://github.com/ValveSoftware/steam-for-linux/issues/9706#issuecomment-1609256395 "@ntm"
[7]: https://github.com/ValveSoftware/steam-for-linux/issues/9706#issuecomment-1615521406 "@vityafx"
[8]: https://github.com/ValveSoftware/steam-for-linux/issues/9383 "@koresh-krasa"

**Comment by nickonegen** [comment]
> I was able to get Steam to launch normally without `-vgui` by deleting `~/.local/share/Steam` — @fr33zing 

While I [tried](#op-attempts) this, I decided to give it another shot, and I found *something*.

Removing `~/.local/share/Steam` (further referred to as the Steam directory) worked **sometimes** to get it running. Removed it, tried running `steam` via terminal, and it worked without the [performance and crashing issues](https://github.com/ValveSoftware/steam-for-linux/issues/9780#issuecomment-1616939803) as `-vgui`. Then I tried opening it using the icon (`.desktop`) and everything was as normal – no window, live-die loop of `steamwebhelper`. Wiping the Steam directory again allowed `steam` to be ran from the terminal once more.

However after a few attempts, not even `rm -Rf ~/.local/share/Steam` got it running again. It re-downloaded everything but hung at the same spot once more. Can't say I have made any other changes, I only tried experimenting with removing individual subfolders. Not even a full reinstall with `sudo dnf remove steam` helped. Given how many symlinks are in that directory, I can't say I am surprised. 😅

I will continue experimenting with it, but so far, only `steam -vgui` works.

**Comment by cyrasil** [comment]
> > @grillo-delmal: I'm having the same issues as nickonegen, I think we only differ in our hardware
> 
> Right, so far this (or similar) issue was see on various DEs (GNOME[1](https://github.com/ValveSoftware/steam-for-linux/issues/9780#op-sys) [3](https://github.com/ValveSoftware/steam-for-linux/issues/9780#issuecomment-1617149583), KDE[4](https://github.com/ValveSoftware/steam-for-linux/issues/9706) [6](https://github.com/ValveSoftware/steam-for-linux/issues/9706#issuecomment-1609256395), XFCE[2](https://github.com/ValveSoftware/steam-for-linux/issues/9780#issuecomment-1616954238)) and distros, (Fedora[1](https://github.com/ValveSoftware/steam-for-linux/issues/9780#op-sys) [3](https://github.com/ValveSoftware/steam-for-linux/issues/9780#issuecomment-1617149583) [4](https://github.com/ValveSoftware/steam-for-linux/issues/9706), Ubuntu[5](https://github.com/ValveSoftware/steam-for-linux/issues/9706#issuecomment-1605992509), openSUSE[2](https://github.com/ValveSoftware/steam-for-linux/issues/9780#issuecomment-1616954238), Arch[7](https://github.com/ValveSoftware/steam-for-linux/issues/9706#issuecomment-1615521406)), even on the Flatpak[8](https://github.com/ValveSoftware/steam-for-linux/issues/9383) release – but all affected systems have a NVIDIA GPU in the [GeForce 900](https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units#GeForce_900_series) generation or younger. I haven't seen a report of someone with older GPU or a non-NVIDIA GPU have this problem.

I have similar (Don't want to say "same" yet, because I have not read through all the posts carefully), issue with Arch+i3wm+amd RX6600 GPU. Ussually some variation of the following sequence gets the steam running, but it requires several tries: `steam-native, steam-runtime, steam -vgui -bigpicture`.

**Comment by LuNeder** [comment]
Quoting someone from NVidia in some discord group: “from what I could see it looks like it might be a race condition in CEF”

So it makes sense that -vgui launches, since it didn’t use CEF while the new UI is apparently made in HTML and uses CEF for **everything**.

**Comment by grillo-delmal** [comment]
I opened my steam client again with the `-vgui` flag and was able to download an update (from the beta branch) that fixed the problem for me.

**Comment by LuNeder** [comment]
> I opened my steam client again with the `-vgui` flag and was able to download an update (from the beta branch) that fixed the problem for me.

I’ve opened with -vgui and joined the beta, but the problem persists when not using -vgui for me.

**Comment by grillo-delmal** [comment]
disregard what I said, the problem persists. It's just that if I leave the big picture looping like how @nickonegen showed at some point at random it starts normally if you leave it looping, but when you start a game it starts looping again and the game ends up being unplayable... at least -vgui works and now I can open the game options panel there, which was actually a problem until now.

**Comment by LuNeder** [comment]
After joining the beta yesterday night, I booted my PC today and Steam is indeed working without -vgui lol (kinda laggy tho)

**Comment by mabenson00** [comment]
not working even with the beta for me.

**Comment by Kizaing** [comment]
Did a dnf update today and I'm hit with the exact same issue :( running with flatpak steam, I was able to get in with the -vgui flag but it seems to have no network connectivity. The new UI or big picture mode won't launch at all, just stuck in a loop

**Comment by dealend** [comment]
With an RTX 3080, this was what I had to do to get steam working properly

1) Open terminal and `steam -vgui`
2) Steam > Settings > Interface, then disable hardware accelerated web views
3) In terminal do `steam --reset`
4) Once steam launches, close it fully
5) In terminal `sudo rm -r ~/.cache/nvidia/GLCache`
5) Steam should now keep launching normally

**Comment by RustyReich** [comment]
> With an RTX 3080, this was what I had to do to get steam working properly
> 
>     1. Open terminal and `steam -vgui`
> 
>     2. Steam > Settings > Interface, then disable hardware accelerated web views
> 
>     3. In terminal do `steam --reset`
> 
>     4. Once steam launches, close it fully
> 
>     5. In terminal `sudo rm -r ~/.cache/nvidia/GLCache`
> 
>     6. Steam should now keep launching normally
> 
> 
> Edit: On x11 with 535 drivers

Can confirm, this appears to have fixed the issue for me, at least for the time being, on a GTX 1070.

**Comment by Kizaing** [comment]
> With an RTX 3080, this was what I had to do to get steam working properly
> 
>     1. Open terminal and `steam -vgui`
> 
>     2. Steam > Settings > Interface, then disable hardware accelerated web views
> 
>     3. In terminal do `steam --reset`
> 
>     4. Once steam launches, close it fully
> 
>     5. In terminal `sudo rm -r ~/.cache/nvidia/GLCache`
> 
>     6. Steam should now keep launching normally
> 
> 
> Edit: On x11 with 535 drivers

No dice for me :( RTX 3060 on driver 535, Fedora 38

**Comment by grillo-delmal** [comment]
> With an RTX 3080, this was what I had to do to get steam working properly
> 
> 1. Open terminal and `steam -vgui`
> 2. Steam > Settings > Interface, then disable hardware accelerated web views
> 3. In terminal do `steam --reset`
> 4. Once steam launches, close it fully
> 5. In terminal `sudo rm -r ~/.cache/nvidia/GLCache`
> 6. Steam should now keep launching normally
> 
> Edit: On x11 with 535 drivers

It fixed the problem for me too, (I skipped step 3 though)

**Comment by nickonegen** [comment]
> from [#9780 (comment)](https://github.com/ValveSoftware/steam-for-linux/issues/9780#issuecomment-1622073358):
> &emsp;5. In terminal `sudo rm -r ~/.cache/nvidia/GLCache`

Apologies for the late reply, but I wanted to test things out before replying. The command `sudo rm -r ~/.cache/nvidia/GLCache` didn’t do anything, because like @vityafx, I didn't have the folder there at all. <sup>(also, why `sudo`?)</sup>

With `locate`, I found the folder to be in `~/.nv/GLCache`. 

And sure enough, after wiping this folder, it looks like it worked!

1. Launched `steam -vgui` via terminal
2. Opted into Steam Beta Update<sup>(not sure if necessary?)</sup>
3. Disabled GPU-accelerated web rendering
4. Close Steam, wait until the Steam process fully exits
5. `rm -r ~/.nv/GLCache`
6. Normal Steam should work now.

Steam now seems to work correctly via terminal and .desktop link. I restarted it several times to confirm, and for now, it looks like it… just works! `steam --reset` was not necessary.

I wonder why the folder difference – according to [NVIDIA Dev-Guide](https://developer.nvidia.com/docs/drive/drive-os/latest/linux/sdk/common/topics/graphics_content/AutomaticShaderCache8.html), **`~/.nv`** should be the default folder for NVIDIA shader cache (but it can be changed by setting the `$__GL_SHADER_DISK_CACHE_PATH` variable). Not sure if it’s distro repack difference or we just installed things differently…?

Quick sidenote: I noticed that I was able to run all games and even the GUI using Lutris, and I couldn’t for a long time figure out what was different. Well, if the GLCache was at fault, Lutris had to do something with or around that – and it looks like it just straight up used its own cache in `~/.cache/lutris/shaders/steam/GLCache`.

On the Beta Update (steam-runtime_0.20230509.49499), I re-enabled "GPU-accelerated web rendering", and so far it looks like it works without problems – though I won’t be surprised if it broke in a few restarts, I’ll update this post if that happens.

**Comment by Drogobo** [comment]
Mine is still broken after trying everyone's advice. I am an arch user on latest everything with a 2070 super.

**Comment by JackLeEmmerdeur** [comment]
@Drogobo 
I tend to believe the solution posted by @nickonegen works for me on kernel 6.4.1-arch2-1 and nvidia-dkms 535.54.03. I've done nothing before that but a reinstall of the drivers after a failed downgrade to 530.41.03 (the downgrade can't compile the dkms for kernel 6.4.1 anymore).

Have you tried steam-native or steam -vgui from console? 
There are a few red herrings in the output but I had an "terminate called after throwing an instance of 'dxvk::DxvkError" at some point which I fixed by putting VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json in /etc/environment.
If you think you found an error, maybe create a gist of it and post the link here.

**Comment by IBBoard** [comment]
I seem to be hitting this on openSUSE Tumbleweed. With updates up to Friday last week, it worked if I just disabled hardware acceleration. With today's updates it only works with `-vgui`.

I've tried https://github.com/ValveSoftware/steam-for-linux/issues/9780#issuecomment-1623489003 and it didn't work for me. I've tried a couple of CEF switches, which don't fix the crash but sometimes change the sandboxing message. I've tried a `steam --reset` and still getting the crash loop after logging in again.

NVidia 535.54.03, kernel 6.3.9-1, glibc-2.37-4.4 and Steam 1.0.0.78 by the RPM, 1687386907 by the UI. Steam Beta isn't any different.

**Comment by Drogobo** [comment]
I don't know about what everyone else's type of glitch is, but mine is really screwed. `steam -vgui` crashes xorg whenever I open a game. The regular one is even worse; I will just run `steam`, and xorg will kill itself. I am on the currently-available newest version of the kernel and drivers for Arch Linux.

**Comment by xi-pinmping** [comment]
I'm on arch as well with the newest nvidia drivers and can't start steam through the command line, using -vgui, native or anything else mentioned in this thread. Unfortunately I just scrolled all the way through.

**Comment by IBBoard** [comment]
It was there (not in .cache), and deleting didn't change anything. Still won't open unless I use -vgui.

I'll try checking other locations later on case there's another cache that Steam is using.

**Comment by IBBoard** [comment]
Ahah! `~/.cache/.nv/GLCache` on openSUSE Tumbleweed. Steam opens with the new UI. The `.nv` directory existed, but doesn't seem to have anything later than 2018.

As a user, I like the idea of it cleaning up the cache.

But as an occasional developer and packager then I know that's a PITA and don't think it's a great idea. It would be better if the code automatically invalidated the cache to prevent whatever problem this was, rather than having to forcefully delete it on package update etc.

**Comment by Drogobo** [comment]
I don't know why, but clearing my nvidia cache doesn't do anything to help my issue.

**Comment by Veronicap98** [comment]
Wiping GLCache worked for me. 

Garuda Linux, 6.4.1-zen2-1-zen, nvidia version 535.54.03-1

Simply erased all the contents of ~/.cache/nvidia/GLCache, did nothing else, Steam works perfectly now.

**Comment by spoolcron** [comment]
Arch Linux / 2070S user.

Found my solution here [https://bugs.archlinux.org/task/79006](url)

`Installing our lib32-libnm to avoid the old one from the runtime also avoids the crash.`

**Comment by ViNi-Arco** [comment]
@spoolcron 
> Arch Linux / 2070S user.
> 
> Found my solution here [https://bugs.archlinux.org/task/79006](https://github.com/ValveSoftware/steam-for-linux/issues/url)
> 
> > "Installing our lib32-libnm to avoid the old one from the runtime also avoids the crash."

That was it, thank you very much! the **lib32-libgudev 237-2 -> 238-1** update that broke Steam starting on Archlinux. if you don't want to downgrade **lib32-libgudev**, installing **lib32-libnm** will work fine too.

**lib32-gst-plugins-good** pulls **lib32-libgudev** as dependency if you don't know how it got on your system.

**Comment by xi-pinmping** [comment]
I have searched my whole system for the GLCache and removed all to no avail. Installing lib32-libudev0-shim, lib32-libnm, and downgrading lib32-libgudev has not worked. I cannot get to the menu to disable hardware acceleration using any of the listed options on both runtime and native.

**Comment by Co3co** [comment]
Removing GLCache fixed it for me. The only thing is, I have to do it every time I try to launch Steam, which isn't really a problem as I can use an alias to do both.

**Comment by gotama** [comment]
> Removing GLCache fixed it for me. The only thing is, I have to do it every time I try to launch Steam, which isn't really a problem as I can use an alias to do both.

Did you switch off hard ware acceleration for WebView in steam settings?

**Comment by steffenWi** [comment]
Thank you. Executing
`
cd /var/cache/pacman/pkg/
pacman -U ./libgudev-237-2-x86_64.pkg.tar.zst ./lib32-libgudev-237-2-x86_64.pkg.tar.zst`

fixed it. Was able to launch Steam immediately after executing that command.

> I have searched my whole system for the GLCache and removed all to no avail. Installing lib32-libudev0-shim, lib32-libnm, and downgrading lib32-libgudev has not worked. I cannot even get to the menu to disable hardware acceleration using any of the listed options on both runtime and native.

**Comment by ipaqmaster** [comment]
`steam -vgui` seemed to do the trick for me (3900x, 2080Ti, nvidia-535.54.03). Followed up with killing it and running `rm -r ~/.nv/GLCache`. After that I was able to launch Steam via its start menu shortcut again as normal.

**Comment by maxpain** [comment]
The same problem in Docker on Ubuntu 22.04 and 23.04 with 535 Nvidia drivers.

**Comment by carlos-aurelio** [comment]
> And sure enough, after wiping this folder, it looks like it worked!
> 
>     1. Launched `steam -vgui` via terminal
> 
>     2. Opted into Steam Beta Update(not sure if necessary?)
> 
>     3. Disabled GPU-accelerated web rendering
> 
>     4. Closed Steam, wait until the Steam process fully exits
> 
>     5. `rm -r ~/.nv/GLCache`
> 
>     6. Steam worked properly now!

Works for me but I need to remove the GLCache everytime before I start Steam

**Comment by Reger95** [comment]
For AMD GPU users you can have a try as below:
If amdgpu stack has been installed already do what as below:
```$ sudo amdgpu-uninstall```
```$ sudo amdgpu-install --usecase=graphics --vulkan=pro```
If amdgpu stack has not been installed, Install amdgpu stack according to https://amdgpu-install.readthedocs.io/en/latest/preamble.html
Attention: ```--usecase``` don't use ```workstation``` option.
After above, reboot your machine.
Though something maybe changed but it works for me.

**Comment by ragardner** [comment]
I am also having this issue, amd gpu pop os. The only way I can get steam to run normally is by installing the flatpak version and then clicking open from within pop shop

**Comment by garrett** [comment]
It seems like I'm having this issue too, on an AMD 7900 XTX on Fedora Silverblue 38. I can no longer run the Steam from Flatpak from GNOME. It works from the terminal, oddly, if I do `flatpak run com.valvesoftware.Steam` or if I rebase to Kinoite and run it from KDE.

The workarounds listed above don't seem to work for me.

I even went as far as rebuilding my Steam configs in `~/.var/app/com.valvesoftware.Steam/` completely from scratch (including re-adding games... sigh). It's still broken.

**Comment by kisak-valve** [comment]
Hello @garrett, that set of symptoms makes your issue #9383.

**Comment by garrett** [comment]
@kisak-valve Thanks! Yeah, that's exactly my issue. I just got a new computer and this one has integrated graphics as well as the 7900. (My last only had a PCI GPU.)

**Comment by EntityinArray** [comment]
1. Shutting down Steam entirely
2. Go to ~/.cache/nvidia/GLCache
3. Delete everything there (you will see a bunch of files with hex gibberish)
4. Launch Steam, it worked in my case after that

I think this is NVIDIA driver bug, not Steam's fault.
I recently bought my first NVIDIA card, spent hours trying to set everything up on Arch Linux and stumbled upon this and now i'm dissapointed. All other GPUs work fine on Linux, what's wrong NVIDIA?

**Comment by Hains** [comment]
Fix for Ubuntu 23.04(wayland) which worked for me. 

-Remove 525 drivers with:

sudo apt-get remove --purge '^nvidia-.*'

Install 535.54.03 drivers.

DONT  run 'apt autoremove' after 'apt ugrade'.

`Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  libnvidia-egl-wayland1
Use 'sudo apt autoremove' to remove it.
`

Otherwise steam wont launch again.

**Comment by kisak-valve** [comment]
When it comes available via your distro's normal update process, please retest with the NVIDIA 535.86.05 release.

**Comment by gvuyk** [comment]
Hit this while running Steam with KVM (single Nvidia GPU on the host, no pass-through, running Ubuntu 22.04 on both host and guest),
Solved it with https://github.com/ValveSoftware/steam-for-linux/issues/9780#issuecomment-1623489003  
(had to remove the mentioned cache files from the host)

**Comment by PedroMerinoDev** [comment]
Disabling Secure Boot worked for me.

Secure Boot can cause issues with drivers. If you have Secure Boot enabled in your BIOS/UEFI, temporarily disable it and restart the system to see if the problem persists.

**Comment by PedroMerinoDev** [comment]
Disabling Secure Boot worked for me.

In my case, the NVIDIA driver version 535 was not being loaded correctly.

**Comment by bahman5679** [comment]
Steam for me crashes and reopens repetitively when I lunch it from the desktop but works perfectly when I run it from the terminal. I tried all solutions in here but I didn't have any luck. My OS is Garuda Dr460nized gaming edition and my GPU is NVIDIA GeForce MX330. By the way, I didn't install the Nvidia driver.

**Comment by kisak-valve** [comment]
Hello @bahman5679, you've described the issue being tracked being tracked at #9383.

**Comment by bahman5679** [comment]
Thank you very much @kisak-valve. That resolved a part of my problem.

**Comment by major0** [comment]
>     1. Launched `steam -vgui` via terminal
>     2. Opted into Steam Beta Update(not sure if necessary?)
>     3. Disabled GPU-accelerated web rendering
>     4. Closed Steam, wait until the Steam process fully exits
>     5. `rm -r ~/.nv/GLCache`
>     6. Steam worked properly now!

This solution was almost 100% spot on for me, though I did find that my GLCache was in `~/.AMD/GLCache`.

I ended up needing to do `find ~/.[a-zA-Z]* -name GLCache` to locate it.

**Comment by benuski** [comment]
> libnvidia-egl-wayland1

Reinstalling this package on Pop_OS 22.04 resolved the problem for me more than all of the other steps.

**Comment by MatteoGioia** [comment]
Removing GLCache files inside `home/your_username/.var/app/com.valvesoftware.Steam/.cache/nvidia/GLCache` worked for me on Fedora 37 with nvidia driver 535.54.03.

**Comment by JumperLuko** [comment]
Not working with vnc servers like thinlinc

**Comment by Hains** [comment]
> When it comes available via your distro's normal update process, please retest with the NVIDIA 535.86.05 release.

Ubuntu 23.04
Updating driver to 535.86.05
libnvidia-egl-wayland1 still incorrectly marked as 'not required'.
After re-installing  of libnvidia-egl-wayland1 notification gone.
Steam working.

**Comment by anansivanir** [comment]
Still not able to start with freshly installed Fedora38. Webhelper crashes and steam windows either don't open or open only as "reservations" showing sometimes a rectangle with garbled contents or a white bacground. Tested with XFCE and Gnome and behaviour is pretty much the same. Cleaning up nvidia cache did nothing and it didn't get recreated afterwards. Different command line options do not seem to have any effect to behaviour.

Kernel: Linux 6.4.9-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Aug  8 21:21:11 UTC 2023 x86_64 GNU/Linux

lspci: 01:00.0 VGA compatible controller: NVIDIA Corporation TU104 [GeForce RTX 2070 SUPER] (rev a1)
	Kernel driver in use: nvidia
	Kernel modules: nouveau, nvidia_drm, nvidia

Installed packages for NVidia:
xorg-x11-drv-nvidia-kmodsrc-535.86.05-1.fc38.x86_64
xorg-x11-drv-nvidia-cuda-libs-535.86.05-1.fc38.x86_64
xorg-x11-drv-nvidia-libs-535.86.05-1.fc38.i686
xorg-x11-drv-nvidia-libs-535.86.05-1.fc38.x86_64
akmod-nvidia-535.86.05-1.fc38.x86_64
nvidia-settings-535.86.05-1.fc38.x86_64
xorg-x11-drv-nvidia-power-535.86.05-1.fc38.x86_64
xorg-x11-drv-nvidia-535.86.05-1.fc38.x86_64
kmod-nvidia-6.4.7-200.fc38.x86_64-535.86.05-1.fc38.x86_64
kmod-nvidia-6.4.8-200.fc38.x86_64-535.86.05-1.fc38.x86_64
nvidia-persistenced-535.86.05-1.fc38.x86_64
xorg-x11-drv-nvidia-cuda-libs-535.86.05-1.fc38.i686
xorg-x11-drv-nvidia-cuda-535.86.05-1.fc38.x86_64
nvidia-vaapi-driver-0.0.10-1.fc38.x86_64
kmod-nvidia-6.4.9-200.fc38.x86_64-535.86.05-1.fc38.x86_64
nvidia-gpu-firmware-20230804-153.fc38.noarch

Installed packages for Steam:
purple-libsteam-1.7.1-4.fc38.x86_64
pidgin-libsteam-1.7.1-4.fc38.noarch
python3-steam-1.4.4-1.fc38.noarch
steam-devices-1.0.0.78-1.fc38.i686
steam-1.0.0.78-1.fc38.i686

Ps: At the same time Steam works properly on my laptop with Fedora 38 and AMD Ryzen5 and Radeon graphics card.

**Comment by SamVanheer** [comment]
I'm encountering this issue in a VirtualBox 7.0.10 VM using Ubuntu 22.04, freshly installed. Guest Additions are installed.

The main window doesn't show, but i can open Friends and Settings and the update news window also shows up. The main window exists but it's completely invisible.

![image](https://github.com/ValveSoftware/steam-for-linux/assets/5501383/6cc952bd-82bc-4e7b-93ab-219484285d57)

Interface settings:
![image](https://github.com/ValveSoftware/steam-for-linux/assets/5501383/5d729423-cb75-4d0b-ae68-d39c1f8726eb)

I disabled "Enable GPU accelerated rendering in web views" but this didn't change things.

It takes a couple minutes for these other windows to show up.

<details>
<summary>Complete command line output:</summary>

solokiller@solokiller-VirtualBox:~$ steam --beta
steam.sh[5459]: Running Steam on ubuntu 22.04 64-bit
steam.sh[5459]: STEAM_RUNTIME is enabled automatically
setup.sh[5576]: Steam runtime environment up-to-date!
steam.sh[5459]: Steam client's requirements are satisfied
[2023-08-12 23:28:00] Startup - updater built Jul 28 2023 18:44:09
[2023-08-12 23:28:00] Startup - Steam Client launched with: '/home/solokiller/.local/share/Steam/ubuntu12_32/steam' '--beta'
08/12 23:28:00 Init: Installing breakpad exception handler for appid(steam)/version(1690583737)/tid(5652)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2023-08-12 23:28:00] Loading cached metrics from disk (/home/solokiller/.local/share/Steam/package/steam_client_metrics.bin)
[2023-08-12 23:28:00] Using the following download hosts for Public, Realm steamglobal
[2023-08-12 23:28:00] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2023-08-12 23:28:00] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2023-08-12 23:28:00] 3. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-08-12 23:28:00] Checking for update on startup
[2023-08-12 23:28:00] Checking for available updates...
[2023-08-12 23:28:00] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12
[2023-08-12 23:28:00] Manifest download: send request
[2023-08-12 23:28:00] Manifest download: waiting for download to finish
[2023-08-12 23:28:01] Manifest download: finished
[2023-08-12 23:28:01] Download skipped: /steam_client_ubuntu12 version 1690583737, installed version 1690583737, existing pending version 0
[2023-08-12 23:28:01] Nothing to do
[2023-08-12 23:28:01] Verifying installation...
[2023-08-12 23:28:01] Performing checksum verification of executable files
[2023-08-12 23:28:02] Verification complete
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf63be9c0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf63bd1f0
/usr/share/themes/Yaru/gtk-2.0/main.rc:775: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Yaru/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
GetWin32Stats: display was not open yet, good
GetWin32Stats: display was not open yet, good
steamwebhelper.sh[5690]: Runtime for steamwebhelper: defaulting to /home/solokiller/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[5690]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
CAppInfoCacheReadFromDiskThread took 101 milliseconds to initialize
BRefreshApplicationsInLibrary 1: 1ms
BuildCompleteAppOverviewChange: 378 apps
RegisterForAppOverview 1: 32ms
RegisterForAppOverview 2: 32ms
[2023-08-12 23:30:03] Background update loop checking for update. . .
[2023-08-12 23:30:03] Checking for available updates...
[2023-08-12 23:30:03] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12?t=660354414
[2023-08-12 23:30:03] Manifest download: send request
[2023-08-12 23:30:03] Manifest download: waiting for download to finish
[2023-08-12 23:30:04] Manifest download: finished
[2023-08-12 23:30:04] Download skipped by HTTP 304 Not Modified
[2023-08-12 23:30:04] Nothing to do
</details>

I tried to opt into the current beta with `--beta` but i doubt this option exists.

**Comment by kisak-valve** [comment]
Hello @SamVanheer, it's likely you're seeing the issue being tracked at #9752.

**Comment by SamVanheer** [comment]
Looks like it, thanks for the information.

**Comment by liamwerk7676** [comment]
i have the same isue however opening steam truh the terminal somtimes makes it work idk how it fixes it

**Comment by kisak-valve** [comment]
Hello @liamwerk7676, you've symptomatically described #9383.

**Comment by salmmm22** [comment]
What worked for me was to type the following to run Steam:
~$ <code>steam -no-cef-sandbox</code>

**Comment by weirdsmiley** [comment]
I was facing the same issue, and I believe disabling GPU-accelerated web rendering, would solve the issue. To disable it via cmdline, use `steam -cef-disable-gpu`.

[Gist](https://gist.github.com/davispuh/6600880) from where I found cmdline options' details.

**Comment by CaitlinDavitt** [comment]
I am just going to add that I was having what I believe to be this same issue with an Intel igpu and the `steam -cef-disable-gpu` fix worked

**Comment by RayOfLight1** [comment]
Damn, I got a fully AMD system thus this is not exclusive to Nvidia, not even -cef-disable-gpu can make it start, I even downgraded my glibc from 2.38 to 2.37 to no avail.

**Comment by ragardner** [comment]
I also have a full AMD system and the only way I can launch steam currently is by right clicking on the icon and selecting library

**Comment by kirk-clawson** [comment]
Fedora 38/ Full AMD user here. Originally used the `-cef-disable-gpu` flag, and that got me into it, but after some other (seemingly unrelated) Game weirdness I went into my BIOS and realized that even though my Mobo was defaulting to my Radeon, the iGPU was in fact _not_ disabled. After disabling the iGPU, and only running with the discrete Radeon, I was able to turn off the flag and Steam starts up just fine after that.
Hopefully this helps someone else out there.

**Comment by vaparetia** [comment]
> I also have a full AMD system and the only way I can launch steam currently is by right clicking on the icon and selecting library
> 
> edit: I have also disabled friends and chat from opening on start although I have no idea if that makes any difference

This worked for me as well. If I start steam in the terminal, it works fine. Otherwise I get webrender errors.

**Comment by kisak-valve** [comment]
Hello @vaparetia, same as https://github.com/ValveSoftware/steam-for-linux/issues/9780#issuecomment-1676359367, you've described #9383.

**Comment by thePaulRichard** [comment]
I'm encountering this error when I don't start Steam from the terminal. Starting Steam from the terminal works fine.

```
Oct 26 22:29:20 fedora systemd[1]: systemd-coredump@5-26866-0.service: Deactivated successfully.
Oct 26 22:29:20 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@5-26866-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Oct 26 22:29:20 fedora systemd[1]: systemd-coredump@5-26866-0.service: Consumed 3.284s CPU time.
Oct 26 22:29:20 fedora audit: BPF prog-id=112 op=UNLOAD
Oct 26 22:29:20 fedora audit: BPF prog-id=111 op=UNLOAD
Oct 26 22:29:20 fedora audit: BPF prog-id=110 op=UNLOAD
Oct 26 22:29:21 fedora abrt-server[26878]: Executable '/home/paulrichard/.local/share/Steam/ubuntu12_64/steamwebhelper' doesn't belong to any package and ProcessUnpackaged is set to 'no'
Oct 26 22:29:21 fedora abrt-server[26878]: 'post-create' on '/var/spool/abrt/ccpp-2023-10-26-22:29:20.748093-25814' exited with 1
Oct 26 22:29:21 fedora abrt-server[26878]: Deleting problem directory '/var/spool/abrt/ccpp-2023-10-26-22:29:20.748093-25814'
Oct 26 22:29:24 fedora steam.desktop[26881]: steamwebhelper.sh[26881]: Runtime for steamwebhelper: defaulting to /home/paulrichard/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
Oct 26 22:29:24 fedora steam.desktop[26881]: steamwebhelper.sh[26881]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
Oct 26 22:29:26 fedora steam.desktop[22571]: BuildCompleteAppOverviewChange: 166 apps
Oct 26 22:29:26 fedora steam.desktop[22571]: RegisterForAppOverview 1: 3ms
Oct 26 22:29:26 fedora steam.desktop[22571]: RegisterForAppOverview 2: 3ms
Oct 26 22:29:27 fedora audit[26881]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=2 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=26881 comm=436F6D706F73697465205468726561 exe="/home/paulrichard/.local/share/Steam/ubuntu12_64/steamwebhelper" sig=11 res=1
Oct 26 22:29:27 fedora kernel: Composite Threa[27945]: segfault at 0 ip 0000000000000000 sp 00007fc0fd9d46b8 error 14 in steamwebhelper[400000+10000] likely on CPU 15 (core 7, socket 0)
Oct 26 22:29:27 fedora kernel: Code: Unable to access opcode bytes at 0xffffffffffffffd6.
Oct 26 22:29:27 fedora audit: BPF prog-id=113 op=LOAD
Oct 26 22:29:27 fedora audit: BPF prog-id=114 op=LOAD
Oct 26 22:29:27 fedora audit: BPF prog-id=115 op=LOAD
Oct 26 22:29:27 fedora systemd[1]: Started systemd-coredump@6-28087-0.service - Process Core Dump (PID 28087/UID 0).
Oct 26 22:29:27 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@6-28087-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Oct 26 22:29:28 fedora systemd-coredump[28088]: [🡕] Process 26881 (steamwebhelper) of user 1000 dumped core.
                                                
                                                Module libpciaccess.so.0 from rpm libpciaccess-0.16-8.fc38.x86_64
                                                Module libtinfo.so.6 from rpm ncurses-6.4-3.20230114.fc38.x86_64
                                                Module libedit.so.0 from rpm libedit-3.1-45.20221030cvs.fc38.x86_64
                                                Module libdrm_intel.so.1 from rpm libdrm-2.4.114-2.fc38.x86_64
                                                Module libdrm_nouveau.so.2 from rpm libdrm-2.4.114-2.fc38.x86_64
                                                Module libdrm_amdgpu.so.1 from rpm libdrm-2.4.114-2.fc38.x86_64
                                                Module libelf.so.1 from rpm elfutils-0.189-3.fc38.x86_64
                                                Module libdrm_radeon.so.1 from rpm libdrm-2.4.114-2.fc38.x86_64
                                                Module libsensors.so.4 from rpm lm_sensors-3.6.0-13.fc38.x86_64
                                                Module radeonsi_dri.so from rpm mesa-23.1.8-1.fc38.x86_64
                                                Module libxcb-xfixes.so.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                                                Module libxcb-sync.so.1 from rpm libxcb-1.13.1-11.fc38.x86_64
                                                Module libxcb-present.so.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                                                Module libxcb-randr.so.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                                                Module libxshmfence.so.1 from rpm libxshmfence-1.3-12.fc38.x86_64
                                                Module libXxf86vm.so.1 from rpm libXxf86vm-1.1.5-2.fc38.x86_64
                                                Module libxcb-dri2.so.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                                                Module libxcb-glx.so.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                                                Module libglapi.so.0 from rpm mesa-23.1.8-1.fc38.x86_64
                                                Module libGLX_mesa.so.0 from rpm mesa-23.1.8-1.fc38.x86_64
                                                Module libXss.so.1 from rpm libXScrnSaver-1.2.3-12.fc38.x86_64
                                                Module libudev.so.1 from rpm systemd-253.10-1.fc38.x86_64
                                                Module libdconfsettings.so from rpm dconf-0.40.0-8.fc38.x86_64
                                                Module libbrotlicommon.so.1 from rpm brotli-1.0.9-11.fc38.x86_64
                                                Module libbrotlidec.so.1 from rpm brotli-1.0.9-11.fc38.x86_64
                                                Module libbz2.so.1 from rpm bzip2-1.0.8-13.fc38.x86_64
                                                Module libgmp.so.10 from rpm gmp-6.2.1-4.fc38.x86_64
                                                Module libhogweed.so.6 from rpm nettle-3.8-3.fc38.x86_64
                                                Module libnettle.so.8 from rpm nettle-3.8-3.fc38.x86_64
                                                Module libtasn1.so.6 from rpm libtasn1-4.19.0-2.fc38.x86_64
                                                Module libunistring.so.5 from rpm libunistring-1.1-3.fc38.x86_64
                                                Module libidn2.so.0 from rpm libidn2-2.3.4-2.fc38.x86_64
                                                Module libp11-kit.so.0 from rpm p11-kit-0.25.0-1.fc38.x86_64
                                                Module libcrypto.so.3 from rpm openssl-3.0.9-2.fc38.x86_64
                                                Module libkeyutils.so.1 from rpm keyutils-1.6.1-6.fc38.x86_64
                                                Module libkrb5support.so.0 from rpm krb5-1.21-3.fc38.x86_64
                                                Module libcom_err.so.2 from rpm e2fsprogs-1.46.5-4.fc38.x86_64
                                                Module libk5crypto.so.3 from rpm krb5-1.21-3.fc38.x86_64
                                                Module libkrb5.so.3 from rpm krb5-1.21-3.fc38.x86_64
                                                Module libdatrie.so.1 from rpm libdatrie-0.2.13-5.fc38.x86_64
                                                Module libpixman-1.so.0 from rpm pixman-0.42.2-1.fc38.x86_64
                                                Module libxcb-shm.so.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                                                Module libxcb-render.so.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                                                Module libpng16.so.16 from rpm libpng-1.6.37-14.fc38.x86_64
                                                Module libxml2.so.2 from rpm libxml2-2.10.4-1.fc38.x86_64
                                                Module libgraphite2.so.3 from rpm graphite2-1.3.14-11.fc38.x86_64
                                                Module libfreetype.so.6 from rpm freetype-2.13.0-2.fc38.x86_64
                                                Module liblz4.so.1 from rpm lz4-1.9.4-2.fc38.x86_64
                                                Module libzstd.so.1 from rpm zstd-1.5.5-1.fc38.x86_64
                                                Module liblzma.so.5 from rpm xz-5.4.1-1.fc38.x86_64
                                                Module libcap.so.2 from rpm libcap-2.48-6.fc38.x86_64
                                                Module libblkid.so.1 from rpm util-linux-2.38.1-4.fc38.x86_64
                                                Module libgnutls.so.30 from rpm gnutls-3.8.1-1.fc38.x86_64
                                                Module libavahi-client.so.3 from rpm avahi-0.8-22.fc38.x86_64
                                                Module libavahi-common.so.3 from rpm avahi-0.8-22.fc38.x86_64
                                                Module libgssapi_krb5.so.2 from rpm krb5-1.21-3.fc38.x86_64
                                                Module libthai.so.0 from rpm libthai-0.1.29-4.fc38.x86_64
                                                Module libfribidi.so.0 from rpm fribidi-1.0.12-3.fc38.x86_64
                                                Module libcairo.so.2 from rpm cairo-1.17.8-4.fc38.x86_64
                                                Module libfontconfig.so.1 from rpm fontconfig-2.14.2-1.fc38.x86_64
                                                Module libharfbuzz.so.0 from rpm harfbuzz-7.1.0-1.fc38.x86_64
                                                Module libpangoft2-1.0.so.0 from rpm pango-1.50.14-1.fc38.x86_64
                                                Module libsystemd.so.0 from rpm systemd-253.10-1.fc38.x86_64
                                                Module libXau.so.6 from rpm libXau-1.0.11-2.fc38.x86_64
                                                Module libplds4.so from rpm nss-3.94.0-1.fc38.x86_64
                                                Module libplc4.so from rpm nss-3.94.0-1.fc38.x86_64
                                                Module libdrm.so.2 from rpm libdrm-2.4.114-2.fc38.x86_64
                                                Module libGLdispatch.so.0 from rpm libglvnd-1.6.0-2.fc38.x86_64
                                                Module libGLX.so.0 from rpm libglvnd-1.6.0-2.fc38.x86_64
                                                Module libselinux.so.1 from rpm libselinux-3.5-1.fc38.x86_64
                                                Module libmount.so.1 from rpm util-linux-2.38.1-4.fc38.x86_64
                                                Module libz.so.1 from rpm zlib-1.2.13-3.fc38.x86_64
                                                Module libgmodule-2.0.so.0 from rpm glib2-2.76.5-2.fc38.x86_64
                                                Module libpcre2-8.so.0 from rpm pcre2-10.42-1.fc38.1.x86_64
                                                Module libffi.so.8 from rpm libffi-3.4.4-2.fc38.x86_64
                                                Module libatspi.so.0 from rpm at-spi2-core-2.48.3-1.fc38.x86_64
                                                Module libcups.so.2 from rpm cups-2.4.7-1.fc38.x86_64
                                                Module libpango-1.0.so.0 from rpm pango-1.50.14-1.fc38.x86_64
                                                Module libpangocairo-1.0.so.0 from rpm pango-1.50.14-1.fc38.x86_64
                                                Module libasound.so.2 from rpm alsa-lib-1.2.10-2.fc38.x86_64
                                                Module libdbus-1.so.3 from rpm dbus-1.14.10-1.fc38.x86_64
                                                Module libexpat.so.1 from rpm expat-2.5.0-2.fc38.x86_64
                                                Module libXfixes.so.3 from rpm libXfixes-6.0.0-5.fc38.x86_64
                                                Module libXcursor.so.1 from rpm libXcursor-1.2.1-3.fc38.x86_64
                                                Module libxcb-dri3.so.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                                                Module libxcb.so.1 from rpm libxcb-1.13.1-11.fc38.x86_64
                                                Module libX11-xcb.so.1 from rpm libX11-1.8.7-1.fc38.x86_64
                                                Module libatk-bridge-2.0.so.0 from rpm at-spi2-core-2.48.3-1.fc38.x86_64
                                                Module libatk-1.0.so.0 from rpm at-spi2-core-2.48.3-1.fc38.x86_64
                                                Module libnspr4.so from rpm nss-3.94.0-1.fc38.x86_64
                                                Module libibus-1.0.so.5 from rpm ibus-1.5.28-6.fc38.x86_64
                                                Module libGL.so.1 from rpm libglvnd-1.6.0-2.fc38.x86_64
                                                Module libXdamage.so.1 from rpm libXdamage-1.1.5-9.fc38.x86_64
                                                Module libXcomposite.so.1 from rpm libXcomposite-0.4.5-9.fc38.x86_64
                                                Module libXrandr.so.2 from rpm libXrandr-1.5.2-10.fc38.x86_64
                                                Module libXtst.so.6 from rpm libXtst-1.2.4-2.fc38.x86_64
                                                Module libXrender.so.1 from rpm libXrender-0.9.11-2.fc38.x86_64
                                                Module libXext.so.6 from rpm libXext-1.3.5-2.fc38.x86_64
                                                Module libXi.so.6 from rpm libXi-1.8.1-1.fc38.x86_64
                                                Module libX11.so.6 from rpm libX11-1.8.7-1.fc38.x86_64
                                                Module libgio-2.0.so.0 from rpm glib2-2.76.5-2.fc38.x86_64
                                                Module libglib-2.0.so.0 from rpm glib2-2.76.5-2.fc38.x86_64
                                                Module libgobject-2.0.so.0 from rpm glib2-2.76.5-2.fc38.x86_64
                                                Stack trace of thread 27945:
                                                #0  0x0000000000000000 n/a (n/a + 0x0)
                                                ELF object binary architecture: AMD x86-64
Oct 26 22:29:28 fedora systemd[1]: systemd-coredump@6-28087-0.service: Deactivated successfully.
Oct 26 22:29:29 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@6-28087-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Oct 26 22:29:29 fedora systemd[1]: systemd-coredump@6-28087-0.service: Consumed 1.091s CPU time.
Oct 26 22:29:29 fedora audit: BPF prog-id=115 op=UNLOAD
Oct 26 22:29:29 fedora audit: BPF prog-id=114 op=UNLOAD
Oct 26 22:29:29 fedora audit: BPF prog-id=113 op=UNLOAD
Oct 26 22:29:29 fedora abrt-server[28098]: Executable '/home/paulrichard/.local/share/Steam/ubuntu12_64/steamwebhelper' doesn't belong to any package and ProcessUnpackaged is set to 'no'
Oct 26 22:29:29 fedora abrt-server[28098]: 'post-create' on '/var/spool/abrt/ccpp-2023-10-26-22:29:29.247991-26881' exited with 1
Oct 26 22:29:29 fedora abrt-server[28098]: Deleting problem directory '/var/spool/abrt/ccpp-2023-10-26-22:29:29.247991-26881'
Oct 26 22:29:34 fedora steam.desktop[28105]: steamwebhelper.sh[28105]: Runtime for steamwebhelper: defaulting to /home/paulrichard/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
Oct 26 22:29:34 fedora steam.desktop[28105]: steamwebhelper.sh[28105]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
Oct 26 22:29:36 fedora steam.desktop[22571]: BuildCompleteAppOverviewChange: 166 apps
Oct 26 22:29:36 fedora steam.desktop[22571]: RegisterForAppOverview 1: 3ms
Oct 26 22:29:36 fedora steam.desktop[22571]: RegisterForAppOverview 2: 3ms
Oct 26 22:29:36 fedora systemd[1647]: Started app-gnome-gnome\x2dsystem\x2dmonitor-29397.scope - Application launched by gsd-media-keys.
Oct 26 22:29:37 fedora audit[28105]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=2 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=28105 comm=436F6D706F73697465205468726561 exe="/home/paulrichard/.local/share/Steam/ubuntu12_64/steamwebhelper" sig=11 res=1
Oct 26 22:29:37 fedora kernel: Composite Threa[29324]: segfault at 0 ip 0000000000000000 sp 00007fe24f1576b8 error 14 in steamwebhelper[400000+10000] likely on CPU 1 (core 0, socket 0)
Oct 26 22:29:37 fedora kernel: Code: Unable to access opcode bytes at 0xffffffffffffffd6.
Oct 26 22:29:37 fedora audit: BPF prog-id=116 op=LOAD
Oct 26 22:29:37 fedora audit: BPF prog-id=117 op=LOAD
Oct 26 22:29:37 fedora audit: BPF prog-id=118 op=LOAD
Oct 26 22:29:37 fedora systemd[1]: Started systemd-coredump@7-29500-0.service - Process Core Dump (PID 29500/UID 0).
Oct 26 22:29:37 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@7-29500-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Oct 26 22:29:40 fedora systemd-coredump[29501]: [🡕] Process 28105 (steamwebhelper) of user 1000 dumped core.
```

**Comment by Data-007** [comment]
29/11/2023 I have the issue that steam either from the desktop or via a terminal crashes and burns offering(terminal) to upload crash dumps. Iam on Arch fully updated system. not sure how to progress. Have tried various things.

Onm plasma latest under wayland steam works perfectly( unfortunately my system is not stable under wayland)
Fully amd system,  any help gratefully received.
![image](https://github.com/ValveSoftware/steam-for-linux/assets/53057579/eca4dcc9-c382-41b3-a6b4-6dc300355e31)

**Comment by Seyloria** [comment]
Issue still exists for me.

My System:
AMD GPU / Fedora 39 / GNOME / Wayland

Steam starts from Desktop and closes right after beeing fully startet (can shortly see the client). It spawns alot of "steamwebhelper" (more than usual).
Starting from Terminal does fine without anything done.
Fix for me so far is disabling the "Enable GPU accelerated rendering in web views" option under Interface.

**Comment by loqster** [comment]
Same issue here. 

Fedora 38 AMD GPU

Opting into beta did not fix.

what did work was disabling the "Enable GPU accelerated rendering in web views" option under Interface

**Comment by florisdipt** [comment]
> With an RTX 3080, this was what I had to do to get steam working properly
> 
>     1. Open terminal and `steam -vgui`
> 
>     2. Steam > Settings > Interface, then disable hardware accelerated web views
> Edit: On x11 with 535 drivers

This did the trick for me.

system info:


![image](https://github.com/ValveSoftware/steam-for-linux/assets/55819399/5668ae25-886f-42c9-b74e-bc1365496962)

**Comment by hicder** [comment]
I think disabling hardware accelerated web views works.

Another alternative (which still keeps hardware accelerated web view) is:
* Go to `$HOME/.local/share/applications`
* Edit `steam.desktop`, comment out these 2 lines (by putting the hashtag in front)
``` 
# PrefersNonDefaultGPU=true
# X-KDE-RunOnDiscreteGpu=true
```

This fixes for me

**Comment by maxchop** [comment]
> Fedora 38/ Full AMD user here. Originally used the `-cef-disable-gpu` flag, and that got me into it, but after some other (seemingly unrelated) Game weirdness I went into my BIOS and realized that even though my Mobo was defaulting to my Radeon, the iGPU was in fact _not_ disabled. After disabling the iGPU, and only running with the discrete Radeon, I was able to turn off the flag and Steam starts up just fine after that. Hopefully this helps someone else out there.

This was my issue. Some further detail for anyone who comes across this as no other solutions helped since I'm fully AMD.

Lately i'd been working on setting up a GPU passthrough for Windows 10 and had the discrete GPU disabled in /etc/modprobe.d/vfio.conf and using the iGPU natively on Arch. After re-enabling the discrete GPU (removing the vfio.conf file and running mkinitcpio) and plugging in my monitors back to its ports, I forgot to isolate and disable the iGPU I was previously using. Going back and repeating the process to the iGPU fixed this issue after a reboot.

I had not tried running steam prior to this instance so I don't know if any other factors were at play.

**Comment by KenTheWhaleGoddess** [comment]
I have experienced this issue without hardware acceleration in web view. 

[inxi -F](https://gist.github.com/KenTheWhaleGoddess/3be86493fe2b5730b5a4926c64bc933a)

**Comment by Eiim** [comment]
I seem to be experiencing this issue, albiet with an extra segfault, in WSL2 (admittedly, an uncommon use case). I'm using Ubuntu 22.04, and none of the fixes mentioned so far have worked for me (so far as I'm able to try them at least, `-vgui` makes no difference so I can't opt into Beta, nor disable GPU in webview). I have an RTX 3050, although I'm not certain how that plays here. I'm redirecting GUI output to Windows via Xserv, which works fine for the couple windows Steam pops up before it fails.

Portion of CLI output:
```
Steam logging initialized: directory: /home/eiim/.steam/debian-installation/logs

XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf64e3370
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf64e1cc0
steamwebhelper.sh[22460]: Runtime for steamwebhelper: defaulting to /home/eiim/.steam/debian-installation/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[22460]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
CAppInfoCacheReadFromDiskThread took 7 milliseconds to initialize
Segmentation fault
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 22587
bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
steamwebhelper.sh[22703]: Runtime for steamwebhelper: defaulting to /home/eiim/.steam/debian-installation/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[22703]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
```

**Comment by pnlrogue1** [comment]
> Fedora 38/ Full AMD user here. Originally used the `-cef-disable-gpu` flag, and that got me into it, but after some other (seemingly unrelated) Game weirdness I went into my BIOS and realized that even though my Mobo was defaulting to my Radeon, the iGPU was in fact _not_ disabled. After disabling the iGPU, and only running with the discrete Radeon, I was able to turn off the flag and Steam starts up just fine after that. Hopefully this helps someone else out there.

This solved the issue for me (Linux Mint Edge 21.3 / Kernel 6.5 / Ryzen 7 7700X / Sapphire Radeon 7700 XT NITRO OC 12GB

Went into the BIOS, found the setting for the integrated graphics mode and set it to disabled. Steam worked immediately on reboot.

Weirdly, Steam ran find from the terminal when I invoked it with `steam` with no flags (though I didn't test any games) but when I ran it from the shortcut, it opened and crashed, then automatically opened and crash again over and over.

**Comment by KenTheWhaleGoddess** [comment]
Assert( Failed creating offscreen shared JS context ):/data/src/steamUI/steamuisharedjscontroller.cpp:546
Assert( Failed to connect to master html process, created shared memory (spawn time 60.00) ):/data/src/common/html/chrome_ipc_client.cpp:1111


These are some symptoms found during launch attempts using `steam -vgui` and some of the recommendations above related to removing caches.

**Comment by xxxx81** [comment]
For me under LMDE6 (Debian 12) it runs with the parameter "-cef-in-process-gpu" I had to try for quite a while until I found that out before it was absolutely impossible to get it to start and always hung at loading user data.

**Comment by KenTheWhaleGoddess** [comment]
Running `steam -cef-disable-gpu-compositing`  launched Steam effortlessly for me, where `steam -vgui` was not working

https://gist.github.com/davispuh/6600880?permalink_comment_id=2170633

Wish ew didnt have to go figure it out tho. :(

**Comment by KenTheWhaleGoddess** [comment]
@kisak-valve any chance you'll hire some of us on here to look at / address some of the issues seen on GitHub? We all have the time & passion to fix some of this, but we're excluded from helping.

**Comment by xxxx81** [comment]
@KenTheWhaleGoddess Nice to hear that it works. If it does not work, deactivate the internet connection, start Steam and reactivate the internet when the client tries to log in. Apparently the problem is caused by several software bugs, no wonder with the software junk that Valve delivers.

**Comment by radionaut** [comment]
add another workaround to this issue: sudo rm -r /tmp/dumps/
fedora 39

**Comment by radionaut** [comment]
add another workaround to this issue: `sudo rm -r /tmp/dumps/`
fedora 39

**Comment by wancoder** [comment]
@smcv 
Practicality is under two use cases: 
1. Reducing memory overhead (great for embedded devices), 4MB vs 8MB per thread. It could be set to 2MB with adjustments, even 512KB when you adjust the base system libraries with updated versions.
2. Forcing development of more efficient logic by constraining resources

Normally not an issue for standard installations.
So this serves as a reminder to anyone who, changed nothing and have touched their stack limits for single or multiple user environments to check it with ulimit -a. If they are running a custom sandboxing environment it could be a factor through a different security setting.

**Comment by smcv** [comment]
@kisak-valve, perhaps you could retitle this to something like "steamwebhelper crashing on Nvidia with GPU-accelerated web rendering (workaround in beta)" to narrow down its scope?

**Comment by KenTheWhaleGoddess** [comment]
Hi Kisak, thanks for keeping track of the issues. 

I am on the beta version: `Download skipped: /steam_client_publicbeta_ubuntu12 version 1715635533, installed version 1715635533, existing pending version 0` on Linux Mint 

I noticed that after I delete GLCache (`rm -rf`) then start steam, some re-appear (`~/.cache/nvidia/GLCache/...`). When I delete the contents of GLCache the second time, steam will launch.

Thanks again

**Comment by mmatviyiv** [comment]
Fixed by downloading `SDL2.dll` 64bit and placing into steamwebhelper folder `.../Steam/bin/cef/cef.win7x64`

**Comment by EOSRX24** [comment]
Same or similar issue here:

![screenshot](https://github.com/user-attachments/assets/ce523839-4ab1-4abc-88af-c0f9e3d94062)

Tried absolutely everything, no luck.

Although I found something:

[journalxe.txt](https://github.com/user-attachments/files/17564766/journalxe.txt)

**Comment by EOSRX24** [comment]
I'm not sure if it's useful.

**Comment by shazzner** [comment]
> Replying to https://github.com/ValveSoftware/steam-for-linux/issues/9780#issuecomment-1930782468

Same symptoms and can confirm this was the solution for me too. For some reason Steam was detecting an iGPU and getting confused attempting to use that to launch steam with the steam launcher. Previously, running steam from the command line worked just fine.
