### ISSUE TITLE
New Steam UI is slow and unresponsive and lags entire system

### ISSUE THREAD

**Issue by Skrappjaw** [ValveSoftware/steam-for-linux#9960]
#### Your system information

* Steam client version (build number or date): 8-6-23
* Distribution (e.g. Ubuntu): OpenSuse Tubleweed
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia rtx 2060

#### Please describe your issue in as much detail as possible:
Steam lags my entire system on load for up to 10 or 15 minutes when I start the client. Client gets past the loading screen and then lags when the store and library load. System is unusable. Even the sound lags,

#### Steps for reproducing this issue:

1. Start Client.
2. Go to the pub
3. Come back and hope it is done lagging.
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12271095/steam-logs.tar.gz)

**Comment by kisak-valve** [comment]
Hello @Skrappjaw, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by Skrappjaw** [comment]
> Hello @Skrappjaw, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

Done

**Comment by drlkf** [comment]
Same issue here, the interface will start lagging the entire system on loading some elements. I suspect an Xorg related issue since sound does not seem to be affected, it stays smooth the entire time, I have yet to try on a Wayland setup.
https://gist.github.com/drlkf/20dd695b01533e216a3b24f61dbcf12c

**Comment by rdyro** [comment]
I'm experiencing a very similar issue, the steam client makes the whole system laggy and unusable for about 20-30 seconds on startup and when updating games. I'm using X11 with Gnome.

```
Steam Version:  1701289036
Steam Client Build Date:  Wed, Nov 29 11:59 AM UTC -08:00
Steam Web Build Date:  Wed, Nov 29 11:03 AM UTC -08:00
Steam API Version:  SteamClient021
```

```
Operating System Version:
Ubuntu 22.04.3 LTS (64 bit)
Kernel Name: Linux
Kernel Version: 6.2.0-37-generic
X Server Vendor: The X.Org Foundation
X Server Release: 12101004
X Window Manager: GNOME Shell
Steam Runtime Version: steam-runtime_0.20231024.64411
Video Card:
Driver: NVIDIA Corporation NVIDIA GeForce RTX 3090/PCIe/SSE2
Driver Version: 4.6.0 NVIDIA 545.23.06
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID: 0x10de
DeviceID: 0x2204
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 2
Primary Display Resolution: 2560 x 1440
Desktop Resolution: 2560 x 1440
Primary Display Size: 23.50" x 13.23" (26.97" diag), 59.7cm x 33.6cm (68.5cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 24576 MB
Supported MSAA Modes: 2x 4x 8x 16x
```

**Comment by rdyro** [comment]
After disabling the iGPU in BIOS, the stutter on startup goes away.

This also fixes another issue I had with steam on Linux where some games wouldn't launch (Last of US Part I). The error output seems to indicate some confusion between nvidia (for the eGPU) and radeon (for the iGPU) drivers.

My CPU is Ryzen 5 7600X.

**Comment by Wemmy0** [comment]
My CPU doesn't even have an iGPU yet I'm still getting severe stuttering on the entire system when launching steam

**Comment by Yorizuka** [comment]
Also an Intel Arc A770 user, same issue.

**Comment by FraYoshi** [comment]
Same issue on Arch, Xfce4 as DE (Xorg). It's like a year since it started. Ended up not opening Steam if possible... I have to close it entirely to stop the lag. Very frustrating.

**Comment by drlkf** [comment]
> Same issue here, the interface will start lagging the entire system on loading some elements. I suspect an Xorg related issue since sound does not seem to be affected, it stays smooth the entire time, I have yet to try on a Wayland setup. https://gist.github.com/drlkf/20dd695b01533e216a3b24f61dbcf12c

i can confirm the issue does not appear on my setup after migrating to wayland (i3 -> sway)

**Comment by Trayshar** [comment]
> i can confirm the issue does not appear on my setup after migrating to wayland (i3 -> sway)

So can I. Issue does not appear with Wayland on my KDE Plasma Manjaro system (kwin WM). Also, the games don't take forever to load anymore, I just thought that was wine's fault lol

**Comment by FraYoshi** [comment]
I just found out that the problem was solved once I re-installed `xdg-desktop-portal-gtk` which I removed at the time lags started to happen for Steam.. check out if it solves it for you too...

**Comment by JulianGro** [comment]
For me it turned out that Steam was using the Integrated Graphics instead of the system default dedicated graphics.
Fully disabling the iGPU in the BIOS fixed the issue for me.

This also explains why I only ran into this after upgrading to a faster CPU; My old CPU didn't have integrated graphics.

Steam had stopped starting for me after a big operating system update and comment https://steamcommunity.com/app/221410/discussions/0/3051736373892813276/?ctp=3#c4358998952355858858 made me disable the iGPU to get Steam starting again.

**Comment by NotMurPh** [comment]
same issue here but i noticed that the problem doesn't exists in flatpak now im looking for dependencies to install

**Comment by bkdwt** [comment]
Same problem on Ubuntu 24.04 with RTX A2000, 555.52.04 driver running on Xorg and an i7 8700. Steam deb installed.

**Comment by Kadah** [comment]
Updated to 22.04 recently and this has gotten a lot worse. On 20.04, disabling hardware acceleration mostly fixed it. Now that makes no difference, input is laggy across the entire system while Steam is running. Its not as extremely bad if Steam is minimized to the system tray. System (CPU and GPU) load is virtually at idle, except for a randomly high kernel load sometimes from seemingly wine processes, though there is no change in the issue while that is happening. 

While Steam is running, all HID inputs are laggy and constantly stutter, all windows and desktop UIs are very slow to respond, any video playback is choppy... pretty much anything displaying to the desktop environment is borked.

Steam hasn't been this bad since the initial UI update and before the previous working mitigation on 20.04. Currently Steam is unusable.I'm going to reinstall the NVIDIA drivers to see if that makes any difference, then switch to the flatpack as others have suggested worked for them.

https://gist.github.com/Kadah/1beaf07fd06780971f38adb48d8e2de9

**Comment by djaiss** [comment]
I have the same issue and @Kadah indeed, Flatpak works better than deb, but it still freezes randomly the entire OS.

**Comment by howdev** [comment]
Yes, I see the same problem too. Whenever Steam is running, drag window of other apps is slow, and web browser also slow, nautilus slow to a state that is not usable
enable or disable gpu acceleration in Steam, does not resolve.

**Comment by Skrappjaw** [comment]
> > > Any updates on this? That "Distro Family: openSUSE" label should be removed.
> > 
> > 
> > I found that on a hybrid graphics system with Intel and nvidia drivers, regardless of using all the recommended settings to force use of the nvidia card, steam is still attempting to use the Intel drivers. How do I know? I had to break my system packages and ability to switch to Intel by uninstalling all the Intel related GPU packages on my system.
> 
> That's interesting, I also have an Optimus setup (NVIDIA GPU/AMD APU). Is Steam still messing up your system when it exclusively uses NVIDIA?

Yes. Steam must be still attempting to use the Intel drivers while the system is set to nvidia.

**Comment by jbracker** [comment]
I have the same problem. Running Manjaro Linux with a Intel i7-8700k and Nvidia GeForce RTX 4070. 

Removing `libva-intel-driver` from my system improved the situation considerably. At least other software is not having issues anymore when steam is running. Though steam it still stutters sometimes.

**Comment by 0XPW87** [comment]
Hello - same issue here, also opensuse. However, the lag from opening steam can occasionally be so severe it takes down the whole operating system with it or leads into unrecoverable freezes.
